/* Parsing and strict validation of what the user pastes back from Claude. Nothing is imported silently. */
import type { AiFeedback } from "./types";
import { criteriaBand, roundBand } from "./bands";

export function extractJson(text: string): { obj: any | null; error: string | null } {
  const t = text.trim();
  if (!t) return { obj: null, error: "Nothing was pasted." };
  const fence = t.match(/```(?:json)?\s*([\s\S]*?)```/i);
  let candidate = fence ? fence[1] : t;
  if (!fence) {
    const a = t.indexOf("{"), b = t.lastIndexOf("}");
    if (a < 0 || b <= a) return { obj: null, error: "No JSON object found. Paste Claude's full reply, including the ```json block." };
    candidate = t.slice(a, b + 1);
  }
  candidate = candidate.replace(/[“”]/g, '"').replace(/,\s*([}\]])/g, "$1");
  try { return { obj: JSON.parse(candidate), error: null }; }
  catch (e: any) {
    const m = String(e?.message || "").match(/position (\d+)/);
    const pos = m ? Number(m[1]) : -1;
    const near = pos >= 0 ? ` Near: "…${candidate.slice(Math.max(0, pos - 40), pos + 20).replace(/\s+/g, " ")}…"` : "";
    return { obj: null, error: "The JSON is malformed (" + (e?.message || "parse error") + ")." + near + " Ask Claude to resend valid JSON only." };
  }
}

const isBand = (v: any) => typeof v === "number" && v >= 0 && v <= 9 && Math.abs(v * 2 - Math.round(v * 2)) < 1e-9;
const strArr = (v: any) => (Array.isArray(v) ? v.filter((x) => typeof x === "string" && x.trim()) : []);

export function validateFeedback(o: any, skill: "writing" | "speaking"): { ok: boolean; errors: string[]; warnings: string[]; fb?: AiFeedback; ref?: string } {
  const errors: string[] = [], warnings: string[] = [];
  if (!o || typeof o !== "object") return { ok: false, errors: ["The reply is not a JSON object."], warnings };
  if (o.type !== "ielts-mastery-feedback") errors.push('Missing "type":"ielts-mastery-feedback". Use the prompt generated by the app.');
  if (o.skill && o.skill !== skill) errors.push(`This feedback is for "${o.skill}", but you are importing it into ${skill}.`);
  const keys = skill === "writing" ? ["TA", "CC", "LR", "GRA"] : ["FC", "LR", "GRA"];
  const crit: Record<string, number | null> = {};
  if (!o.criteria || typeof o.criteria !== "object") errors.push('Missing "criteria".');
  else for (const k of keys) {
    const v = o.criteria[k];
    if (!isBand(v)) errors.push(`criteria.${k} must be a band from 0 to 9 in steps of 0.5 (got ${JSON.stringify(v)}).`);
    else crit[k] = v;
  }
  if (skill === "speaking") {
    const p = o.criteria?.P;
    crit.P = isBand(p) ? p : null;
    if (isBand(p)) warnings.push("Claude returned a Pronunciation band, but it cannot hear audio. It was kept but marked as unreliable.");
  }
  let overall: number | null = isBand(o.overall) ? o.overall : null;
  const calc = criteriaBand(keys.map((k) => crit[k]));
  if (overall == null && calc != null) { overall = calc; warnings.push("No valid overall band - calculated from the criteria."); }
  if (overall != null && calc != null && Math.abs(overall - calc) > 0.5) warnings.push(`Overall (${overall}) differs from the criteria average (${calc}).`);
  const errs = Array.isArray(o.errors) ? o.errors.filter((e: any) => e && typeof e.original === "string").map((e: any) => ({
    original: String(e.original), problem: String(e.category || e.problem || ""), category: String(e.category || "other").toLowerCase(),
    correction: String(e.correction || ""), explanation: String(e.explanation || ""),
  })) : [];
  if (!Array.isArray(o.errors)) warnings.push('No "errors" list.');
  if (errors.length) return { ok: false, errors, warnings };
  const fb: AiFeedback = {
    importedAt: Date.now(), raw: JSON.stringify(o), overall: overall == null ? null : roundBand(overall), criteria: crit, errors: errs,
    vocabulary: strArr(o.vocabulary), grammar: strArr(o.grammar), improvements: strArr(o.improvements),
    improved: typeof o.improved === "string" ? o.improved : undefined,
    band7: typeof o.band7 === "string" ? o.band7 : undefined,
    band8: typeof o.band8 === "string" ? o.band8 : undefined,
    pronunciation: skill === "speaking" ? String(o.pronunciation || "not assessed - transcript only") : undefined,
    summary: [typeof o.summary === "string" ? o.summary : "", o.justification ? Object.entries(o.justification).map(([k, v]) => `${k}: ${v}`).join("\n") : ""].filter(Boolean).join("\n\n"),
  };
  return { ok: true, errors, warnings, fb, ref: typeof o.ref === "string" ? o.ref : undefined };
}

/* ---------------- content pack validation ---------------- */
const CHOICE_TYPES = new Set(["True/False/Not Given", "Yes/No/Not Given", "Matching Headings", "Matching Information", "Matching Features", "Multiple Choice", "Matching", "Map Labelling"]);
const R_TYPES = new Set(["Multiple Choice", "True/False/Not Given", "Yes/No/Not Given", "Matching Headings", "Matching Information", "Matching Features", "Sentence Completion", "Summary Completion", "Note Completion", "Table Completion", "Flow-chart Completion", "Diagram Label Completion", "Short Answer"]);
const L_TYPES = new Set(["Multiple Choice", "Matching", "Form Completion", "Note Completion", "Table Completion", "Sentence Completion", "Summary Completion", "Short Answer", "Map Labelling", "Diagram Label Completion"]);
const norm = (s: string) => s.toLowerCase().replace(/[’‘]/g, "'").replace(/[“”]/g, '"').replace(/\s+/g, " ").trim();

export function validatePack(o: any): { ok: boolean; errors: string[]; warnings: string[]; kind?: string; title?: string; data?: any; count: number } {
  const errors: string[] = [], warnings: string[] = [];
  let count = 0;
  if (!o || typeof o !== "object") return { ok: false, errors: ["Not a JSON object."], warnings, count };
  if (o.type !== "ielts-mastery-pack") errors.push('Missing "type":"ielts-mastery-pack".');
  const kind = o.kind;
  if (!["reading", "listening", "grammar", "vocabulary"].includes(kind)) { errors.push('"kind" must be reading, listening, grammar or vocabulary.'); return { ok: false, errors, warnings, count }; }
  const title = String(o.title || `AI ${kind} pack`);
  if (kind === "reading" || kind === "listening") {
    if (!Array.isArray(o.sets) || !o.sets.length) errors.push('"sets" must be a non-empty list.');
    (o.sets || []).forEach((s: any, si: number) => {
      const P = `sets[${si}]`;
      if (!s.title) errors.push(`${P}.title is missing.`);
      const text = kind === "reading" ? (Array.isArray(s.paras) ? s.paras.map((p: any) => (Array.isArray(p) ? p[1] : "")).join(" ") : "") : (Array.isArray(s.lines) ? s.lines.map((l: any) => (Array.isArray(l) ? l[1] : "")).join(" ") : "");
      if (kind === "reading" && (!Array.isArray(s.paras) || s.paras.some((p: any) => !Array.isArray(p) || p.length !== 2))) errors.push(`${P}.paras must be a list of ["A","text"] pairs.`);
      if (kind === "listening" && (!Array.isArray(s.lines) || s.lines.some((l: any) => !Array.isArray(l) || l.length !== 2))) errors.push(`${P}.lines must be a list of ["W","text"] pairs.`);
      if (text.split(/\s+/).length < 120) warnings.push(`${P}: the text is very short (${text.split(/\s+/).length} words).`);
      if (!Array.isArray(s.groups) || !s.groups.length) errors.push(`${P}.groups must be a non-empty list.`);
      (s.groups || []).forEach((g: any, gi: number) => {
        const G = `${P}.groups[${gi}]`;
        const types = kind === "reading" ? R_TYPES : L_TYPES;
        if (!types.has(g.qtype)) errors.push(`${G}.qtype "${g.qtype}" is not a valid ${kind} question type.`);
        if (!Array.isArray(g.items) || !g.items.length) { errors.push(`${G}.items must be a non-empty list.`); return; }
        g.items.forEach((it: any, ii: number) => {
          const I = `${G}.items[${ii}]`;
          count++;
          if (!it.q) errors.push(`${I}.q is missing.`);
          if (it.a == null || it.a === "" || (Array.isArray(it.a) && !it.a.length)) errors.push(`${I}.a (answer) is missing.`);
          if (!it.ev) errors.push(`${I}.ev (evidence quote) is missing.`);
          else if (!norm(text).includes(norm(String(it.ev)))) errors.push(`${I}.ev is not an exact quote from the ${kind === "reading" ? "passage" : "script"}: "${String(it.ev).slice(0, 60)}".`);
          if (CHOICE_TYPES.has(g.qtype)) {
            const keys = it.opts ? it.opts.map((_: any, k: number) => "ABCDEFGH"[k]) : (g.options || []).map((x: string) => (g.optKey ? x.trim().split(/\s+/)[0] : x));
            if (!keys.length) errors.push(`${I}: choice question without options.`);
            else if (!keys.map((k: string) => k.toUpperCase()).includes(String(it.a).toUpperCase())) errors.push(`${I}.a "${it.a}" is not one of the options (${keys.join(", ")}).`);
          } else {
            if (!Array.isArray(it.a)) it.a = [String(it.a)];
            if (g.limit && it.a.some((x: string) => x.trim().split(/\s+/).filter((t: string) => !/\d/.test(t)).length > g.limit)) errors.push(`${I}: an accepted answer is longer than the word limit (${g.limit}).`);
          }
        });
      });
      s.id = `AI-${kind[0].toUpperCase()}-${Date.now().toString(36)}-${si}`;
      s.mock = null;
      s.level = s.level || "Intermediate";
      s.category = s.category || "General";
      if (kind === "listening") s.voices = s.voices || { M: "gb_m", W: "gb_f", N: "gb_f" };
    });
    return { ok: !errors.length, errors, warnings, kind, title, data: { sets: o.sets }, count };
  }
  if (kind === "grammar") {
    if (!Array.isArray(o.topics) || !o.topics.length) errors.push('"topics" must be a non-empty list.');
    (o.topics || []).forEach((t: any, ti: number) => {
      const T = `topics[${ti}]`;
      if (!t.title) errors.push(`${T}.title is missing.`);
      if (!Array.isArray(t.ex) || !t.ex.length) errors.push(`${T}.ex must be a non-empty list.`);
      (t.ex || []).forEach((e: any, ei: number) => {
        count++;
        if (!e.q || !Array.isArray(e.opts) || e.opts.length < 2) errors.push(`${T}.ex[${ei}] needs "q" and at least 2 "opts".`);
        else if (typeof e.a !== "number" || e.a < 0 || e.a >= e.opts.length) errors.push(`${T}.ex[${ei}].a must be the index (0-${e.opts.length - 1}) of the correct option.`);
        if (!e.why) warnings.push(`${T}.ex[${ei}] has no explanation.`);
        e.lvl = [1, 2, 3].includes(e.lvl) ? e.lvl : 2;
      });
      t.id = "ai-" + String(t.title || "topic").toLowerCase().replace(/[^a-z0-9]+/g, "-") + "-" + Date.now().toString(36);
      t.rules = Array.isArray(t.rules) ? t.rules : []; t.examples = Array.isArray(t.examples) ? t.examples : [];
    });
    return { ok: !errors.length, errors, warnings, kind, title, data: { topics: o.topics }, count };
  }
  if (!o.categories || typeof o.categories !== "object") errors.push('"categories" must be an object of lists.');
  for (const [cat, list] of Object.entries<any>(o.categories || {})) {
    if (!Array.isArray(list)) { errors.push(`categories.${cat} must be a list.`); continue; }
    list.forEach((w: any, i: number) => {
      count++;
      if (!Array.isArray(w) || w.length !== 9 || w.some((x: any) => typeof x !== "string")) errors.push(`categories.${cat}[${i}] must be an array of exactly 9 strings.`);
      else if (!w[3].toLowerCase().includes(w[0].toLowerCase().slice(0, Math.max(3, w[0].length - 3)))) warnings.push(`"${w[0]}": the example sentence does not contain the word.`);
    });
  }
  return { ok: !errors.length, errors, warnings, kind, title, data: { categories: o.categories }, count };
}
