/* ===== GRAMMAR PACK (new topics): original lessons and exercises for IELTS Academic =====
   lvl 1 = B1, lvl 2 = B2, lvl 3 = C1. Distractors reflect typical learner errors, especially of Portuguese speakers. */
export const GRAMMAR_EXTRA = {};

export const NEW_TOPICS = [
/* ---------- 1. PUNCTUATION ---------- */
{ id:"punctuation", title:"Punctuation", summary:"Use commas, semicolons, colons and apostrophes to show how ideas in a sentence relate to each other.",
 rules:[
  "Put a comma after an introductory clause or phrase: 'Although costs rose, profits remained stable.' No comma is needed when the main clause comes first: 'Profits remained stable although costs rose.'",
  "Never join two complete sentences with only a comma (a comma splice). Use a full stop, a semicolon, or a conjunction: 'Prices fell; demand, however, stayed flat.'",
  "Use a semicolon before linking adverbs such as however, therefore and consequently when they join two independent clauses, and put a comma after the adverb.",
  "Use a colon after a complete clause to introduce a list, an explanation or an example: 'Three factors explain this: cost, access and habit.' Do not put a colon directly after a verb or preposition.",
  "Defining relative clauses take no commas; non-defining clauses (extra information) take commas on both sides: 'Lisbon, which is the capital, attracts most visitors.'",
  "Apostrophes show possession (the country's economy, the countries' economies) and contractions; never use them for plurals (1990s, not 1990's) or for the possessive 'its'."
 ],
 examples:[
  "While urban populations grew rapidly, rural areas experienced a steady decline.",
  "Public transport is cheaper than driving; however, many commuters still prefer their cars.",
  "The survey identified two main concerns: rising rents and long commuting times.",
  "The company's profits doubled in the 2010s, although its market share fell slightly."
 ],
 ex:[
 {lvl:1,cefr:"B1",q:"Which sentence is punctuated correctly?",opts:["Although the museum is free, visitor numbers are low.","Although the museum is free visitor numbers are low.","Although, the museum is free, visitor numbers are low.","Although the museum is free; visitor numbers are low."],a:0,why:"When a subordinate clause (Although...) comes first, a comma separates it from the main clause. Leaving it out makes the sentence hard to read, and a semicolon cannot follow a dependent clause because 'Although the museum is free' is not a complete sentence.",natural:"Although admission to the museum is free, visitor numbers remain surprisingly low."},
 {lvl:1,cefr:"B1",q:"The ___ figures show a clear rise in online sales.",opts:["companys","company's","companys'"],a:1,why:"The figures belong to one company, so the singular possessive is 'company's' (noun + 's). 'Companys' has no apostrophe at all, and 'companys'' is not a real form; the plural possessive would be 'companies''.",natural:"The company's figures show a clear rise in online sales over the period."},
 {lvl:2,cefr:"B2",q:"Which sentence avoids a comma splice?",opts:["Car ownership increased, cycling declined.","Car ownership increased, however cycling declined.","Car ownership increased; however, cycling declined.","Car ownership increased however, cycling declined."],a:2,why:"Two independent clauses joined by 'however' need a semicolon (or full stop) before it and a comma after it. Portuguese often allows 'vírgula + porém' between clauses, which leads learners to write '..., however ...', a comma splice in English.",natural:"Car ownership increased steadily; however, cycling declined over the same period."},
 {lvl:2,cefr:"B2",q:"The report highlights three problems___ overcrowding, pollution and noise.",opts:[":",";",","," that are"],a:0,why:"A colon introduces a list after a complete clause ('The report highlights three problems'). A semicolon joins two independent clauses, not a clause and a list, and a comma here would be too weak to signal that the list explains 'three problems'.",natural:"The report highlights three problems: overcrowding, pollution and noise."},
 {lvl:2,cefr:"B2",q:"Which sentence introduces the list correctly?",opts:["The main reasons are: cost, distance and time.","The main reasons are cost, distance and time.","The main reasons are; cost, distance and time.","The main reasons, are cost, distance and time."],a:1,why:"Do not put a colon directly after a verb such as 'are': the list completes the clause, so no punctuation is needed. A colon is only correct after a full clause, e.g. 'There are three main reasons: ...'. A comma between subject and verb is never correct.",natural:"The main reasons for the decline are cost, distance and time."},
 {lvl:2,cefr:"B2",q:"Which sentence uses commas correctly?",opts:["Students, who work part-time, often have lower grades.","Students who work part-time often have lower grades.","Students who work part-time, often have lower grades.","Students, who work part-time often have lower grades."],a:1,why:"The clause 'who work part-time' defines which students are meant, so it takes no commas. With commas, the sentence would claim that all students work part-time. A single comma between the clause and the verb is never correct.",natural:"Students who work part-time often achieve lower grades than those who do not."},
 {lvl:2,cefr:"B2",q:"Spending on healthcare rose sharply in the ___.",opts:["1990's","1990s","1990s'","90's"],a:1,why:"Decades are plurals, not possessives, so no apostrophe is used: 'the 1990s'. Apostrophes for plurals ('1990's') are a frequent error; '90's' is informal and also wrongly punctuated.",natural:"Spending on healthcare rose sharply in the 1990s before levelling off."},
 {lvl:3,cefr:"C1",q:"Which sentence links the two clauses with correct punctuation?",opts:["The government has raised taxes on sugar, as a result consumption has fallen.","The government has raised taxes on sugar; as a result, consumption has fallen.","The government has raised taxes on sugar, as a result, consumption has fallen.","The government has raised taxes on sugar as a result; consumption has fallen."],a:1,why:"'As a result' is a linking adverbial, not a conjunction, so it cannot join two clauses with only commas (that creates a comma splice). A semicolon before it and a comma after it is correct. Moving the semicolon after 'as a result' changes the meaning.",natural:"The government has raised taxes on sugary drinks; as a result, consumption has fallen significantly."},
 {lvl:3,cefr:"C1",q:"Each university sets ___ own admission criteria.",opts:["it's","its","its'"],a:1,why:"The possessive determiner is 'its' with no apostrophe, like 'his' or 'their'. 'It's' always means 'it is' or 'it has', and 'its'' does not exist.",natural:"Each university sets its own admission criteria, which can lead to inconsistencies."},
 {lvl:3,cefr:"C1",q:"Which sentence punctuates the non-defining clause correctly?",opts:["Brazil, which is the largest economy in South America, exports large quantities of soy.","Brazil which is the largest economy in South America, exports large quantities of soy.","Brazil, that is the largest economy in South America, exports large quantities of soy.","Brazil which is the largest economy in South America exports large quantities of soy."],a:0,why:"A clause adding extra information about a unique noun (Brazil) is non-defining: it needs commas on both sides and must use 'which', not 'that'. Omitting one or both commas makes it look like a defining clause, which is illogical for a single country.",natural:"Brazil, which is the largest economy in South America, exports vast quantities of soy."}
 ]},

/* ---------- 2. WORD FORMATION ---------- */
{ id:"word-formation", title:"Word Formation", summary:"Choose the right word class (noun, verb, adjective, adverb) and the right suffix for the position in the sentence.",
 rules:[
  "Check the gap's job: after an article or adjective you need a noun; after a modal or 'to' you need a verb; before a noun or after be/seem you need an adjective; to describe a verb or an adjective you need an adverb.",
  "Common noun suffixes: -tion/-sion (pollution), -ment (development), -ness (awareness), -ity (stability), -ance/-ence (dependence).",
  "Common adjective suffixes: -al (cultural), -ive (effective), -ous (dangerous), -ful/-less (useful, useless), -able/-ible (affordable).",
  "Adverbs usually add -ly to the adjective (significant → significantly). In Task 1 use adjective + noun (a sharp rise) or verb + adverb (rose sharply).",
  "Watch for confusing pairs: economic (related to the economy) vs economical (saving money); effect (noun) vs affect (verb); historic (important) vs historical (about the past).",
  "Prefixes change meaning, not class: un-, in-, im-, ir-, dis-, over-, under- (unemployment, irreversible, overpopulation)."
 ],
 examples:[
  "There was a significant increase in unemployment, which rose significantly after 2008.",
  "Governments should raise public awareness of the dangers of air pollution.",
  "Renewable energy is becoming increasingly affordable in developing countries."
 ],
 ex:[
 {lvl:1,cefr:"B1",q:"The number of tourists rose ___ between 2010 and 2015.",opts:["dramatic","dramatically","drama"],a:1,why:"The gap describes the verb 'rose', so an adverb is required. 'Dramatic' is an adjective and would need a noun: 'a dramatic rise'.",natural:"The number of tourists rose dramatically between 2010 and 2015."},
 {lvl:1,cefr:"B1",q:"Many cities are trying to reduce air ___.",opts:["polluted","pollute","pollution"],a:2,why:"After 'air' used as a modifier, the sentence needs a noun as the object of 'reduce'. 'Pollute' is a verb and 'polluted' is an adjective or past participle.",natural:"Many cities are trying to reduce air pollution by restricting car use."},
 {lvl:2,cefr:"B2",q:"The pie chart shows that rent accounts for the largest ___ of household spending.",opts:["proportional","proportion","proportionally","proportionate"],a:1,why:"After 'the largest' (article + adjective) the gap must be a noun. 'Proportional' and 'proportionate' are adjectives; 'proportionally' is an adverb.",natural:"Rent accounts for the largest proportion of household spending."},
 {lvl:2,cefr:"B2",q:"Raising fuel taxes could have a serious ___ on low-income families.",opts:["affect","effect","effective","affection"],a:1,why:"After 'a serious' you need a noun: 'effect'. 'Affect' is normally a verb (to affect someone), 'effective' is an adjective and 'affection' means love or fondness.",natural:"Raising fuel taxes could have a serious effect on low-income families."},
 {lvl:2,cefr:"B2",q:"Tourism makes an important contribution to the country's ___ growth.",opts:["economical","economic","economy's","economically"],a:1,why:"'Economic' means related to the economy, which is the meaning here. 'Economical' means cheap to run or not wasteful (an economical car). The adverb cannot modify a noun.",natural:"Tourism makes a vital contribution to the country's economic growth."},
 {lvl:2,cefr:"B2",q:"Many young people find it difficult to achieve financial ___.",opts:["independent","independence","independently","depend"],a:1,why:"After the verb 'achieve' and the adjective 'financial', a noun is needed: 'independence'. 'Independent' is the adjective form, a common slip because Portuguese 'independente' is similar.",natural:"Many young people find it difficult to achieve financial independence."},
 {lvl:2,cefr:"B2",q:"Public transport should be made more ___ for elderly and disabled passengers.",opts:["access","accessibility","accessible","accessibly"],a:2,why:"After 'be made more', the gap describes the noun 'public transport', so an adjective is needed. 'Access' and 'accessibility' are nouns; 'accessibly' is an adverb.",natural:"Public transport should be made more accessible to elderly and disabled passengers."},
 {lvl:3,cefr:"C1",q:"Deforestation in some regions may already be ___, even if logging stops.",opts:["reversible","irreversible","unreversible","irreversibly"],a:1,why:"The sense ('even if logging stops') requires a negative adjective. The negative prefix for 'reversible' is ir-, not un-. The adverb 'irreversibly' cannot follow 'be' on its own.",natural:"In some regions, the damage caused by deforestation may already be irreversible."},
 {lvl:3,cefr:"C1",q:"The ___ of the new policy will depend on how strictly it is enforced.",opts:["effective","effectively","effectiveness","effectivity"],a:2,why:"After 'The' and before 'of', a noun is needed. The standard noun is 'effectiveness'; 'effectivity' is a false form influenced by Portuguese 'efetividade'.",natural:"The effectiveness of the new policy will depend on how strictly it is enforced."},
 {lvl:3,cefr:"C1",q:"Ouro Preto is a ___ town, listed as a World Heritage Site in 1980.",opts:["historic","historical","history","historically"],a:0,why:"'Historic' means important in history and worth preserving, which suits a World Heritage town. 'Historical' means connected with the study of the past (historical records). 'History' is a noun and 'historically' an adverb.",natural:"Ouro Preto is a historic town that was listed as a World Heritage Site in 1980."}
 ]},
/* ---------- 3. CONJUNCTIONS ---------- */
{ id:"conjunctions", title:"Conjunctions", summary:"Link ideas precisely with contrast, condition and purpose words, and use the right grammar after each one.",
 rules:[
  "Although / even though / while + full clause (subject + verb): 'Although prices rose, demand increased.' Do not add 'but' in the same sentence.",
  "Despite / in spite of + noun, pronoun or -ing form, never a full clause: 'Despite the rise in prices...', 'Despite rising prices...', or 'Despite the fact that prices rose...'.",
  "Whereas / while compare two contrasting facts, very useful in Task 1: 'Sales rose in Asia, whereas they fell in Europe.'",
  "Unless means 'if not' and takes a positive verb: 'Unless action is taken...' (not 'unless action is not taken'). Use the present tense for future meaning after unless, if and as long as.",
  "So that + clause (often with can/could/will/would) expresses purpose; 'so' alone expresses result. In order to / so as to + infinitive also express purpose.",
  "As long as / provided that express a condition; whereas and while express contrast; as and since can express reason at the start of a sentence."
 ],
 examples:[
  "Although the population grew, the number of hospitals remained unchanged.",
  "Despite heavy investment, the project failed to attract private funding.",
  "Coal consumption fell sharply, whereas the use of solar power tripled.",
  "Unless governments act quickly, many coastal cities will face severe flooding."
 ],
 ex:[
 {lvl:1,cefr:"B1",q:"___ the weather was bad, the festival attracted thousands of visitors.",opts:["Despite","Although","However"],a:1,why:"The gap is followed by a full clause (the weather was bad), so a conjunction such as 'although' is required. 'Despite' needs a noun or -ing form, and 'however' is an adverb that cannot join two clauses.",natural:"Although the weather was poor, the festival attracted thousands of visitors."},
 {lvl:1,cefr:"B1",q:"Which sentence is grammatically correct?",opts:["Although the course was expensive, but many students enrolled.","Although the course was expensive, many students enrolled.","Although the course was expensive, however many students enrolled."],a:1,why:"'Although' already shows contrast, so the main clause must not start with 'but' or 'however'. Portuguese speakers often write 'Embora..., mas...' patterns, which are incorrect in English.",natural:"Although the course was expensive, many students enrolled."},
 {lvl:2,cefr:"B2",q:"___ rising costs, the number of international students continued to grow.",opts:["Although","Despite","Even though","Whereas"],a:1,why:"'Rising costs' is a noun phrase, not a clause, so a preposition like 'despite' is needed. 'Although', 'even though' and 'whereas' must be followed by subject + verb.",natural:"Despite rising costs, the number of international students continued to grow."},
 {lvl:2,cefr:"B2",q:"In 2020, 60% of men used the gym regularly, ___ only 35% of women did so.",opts:["despite","whereas","unless","so that"],a:1,why:"Two contrasting facts are being compared, so 'whereas' is ideal. 'Despite' needs a noun, 'unless' expresses a condition, and 'so that' expresses purpose.",natural:"In 2020, 60% of men used the gym regularly, whereas only 35% of women did so."},
 {lvl:2,cefr:"B2",q:"Traffic congestion will get worse ___ more people use public transport.",opts:["if","unless","whereas","despite"],a:1,why:"The meaning is 'if more people do not use public transport', which is exactly 'unless'. 'If' reverses the logic, and 'whereas' and 'despite' do not express conditions.",natural:"Traffic congestion will continue to worsen unless more people switch to public transport."},
 {lvl:2,cefr:"B2",q:"Many cities have built cycle lanes ___ residents can travel safely without a car.",opts:["so that","so","in order to","because of"],a:0,why:"The second part is a full clause expressing purpose, so 'so that' is correct. 'In order to' must be followed by a verb, not a subject; 'so' alone expresses result; 'because of' needs a noun.",natural:"Many cities have built cycle lanes so that residents can travel safely without a car."},
 {lvl:2,cefr:"B2",q:"Unless the government ___ more in research, the country will fall behind its competitors.",opts:["invests","will invest","doesn't invest","would invest"],a:0,why:"After 'unless' (like 'if'), use the present simple for a future meaning, and keep the verb positive because 'unless' already means 'if not'. 'Doesn't invest' creates a double negative.",natural:"Unless the government invests more in research, the country will fall behind its competitors."},
 {lvl:3,cefr:"C1",q:"___ the fact that unemployment has fallen, wages have barely increased.",opts:["Although","Despite","Even","Whereas"],a:1,why:"'The fact that' turns a clause into a noun phrase, so it follows a preposition: 'despite the fact that'. 'Although the fact that' is a common hybrid error; 'although' must be followed directly by a clause.",natural:"Despite the fact that unemployment has fallen, wages have barely increased."},
 {lvl:3,cefr:"C1",q:"Remote working can boost productivity, ___ employees have a suitable space at home.",opts:["provided that","in case","whereas","even if"],a:0,why:"The second clause states a condition that must be met, so 'provided that' (= only if) fits. 'In case' means as a precaution, 'whereas' introduces a contrast and 'even if' implies the result happens regardless.",natural:"Remote working can boost productivity, provided that employees have a suitable space at home."},
 {lvl:3,cefr:"C1",q:"___ some argue that zoos protect endangered species, others believe they are cruel.",opts:["While","Despite","Because","Unless"],a:0,why:"'While' can introduce a contrasting view in Task 2 discussion essays and is followed by a full clause. 'Despite' needs a noun, and 'because' and 'unless' do not express contrast.",natural:"While some argue that zoos protect endangered species, others believe that keeping animals in captivity is cruel."}
 ]},

/* ---------- 4. QUANTIFIERS ---------- */
{ id:"quantifiers", title:"Countable & Uncountable / Quantifiers", summary:"Match the quantifier to the noun: many/few/a number of with countable plurals, much/little/an amount of with uncountable nouns.",
 rules:[
  "Countable nouns have plurals (students, cars). Uncountable nouns have no plural and take a singular verb: information, advice, research, equipment, traffic, evidence, knowledge, furniture.",
  "Many, few, a few, a number of, fewer + plural countable nouns; much, little, a little, an amount of, less + uncountable nouns.",
  "A few / a little = some (positive); few / little = not many / not much (negative, often a problem): 'Few students passed' sounds like a disappointing result.",
  "'The number of + plural noun' takes a singular verb (The number of cars has risen); 'a number of + plural noun' means 'several' and takes a plural verb (A number of cars were stolen).",
  "In Task 1, use 'the number of' for countable data (people, cars) and 'the amount of' or 'the quantity of' for uncountable data (water, energy, money).",
  "Words that are countable in Portuguese are often uncountable in English: 'informações' = information, 'conselhos' = advice, 'pesquisas' = research, 'equipamentos' = equipment."
 ],
 examples:[
  "The number of international students has doubled since 2005.",
  "The amount of electricity generated from wind rose steadily.",
  "Few countries met their emission targets, and a few even increased their output.",
  "There is little evidence that the policy reduced crime."
 ],
 ex:[
 {lvl:1,cefr:"B1",q:"The website gives a lot of useful ___ about scholarships.",opts:["informations","information","an information"],a:1,why:"'Information' is uncountable in English, so it has no plural and no 'an'. 'Informations' is a typical error influenced by Portuguese 'informações'.",natural:"The website provides a great deal of useful information about scholarships."},
 {lvl:1,cefr:"B1",q:"How ___ people visited the museum last year?",opts:["much","many","lot"],a:1,why:"'People' is a plural countable noun, so 'how many' is required. 'How much' is used with uncountable nouns such as money or time.",natural:"How many people visited the museum last year?"},
 {lvl:2,cefr:"B2",q:"The graph shows ___ water consumed by households between 1990 and 2020.",opts:["the number of","the amount of","the many","a few"],a:1,why:"'Water' is uncountable, so Task 1 language needs 'the amount of'. 'The number of' is only for countable plurals such as people or litres.",natural:"The graph shows the amount of water consumed by households between 1990 and 2020."},
 {lvl:2,cefr:"B2",q:"The number of cars on the road ___ dramatically since 2000.",opts:["have increased","has increased","are increasing","increase"],a:1,why:"The subject is 'the number', which is singular, so the verb is 'has'. Learners often agree the verb with 'cars', but that noun belongs to the 'of' phrase, not the subject.",natural:"The number of cars on the road has increased dramatically since 2000."},
 {lvl:2,cefr:"B2",q:"Unfortunately, ___ students were aware of the free tutoring service, so it was rarely used.",opts:["a few","few","little","a little"],a:1,why:"The context (unfortunately, rarely used) is negative, so 'few' (= not many) is correct. 'A few' is positive (= some), and 'little' / 'a little' are for uncountable nouns.",natural:"Unfortunately, few students were aware of the free tutoring service, so it was rarely used."},
 {lvl:2,cefr:"B2",q:"Scientists have carried out a great deal of ___ into the causes of obesity.",opts:["researches","research","a research","many research"],a:1,why:"'Research' is uncountable in academic English, and 'a great deal of' is only used with uncountable nouns. 'Researches' and 'a research' reflect Portuguese 'pesquisas / uma pesquisa'; use 'studies' or 'a study' if you need a countable noun.",natural:"Scientists have carried out a great deal of research into the causes of obesity."},
 {lvl:2,cefr:"B2",q:"There were ___ accidents on the motorway after the speed limit was reduced.",opts:["less","fewer","little","much"],a:1,why:"'Accidents' is a countable plural, so the comparative quantifier is 'fewer'. 'Less' is used with uncountable nouns (less traffic), although it is common in informal speech.",natural:"There were fewer accidents on the motorway after the speed limit was reduced."},
 {lvl:3,cefr:"C1",q:"___ of factors have contributed to the decline in bee populations.",opts:["A number","The number","An amount","A great deal"],a:0,why:"'A number of + plural noun' means 'several' and takes a plural verb (have). 'The number of' would need a singular verb and refers to a count, and 'an amount of' / 'a great deal of' are for uncountable nouns.",natural:"A number of factors have contributed to the decline in bee populations."},
 {lvl:3,cefr:"C1",q:"The new laboratory equipment ___ expected to arrive next month.",opts:["are","is","were","have been"],a:1,why:"'Equipment' is uncountable and takes a singular verb. Learners often treat it as plural because Portuguese uses 'equipamentos'.",natural:"The new laboratory equipment is expected to arrive next month."},
 {lvl:3,cefr:"C1",q:"There is ___ evidence that homework improves the performance of very young children.",opts:["few","little","a few","many"],a:1,why:"'Evidence' is uncountable, so 'little' (= not much) is required; this hedged negative is typical in academic writing. 'Few', 'a few' and 'many' can only be used with countable plurals.",natural:"There is little evidence that homework improves the academic performance of very young children."}
 ]},
/* ---------- 5. NOMINALISATION ---------- */
{ id:"nominalisation", title:"Nominalisation", summary:"Turn verbs and adjectives into nouns to write in a more concise, objective academic style.",
 rules:[
  "Nominalisation turns an action or quality into a noun: 'prices increased' becomes 'the increase in prices'; 'people are aware' becomes 'public awareness'.",
  "Each noun has its own prepositions: an increase/rise/fall/decline IN something; the development/introduction/use OF something; an effect/impact ON something; a demand FOR something.",
  "Nominalised subjects make sentences more objective and allow you to pack in cause and effect: 'The introduction of tuition fees led to a fall in applications.'",
  "Use verbs such as lead to, result in, contribute to, cause and be due to to link two nominalised ideas.",
  "Use an adjective, not an adverb, to modify the noun: 'rose rapidly' becomes 'a rapid rise' (not 'a rapidly rise').",
  "Do not overdo it: one or two nominal groups per sentence are enough; a chain of abstract nouns can become unclear."
 ],
 examples:[
  "The rapid expansion of cities has put pressure on water supplies.",
  "There was a steady decline in the consumption of red meat.",
  "The introduction of a congestion charge resulted in a reduction in traffic."
 ],
 ex:[
 {lvl:1,cefr:"B1",q:"There was a sharp ___ in the price of oil in 2008.",opts:["increase","increased","increasing"],a:0,why:"After the article 'a' and the adjective 'sharp', the gap needs a noun. 'Increased' is a verb or adjective form and 'increasing' is a participle.",natural:"There was a sharp increase in the price of oil in 2008."},
 {lvl:1,cefr:"B1",q:"The chart shows a gradual ___ in the number of smokers.",opts:["decline","declining","declined"],a:0,why:"'A gradual ___' requires a noun, and 'decline' is both a verb and a noun. The other forms cannot follow an article and adjective in this way.",natural:"The chart shows a gradual decline in the number of smokers."},
 {lvl:2,cefr:"B2",q:"The government introduced a sugar tax. → The ___ of a sugar tax reduced consumption of soft drinks.",opts:["introduce","introduction","introducing of","introduced"],a:1,why:"'The ___ of' needs a noun: 'introduction'. 'The introducing of' is grammatically awkward and not used in academic writing.",natural:"The introduction of a sugar tax reduced the consumption of soft drinks."},
 {lvl:2,cefr:"B2",q:"Social media has had a significant impact ___ the way teenagers communicate.",opts:["in","on","at","for"],a:1,why:"The noun 'impact' (like 'effect' and 'influence') is followed by 'on'. Portuguese 'impacto em/nos' often leads to 'impact in', which is incorrect.",natural:"Social media has had a significant impact on the way teenagers communicate."},
 {lvl:2,cefr:"B2",q:"Unemployment rose rapidly. → There was a ___ rise in unemployment.",opts:["rapid","rapidly","rapidity","more rapidly"],a:0,why:"When a verb becomes a noun, its adverb becomes an adjective: 'rose rapidly' → 'a rapid rise'. An adverb cannot modify a noun.",natural:"There was a rapid rise in unemployment."},
 {lvl:2,cefr:"B2",q:"Which sentence is the most academic version of 'Because people are not aware of the risks, many accidents happen'?",opts:["A lack of awareness of the risks leads to many accidents.","People are not aware of the risks so a lot of accidents happen.","Because people don't know about the risks, lots of accidents happen.","A lack of aware about risks makes many accident."],a:0,why:"The first option nominalises 'not aware' into 'a lack of awareness' and links cause and effect with 'leads to', which is concise and objective. The last option uses the adjective 'aware' where a noun is needed and has other errors.",natural:"A lack of awareness of the risks leads to a large number of accidents."},
 {lvl:2,cefr:"B2",q:"There has been a growing demand ___ renewable energy in recent years.",opts:["of","for","to","by"],a:1,why:"The noun 'demand' is followed by 'for' (demand for something). Portuguese 'demanda de' often causes the error 'demand of'.",natural:"There has been a growing demand for renewable energy in recent years."},
 {lvl:3,cefr:"C1",q:"Factories closed, and as a result many workers moved to the cities. → The ___ of factories resulted in large-scale migration to urban areas.",opts:["closing down","closure","close","closed"],a:1,why:"'Closure' is the standard noun for the action of shutting a factory permanently and is the most formal choice. 'Close' as a noun means 'end' and 'closed' is an adjective; 'closing down' is possible but less concise.",natural:"The closure of factories resulted in large-scale migration to urban areas."},
 {lvl:3,cefr:"C1",q:"Which sentence uses nominalisation effectively?",opts:["The failure to invest in infrastructure has contributed to the deterioration of public services.","Because they failed to invest in infrastructure, public services have got worse.","The fail of investing in infrastructure contributed to deteriorate the public services.","The failure investment in infrastructure deteriorated public services."],a:0,why:"The first option uses two well-formed nominal groups (the failure to invest, the deterioration of public services) linked by 'contributed to'. 'The fail of' uses a verb as a noun, and 'contributed to deteriorate' wrongly uses an infinitive after 'to' as a preposition.",natural:"The failure to invest in infrastructure has contributed to the deterioration of public services."},
 {lvl:3,cefr:"C1",q:"The ___ of the region's coastline is largely due to rising sea levels.",opts:["erosion","eroding","erode","eroded"],a:0,why:"After 'The' and before 'of', a noun is needed: 'erosion'. Using the bare verb or a participle in a noun position is a typical error.",natural:"The erosion of the region's coastline is largely due to rising sea levels."}
 ]},

/* ---------- 6. HEDGING ---------- */
{ id:"hedging", title:"Hedging Language", summary:"Soften claims so they are accurate and academic: avoid absolute statements that cannot be proved.",
 rules:[
  "Use modal verbs to show possibility: may, might, could, can ('This may lead to...').",
  "Use tend to / appear to / seem to + infinitive to describe general patterns without claiming certainty: 'Older people tend to read more newspapers.'",
  "Use impersonal phrases to present arguments objectively: 'It could be argued that...', 'It is widely believed that...', 'It is likely that...'.",
  "Use frequency and quantity qualifiers instead of absolutes: often, generally, in many cases, most, some (not always, never, all, everyone).",
  "Use adjectives and adverbs of probability: likely, possible, probably, arguably, to some extent, largely.",
  "Do not over-hedge: 'It might possibly perhaps be...' sounds weak. One hedge per claim is usually enough, and Task 1 data should be reported directly."
 ],
 examples:[
  "It could be argued that tourism does more harm than good to historic towns.",
  "People who live in cities tend to have less contact with nature.",
  "Video games appear to improve certain cognitive skills.",
  "This trend is likely to continue over the next decade."
 ],
 ex:[
 {lvl:1,cefr:"B1",q:"Too much screen time ___ affect children's sleep.",opts:["may","must","is"],a:0,why:"'May' presents the effect as a possibility, which is appropriate for a general claim. 'Must' sounds like a certainty or obligation, and 'is affect' is ungrammatical.",natural:"Excessive screen time may affect children's sleep."},
 {lvl:1,cefr:"B1",q:"Young people ___ use social media more than older people.",opts:["tend to","tends to","are tend to"],a:0,why:"'Tend to' + infinitive describes a general pattern. With the plural subject 'young people' the verb is 'tend', not 'tends', and 'are tend' mixes two structures.",natural:"Young people tend to use social media more than older generations."},
 {lvl:2,cefr:"B2",q:"Which sentence is the most appropriate for an academic essay?",opts:["Everyone knows that fast food causes obesity.","Fast food always causes obesity.","Fast food is likely to be a major contributor to obesity.","Fast food is the only reason why people are fat."],a:2,why:"'Is likely to be a major contributor' makes a cautious, defensible claim. The other options use absolutes (everyone, always, the only) that an examiner sees as overgeneralisation.",natural:"Fast food is likely to be a major contributor to rising obesity rates."},
 {lvl:2,cefr:"B2",q:"It ___ that public libraries are no longer necessary in the digital age.",opts:["could be argued","could argue","can argues","is arguing"],a:0,why:"The impersonal passive 'It could be argued that' presents a view objectively. 'It could argue' is active, so 'it' would be doing the arguing, which makes no sense here.",natural:"It could be argued that public libraries are no longer necessary in the digital age."},
 {lvl:2,cefr:"B2",q:"The new medicine ___ to reduce symptoms in most patients, although further trials are needed.",opts:["appears","proves","is appearing","appear"],a:0,why:"'Appears to' softens the claim, which matches 'further trials are needed'. 'Proves' is too strong, and the continuous 'is appearing' is not used with this meaning. The singular subject needs 'appears'.",natural:"The new medicine appears to reduce symptoms in most patients, although further trials are needed."},
 {lvl:2,cefr:"B2",q:"Which phrase best replaces 'always' in: 'Working from home always increases productivity'?",opts:["in many cases","never","definitely","in all cases"],a:0,why:"'In many cases' turns an absolute claim into a qualified one that is easier to defend. 'Definitely' and 'in all cases' are as absolute as 'always', and 'never' reverses the meaning.",natural:"In many cases, working from home increases productivity."},
 {lvl:2,cefr:"B2",q:"It is ___ that the number of electric cars will continue to grow.",opts:["likely","probably","maybe","perhaps"],a:0,why:"After 'It is ... that', an adjective is needed: 'likely'. 'Probably' is an adverb, and 'maybe' and 'perhaps' cannot follow 'It is' in this structure; this is a common slip for speakers of Portuguese, where 'é provável' and 'provavelmente' are easily confused.",natural:"It is likely that the number of electric cars will continue to grow."},
 {lvl:3,cefr:"C1",q:"Which sentence is over-hedged?",opts:["It may perhaps be possible that this could possibly reduce crime.","This policy may reduce crime.","This policy is likely to reduce crime to some extent.","There is some evidence that this policy reduces crime."],a:0,why:"The first option piles up four hedges (may, perhaps, possible, could possibly), making the writer sound unsure and wordy. Good academic writing uses just enough hedging, as in the other three options.",natural:"This policy may reduce crime to some extent."},
 {lvl:3,cefr:"C1",q:"Urbanisation has ___ contributed to the loss of agricultural land, although other factors also played a role.",opts:["largely","totally","alone","only"],a:0,why:"'Largely' indicates a major but not exclusive cause, matching 'other factors also played a role'. 'Totally', 'alone' and 'only' contradict the second clause.",natural:"Urbanisation has largely contributed to the loss of agricultural land, although other factors have also played a role."},
 {lvl:3,cefr:"C1",q:"Which version of the claim is best for a Task 2 essay?",opts:["Arguably, the benefits of globalisation have not been shared equally.","It is a fact that globalisation is bad for everybody.","Globalisation has destroyed all local cultures.","Without doubt globalisation only helps rich countries."],a:0,why:"'Arguably' signals a reasoned opinion while allowing for disagreement, and the claim is limited and precise. The other options make sweeping claims (everybody, all, only) and present opinion as fact.",natural:"Arguably, the benefits of globalisation have not been shared equally between developed and developing nations."}
 ]},
/* ---------- 7. PARALLEL STRUCTURE ---------- */
{ id:"parallel-structure", title:"Parallel Structure", summary:"Items joined by and, or, but, or paired conjunctions must have the same grammatical form.",
 rules:[
  "Items in a list must share the same form: all nouns, all -ing forms, all infinitives or all clauses: 'Cycling is cheap, healthy and environmentally friendly.'",
  "Paired conjunctions (both...and, either...or, neither...nor, not only...but also) must be followed by the same type of word or phrase.",
  "In comparisons, compare like with like: 'The population of Tokyo is larger than that of London' (not 'than London').",
  "With infinitives in a list, either repeat 'to' before every item or use it only once at the start; do not mix the two.",
  "Keep the same tense and voice across a series of verbs unless the time really changes: 'Sales rose in May, peaked in June and fell in July.'",
  "Parallelism is a key part of 'grammatical range and accuracy' and makes Task 2 arguments easier to follow."
 ],
 examples:[
  "Governments should invest in public transport, reduce fuel subsidies and promote cycling.",
  "The scheme was not only expensive but also ineffective.",
  "The cost of living in Paris is higher than that in Lisbon."
 ],
 ex:[
 {lvl:1,cefr:"B1",q:"In my free time I enjoy reading, swimming and ___.",opts:["to cook","cooking","cook"],a:1,why:"The other items in the list are -ing forms (reading, swimming), so the last item must also be 'cooking'. Mixing 'to cook' or 'cook' breaks the parallel pattern.",natural:"In my free time, I enjoy reading, swimming and cooking."},
 {lvl:1,cefr:"B1",q:"The new park is large, clean and ___.",opts:["safety","safe","safely"],a:1,why:"'Large' and 'clean' are adjectives, so the third item must be the adjective 'safe'. 'Safety' is a noun and 'safely' an adverb.",natural:"The new park is large, clean and safe."},
 {lvl:2,cefr:"B2",q:"Living in a big city can be both exciting and ___.",opts:["stress","stressful","it is stressful","stressing"],a:1,why:"After 'both exciting and', the second item must match 'exciting', which is an adjective. 'Stressful' is the correct adjective; 'stress' is a noun and 'it is stressful' is a full clause.",natural:"Living in a big city can be both exciting and stressful."},
 {lvl:2,cefr:"B2",q:"The aim of the programme is to reduce poverty, improve health and ___ access to education.",opts:["increasing","to increasing","increase","increased"],a:2,why:"'To' appears once before 'reduce', so all items use the bare infinitive: reduce, improve, increase. 'Increasing' and 'increased' break the pattern; 'to increasing' is wrong in any case.",natural:"The aim of the programme is to reduce poverty, improve health and increase access to education."},
 {lvl:2,cefr:"B2",q:"Students can either study online ___ attend classes on campus.",opts:["or","nor","and","or they can to"],a:0,why:"'Either' is always paired with 'or', and the structures after each must match (study online / attend classes). 'Nor' goes with 'neither', and 'and' goes with 'both'.",natural:"Students can either study online or attend classes on campus."},
 {lvl:2,cefr:"B2",q:"Between 2000 and 2010, the price of rice rose, ___ in 2012 and then fell slightly.",opts:["peaking","peaked","has peaked","was peaked"],a:1,why:"The series of verbs is in the past simple (rose ... fell), so the middle verb must be 'peaked'. The present perfect and the passive break the parallel structure.",natural:"Between 2000 and 2010, the price of rice rose, peaked in 2012 and then fell slightly."},
 {lvl:2,cefr:"B2",q:"Which sentence has correct parallel structure?",opts:["Exercise improves mood, sleep, and it reduces stress.","Exercise improves mood, sleep and reducing stress.","Exercise improves mood and sleep, and it reduces stress.","Exercise improves mood, to sleep and reduces stress."],a:2,why:"The third option joins two complete, parallel clauses (Exercise improves... and it reduces...). The others mix nouns with a clause or -ing form inside the same list.",natural:"Regular exercise improves mood and sleep, and it also reduces stress."},
 {lvl:3,cefr:"C1",q:"The scheme was criticised not only for its high cost but also ___.",opts:["because it was ineffective","for its lack of effectiveness","it was ineffective","ineffective"],a:1,why:"'Not only for its high cost' (preposition + noun phrase) must be balanced by 'but also for its lack of effectiveness'. A 'because' clause or a bare adjective breaks the parallel structure.",natural:"The scheme was criticised not only for its high cost but also for its lack of effectiveness."},
 {lvl:3,cefr:"C1",q:"The average salary in Germany is considerably higher than ___ Brazil.",opts:["in","that in","Brazil's salary in","those of"],a:1,why:"Compare like with like: salary in Germany with the salary in Brazil. 'That in' replaces 'the average salary'. 'Than in Brazil' wrongly compares a salary with a country, and 'those' is plural.",natural:"The average salary in Germany is considerably higher than that in Brazil."},
 {lvl:3,cefr:"C1",q:"Neither raising taxes ___ cutting public spending is likely to solve the problem on its own.",opts:["or","nor","and","nor to"],a:1,why:"'Neither' pairs with 'nor', and the two items must match (raising taxes / cutting public spending, both -ing forms). 'Neither ... or' is a common error, and 'nor to cutting' breaks the parallel form.",natural:"Neither raising taxes nor cutting public spending is likely to solve the problem on its own."}
 ]},

/* ---------- 8. PARTICIPLE CLAUSES ---------- */
{ id:"participle-clauses", title:"Participle Clauses", summary:"Use -ing, -ed and having + past participle clauses to combine ideas concisely, as long as the subjects match.",
 rules:[
  "Present participle (-ing) clauses show an active action happening at the same time or a reason: 'Living in a small town, she rarely uses public transport.'",
  "Past participle (-ed / 3rd form) clauses have a passive meaning: 'Built in 1890, the bridge is still in use.' (= The bridge was built in 1890.)",
  "Perfect participle (having + past participle) shows that one action was completed before another: 'Having finished the survey, the researchers analysed the data.'",
  "The subject of the participle clause must be the same as the subject of the main clause; otherwise you create a dangling participle ('Walking to work, the rain started' is wrong).",
  "Participle clauses can also reduce relative clauses: 'Students taking the test' (= who are taking), 'the data collected in 2020' (= which was collected).",
  "Use 'Not' before the participle for the negative: 'Not knowing the area, the tourists got lost.'"
 ],
 examples:[
  "Having completed the experiment, the team published their findings.",
  "Built in the 18th century, the church is one of the finest examples of Baroque architecture in Brazil.",
  "The chart shows the number of people using public transport in four cities.",
  "Not having enough funding, many small museums are forced to close."
 ],
 ex:[
 {lvl:1,cefr:"B1",q:"The table shows the number of students ___ abroad in 2022.",opts:["studying","studied","study"],a:0,why:"'Studying' reduces the relative clause 'who were studying' and has an active meaning. 'Studied' would be passive (the students were studied), and the bare verb 'study' cannot follow a noun like this.",natural:"The table shows the number of students studying abroad in 2022."},
 {lvl:1,cefr:"B1",q:"___ in 1711, Ouro Preto was once the capital of Minas Gerais.",opts:["Founding","Founded","Having founded"],a:1,why:"The town was founded by someone, so the meaning is passive and a past participle is needed. 'Founding' and 'Having founded' are active, suggesting the town founded something.",natural:"Founded in 1711, Ouro Preto was once the capital of Minas Gerais."},
 {lvl:2,cefr:"B2",q:"___ the survey, the researchers analysed the results.",opts:["Having completed","Completed","Having been completed","Completing of"],a:0,why:"The researchers completed the survey first and then analysed the results, so the perfect participle (active) 'Having completed' is correct. 'Completed' and 'Having been completed' are passive, implying the researchers were completed.",natural:"Having completed the survey, the researchers analysed the results."},
 {lvl:2,cefr:"B2",q:"Which sentence is correct?",opts:["Walking along the beach, the sun began to set.","Walking along the beach, we watched the sun set.","Walked along the beach, we watched the sun set.","Walking along the beach, the sunset was beautiful."],a:1,why:"The subject of 'walking' must be the subject of the main clause. In the second option 'we' were walking. In the first and last options the sun or the sunset seems to be walking, which is a dangling participle.",natural:"Walking along the beach, we watched the sun set."},
 {lvl:2,cefr:"B2",q:"The products ___ in this factory are exported to over 30 countries.",opts:["making","made","are made","have made"],a:1,why:"'Made' reduces 'which are made' and has a passive meaning: the products do not make anything. 'Making' is active, and 'are made' would create two main verbs in the same clause.",natural:"The products manufactured in this factory are exported to over 30 countries."},
 {lvl:2,cefr:"B2",q:"___ the importance of exercise, many companies now offer free gym membership.",opts:["Recognising","Recognised","Recognise","To recognising"],a:0,why:"The companies recognise the importance of exercise (active), so the present participle 'Recognising' is correct. 'Recognised' would mean the companies were recognised.",natural:"Recognising the importance of exercise, many companies now offer their staff free gym membership."},
 {lvl:2,cefr:"B2",q:"___ enough money, many graduates continue to live with their parents.",opts:["Not having","Having not","No having","Don't having"],a:0,why:"The negative of a participle clause is formed with 'not' before the participle: 'Not having'. 'No having' and 'Don't having' are calques that do not exist in English; 'Having not' is rare and less natural.",natural:"Not having enough money, many graduates continue to live with their parents."},
 {lvl:3,cefr:"C1",q:"___ by the government in 2015, the scheme has already helped thousands of families.",opts:["Introducing","Having introduced","Introduced","Being introducing"],a:2,why:"The scheme was introduced by the government (passive), so the past participle 'Introduced' is correct. 'Having introduced' is active and would mean the scheme introduced something.",natural:"Introduced by the government in 2015, the scheme has already helped thousands of families."},
 {lvl:3,cefr:"C1",q:"Which sentence avoids a dangling participle?",opts:["Having been rejected twice, the committee finally approved the proposal.","Having been rejected twice, the proposal was finally approved by the committee.","Rejecting twice, the proposal was finally approved.","Having rejected twice, the proposal was finally approved by the committee."],a:1,why:"The proposal was rejected, so it must be the subject of the main clause, and the passive perfect participle 'having been rejected' is needed. In the first option the committee seems to have been rejected; the active forms in the other options are also wrong.",natural:"Having been rejected twice, the proposal was finally approved by the committee."},
 {lvl:3,cefr:"C1",q:"___ from 2005 to 2020, the data reveal a clear upward trend in renewable energy use.",opts:["Collecting","Collected","Having collected","Being collecting"],a:1,why:"The data were collected (passive), so 'Collected' is correct. 'Collecting' and 'Having collected' are active and would mean the data collected something, a dangling participle.",natural:"Collected between 2005 and 2020, the data reveal a clear upward trend in the use of renewable energy."}
 ]}
];
