// Original paraphrasing exercises for IELTS Mastery (kind: paraphrase). See content/CONTENT_SPEC.md section 6.
export const PARAPHRASE = [
 // ---------- SYNONYM SUBSTITUTION (PP-001 .. PP-030) ----------
 {id:"PP-001", type:"synonym", band:5.5, original:"The museum attracts around 2,000 visitors every week.",
  task:"choose", q:"Which sentence has the SAME meaning?",
  opts:["Roughly 2,000 people visit the museum each week.","Exactly 2,000 people visit the museum each week.","Around 2,000 people visited the museum last week.","More than 2,000 people visit the museum each week."], a:0,
  model:"Roughly 2,000 people visit the museum each week.",
  why:"Synonyms: around = roughly, every = each, attracts visitors = people visit. 'Exactly' and 'more than' change the approximate quantity; 'last week' turns a regular pattern into one past week."},
 {id:"PP-002", type:"synonym", band:6, original:"The council plans to reduce traffic in the city centre.",
  task:"complete", q:"The council intends to ___ traffic in the city centre.", a:["cut","lower","decrease","bring down"],
  model:"The council intends to cut traffic in the city centre.",
  why:"Synonym substitution: plans = intends, reduce = cut / lower / decrease / bring down. 'Increase' or 'stop' would change the meaning."},
 {id:"PP-003", type:"synonym", band:6.5, original:"Researchers found that the new crop variety requires considerably less water.",
  task:"choose", q:"Which sentence has the SAME meaning?",
  opts:["Scientists discovered that the new type of crop needs slightly less water.","Scientists hope that the new type of crop will need significantly less water.","Scientists discovered that the new type of crop needs significantly less water.","Scientists discovered that giving less water helps the new type of crop grow."], a:2,
  model:"Scientists discovered that the new type of crop needs significantly less water.",
  why:"Synonyms: found = discovered, variety = type, requires = needs, considerably = significantly. 'Slightly' weakens the amount; 'hope ... will' turns a finding into a wish about the future; the last option reverses the relationship (less water causes growth)."},
 {id:"PP-004", type:"synonym", band:7, original:"The decline in bee populations is a major concern for farmers.",
  task:"complete", q:"Farmers are seriously ___ about the falling number of bees.", a:["worried","concerned","anxious","troubled"],
  model:"Farmers are seriously worried about the falling number of bees.",
  why:"Synonym and word-class change: a major concern = seriously worried / concerned; decline = falling number; populations = number of bees."},
 {id:"PP-005", type:"synonym", band:7.5, original:"The documents were virtually impossible to decipher because the ink had faded.",
  task:"choose", q:"Which sentence has the SAME meaning?",
  opts:["Because the ink had faded, the papers could hardly be read at all.","Because the ink had faded, the papers were completely impossible to read.","The ink faded because the papers were hard to read.","Although the ink had faded, the papers could easily be read."], a:0,
  model:"Because the ink had faded, the papers could hardly be read at all.",
  why:"Synonyms: virtually impossible = could hardly, decipher = read, documents = papers. 'Completely impossible' is stronger than 'virtually'; the third option reverses cause and effect; the fourth contradicts the original."},
 {id:"PP-006", type:"synonym", band:5.5, original:"Students must hand in their essays before Friday.",
  task:"complete", q:"Students have to ___ their essays before Friday.", a:["submit","turn in","give in"],
  model:"Students have to submit their essays before Friday.",
  why:"Synonyms: must = have to, hand in = submit / turn in. This is a common Listening note-taking paraphrase."},
 {id:"PP-007", type:"synonym", band:6, original:"The library is closed temporarily for repairs.",
  task:"choose", q:"Which sentence has the SAME meaning?",
  opts:["The library has shut permanently because of repairs.","The library is shut for a short time while it is being repaired.","The library will close soon for repairs.","The library is closed because repairs have finished."], a:1,
  model:"The library is shut for a short time while it is being repaired.",
  why:"Synonyms: temporarily = for a short time, closed = shut, for repairs = while it is being repaired. 'Permanently' is the opposite; 'will close soon' changes the time; the last option says the repairs are over."},
 {id:"PP-008", type:"synonym", band:6.5, original:"Online shopping has become increasingly popular among older consumers.",
  task:"complete", q:"Internet shopping is ___ popular with elderly customers than before.", a:["more","much more","far more"],
  model:"Internet shopping is more popular with elderly customers than before.",
  why:"Synonyms: online = internet, older consumers = elderly customers. 'Increasingly popular' is reformulated as a comparison with the past: more popular than before."},
 {id:"PP-009", type:"synonym", band:7, original:"The study revealed a strong link between sleep quality and exam performance.",
  task:"choose", q:"Which sentence has the SAME meaning?",
  opts:["The research proved that poor sleep causes bad exam results.","The research showed a weak connection between sleep and exam results.","The research showed a close connection between how well people sleep and how they do in exams.","The research showed that exam results affect how well students sleep."], a:2,
  model:"The research showed a close connection between how well people sleep and how they do in exams.",
  why:"Synonyms: revealed = showed, strong link = close connection, exam performance = how they do in exams. 'Proved ... causes' adds certainty and causation that a 'link' does not state; 'weak' changes the qualifier; the last option reverses the direction."},
 {id:"PP-010", type:"synonym", band:7.5, original:"The town's economy relied heavily on the textile industry until the 1970s.",
  task:"complete", q:"Up to the 1970s, the town's economy was highly ___ on textile manufacturing.", a:["dependent","reliant"],
  model:"Up to the 1970s, the town's economy was highly dependent on textile manufacturing.",
  why:"Synonym plus word-class change: relied heavily on = was highly dependent / reliant on; until = up to; industry = manufacturing."},
 {id:"PP-011", type:"synonym", band:5.5, original:"The tour lasts approximately two hours.",
  task:"choose", q:"Which sentence has the SAME meaning?",
  opts:["The tour takes at least two hours.","The tour takes about two hours.","The tour takes exactly two hours.","The tour took two hours yesterday."], a:1,
  model:"The tour takes about two hours.",
  why:"Synonyms: lasts = takes, approximately = about. 'At least' and 'exactly' change the quantity; 'yesterday' refers to one past occasion, not a general fact."},
 {id:"PP-012", type:"synonym", band:6, original:"Many residents oppose the plan to build a new airport.",
  task:"complete", q:"A lot of local people are ___ the proposal for a new airport.", a:["against","opposed to","not in favour of"],
  model:"A lot of local people are against the proposal for a new airport.",
  why:"Synonyms: many = a lot of, residents = local people, oppose = are against / are opposed to, plan = proposal."},
 {id:"PP-013", type:"synonym", band:6.5, original:"The bridge was designed to withstand severe earthquakes.",
  task:"choose", q:"Which sentence has the SAME meaning?",
  opts:["The bridge was built to survive powerful earthquakes.","The bridge was damaged by powerful earthquakes.","The bridge was built to survive minor earthquakes.","The bridge has survived every earthquake so far."], a:0,
  model:"The bridge was built to survive powerful earthquakes.",
  why:"Synonyms: designed = built (with a purpose), withstand = survive, severe = powerful. 'Damaged' contradicts the purpose; 'minor' weakens the qualifier; the last option states a past record rather than a design purpose."},
 {id:"PP-014", type:"synonym", band:7, original:"The government has pledged to eliminate child poverty by 2035.",
  task:"complete", q:"The government has promised to ___ child poverty by 2035.", a:["end","eradicate","get rid of","abolish"],
  model:"The government has promised to end child poverty by 2035.",
  why:"Synonyms: pledged = promised, eliminate = end / eradicate / get rid of. 'Reduce' would be a weaker claim and change the meaning."},
 {id:"PP-015", type:"synonym", band:7.5, original:"Early settlers in the valley were largely self-sufficient.",
  task:"choose", q:"Which sentence has the SAME meaning?",
  opts:["The first people to live in the valley depended entirely on trade.","The first people to live in the valley produced almost everything they needed themselves.","The first people to live in the valley produced everything they needed without exception.","Later settlers in the valley were mostly self-sufficient."], a:1,
  model:"The first people to live in the valley produced almost everything they needed themselves.",
  why:"Synonyms: early settlers = the first people to live, largely = almost / mostly, self-sufficient = produced what they needed themselves. 'Depended on trade' is the opposite; 'without exception' removes the qualifier 'largely'; 'later settlers' changes the time."},
 {id:"PP-016", type:"synonym", band:5.5, original:"The course is suitable for complete beginners.",
  task:"complete", q:"The course is ___ for people with no previous experience.", a:["appropriate","right","ideal","designed"],
  model:"The course is appropriate for people with no previous experience.",
  why:"Synonyms: suitable = appropriate / right; complete beginners = people with no previous experience."},
 {id:"PP-017", type:"synonym", band:6, original:"Prices rose steadily throughout the decade.",
  task:"choose", q:"Which sentence has the SAME meaning?",
  opts:["Prices rose suddenly at the end of the decade.","Prices increased gradually over the ten years.","Prices fell gradually over the ten years.","Prices rose and fell during the ten years."], a:1,
  model:"Prices increased gradually over the ten years.",
  why:"Synonyms (Writing Task 1 language): rose = increased, steadily = gradually, throughout the decade = over the ten years. 'Suddenly at the end' changes manner and time; 'fell' reverses the trend; 'rose and fell' describes fluctuation."},
 {id:"PP-018", type:"synonym", band:6.5, original:"The festival provides a vital source of income for local businesses.",
  task:"complete", q:"Local firms ___ heavily on the money the festival brings in.", a:["depend","rely"],
  model:"Local firms depend heavily on the money the festival brings in.",
  why:"Synonyms and perspective shift: a vital source of income = depend / rely heavily on the money; businesses = firms. The subject changes from the festival to the businesses."},
 {id:"PP-019", type:"synonym", band:7, original:"The professor's theory was initially dismissed by most of her colleagues.",
  task:"choose", q:"Which sentence has the SAME meaning?",
  opts:["At first, the majority of her fellow academics rejected the professor's theory.","At first, all of her fellow academics rejected the professor's theory.","Most of her fellow academics still reject the professor's theory.","At first, the majority of her fellow academics welcomed the professor's theory."], a:0,
  model:"At first, the majority of her fellow academics rejected the professor's theory.",
  why:"Synonyms: initially = at first, dismissed = rejected, most = the majority, colleagues = fellow academics. 'All' changes the quantity; 'still' changes the time (the original implies opinion changed); 'welcomed' is the opposite."},
 {id:"PP-020", type:"synonym", band:7.5, original:"The policy had a negligible impact on unemployment.",
  task:"complete", q:"The policy made ___ difference to the number of people out of work.", a:["almost no","hardly any","very little","virtually no"],
  model:"The policy made hardly any difference to the number of people out of work.",
  why:"Synonyms: negligible impact = hardly any / very little difference; unemployment = the number of people out of work. 'No difference' alone would be slightly too absolute."},
 {id:"PP-021", type:"synonym", band:5.5, original:"Parking is free for hotel guests.",
  task:"choose", q:"Which sentence has the SAME meaning?",
  opts:["Hotel guests can park at a reduced price.","Hotel guests do not have to pay for parking.","Only some hotel guests can park for free.","Hotel guests must pay for parking."], a:1,
  model:"Hotel guests do not have to pay for parking.",
  why:"Synonym by explanation: free = do not have to pay. 'Reduced price' still means paying; 'only some' adds a restriction; 'must pay' is the opposite."},
 {id:"PP-022", type:"synonym", band:6, original:"The company employs roughly 300 staff.",
  task:"complete", q:"The company has a workforce of ___ 300 people.", a:["about","around","approximately","some"],
  model:"The company has a workforce of about 300 people.",
  why:"Synonyms: employs ... staff = has a workforce of ... people; roughly = about / around / approximately."},
 {id:"PP-023", type:"synonym", band:6.5, original:"Fewer young people are choosing to study languages at university.",
  task:"choose", q:"Which sentence has the SAME meaning?",
  opts:["No young people now choose to study languages at university.","The number of students opting for language degrees is falling.","The number of students opting for language degrees is rising.","Young people who study languages find fewer jobs after university."], a:1,
  model:"The number of students opting for language degrees is falling.",
  why:"Synonyms: fewer = the number ... is falling, choosing = opting for, study languages at university = language degrees. 'No young people' exaggerates; 'rising' reverses the trend; the last option introduces an unrelated claim about jobs."},
 {id:"PP-024", type:"synonym", band:7, original:"The new regulations are expected to come into force next spring.",
  task:"complete", q:"The new rules should ___ next spring.", a:["take effect","become law","be introduced","start to apply"],
  model:"The new rules should take effect next spring.",
  why:"Synonyms: regulations = rules, are expected to = should, come into force = take effect / be introduced."},
 {id:"PP-025", type:"synonym", band:7.5, original:"The artist's later works are markedly different from her early paintings.",
  task:"choose", q:"Which sentence has the SAME meaning?",
  opts:["The artist's early and late paintings are quite similar.","The artist's later works are slightly different from her early paintings.","There is a striking contrast between the artist's early and late paintings.","The artist's early paintings influenced her later works."], a:2,
  model:"There is a striking contrast between the artist's early and late paintings.",
  why:"Synonyms and structure change: markedly different = a striking contrast. 'Quite similar' contradicts; 'slightly' weakens the degree; 'influenced' adds a cause-and-effect claim not in the original."},
 {id:"PP-026", type:"synonym", band:5.5, original:"I usually go jogging in the park near my flat.",
  task:"complete", q:"I ___ go running in the park close to where I live.", a:["normally","generally","often","typically"],
  model:"I normally go running in the park close to where I live.",
  why:"Speaking paraphrase with synonyms: usually = normally / generally, jogging = running, near my flat = close to where I live. 'Always' or 'sometimes' would change the frequency."},
 {id:"PP-027", type:"synonym", band:6, original:"The scheme was abandoned owing to a lack of funding.",
  task:"choose", q:"Which sentence has the SAME meaning?",
  opts:["The project was dropped because there was not enough money.","The project was delayed because there was not enough money.","The project lost its money because it was dropped.","The project was dropped even though there was plenty of money."], a:0,
  model:"The project was dropped because there was not enough money.",
  why:"Synonyms: scheme = project, abandoned = dropped, owing to = because, a lack of funding = not enough money. 'Delayed' is weaker than 'abandoned'; the third option reverses cause and effect; the fourth contradicts the reason."},
 {id:"PP-028", type:"synonym", band:6.5, original:"The island's population has remained stable for the past fifty years.",
  task:"complete", q:"The number of people living on the island has hardly ___ in the last half-century.", a:["changed","altered","varied","fluctuated"],
  model:"The number of people living on the island has hardly changed in the last half-century.",
  why:"Synonym by negation: remained stable = has hardly changed; population = number of people living; the past fifty years = the last half-century."},
 {id:"PP-029", type:"synonym", band:7, original:"Archaeologists believe the site was occupied intermittently over several centuries.",
  task:"choose", q:"Which sentence has the SAME meaning?",
  opts:["Archaeologists have proved that people lived at the site continuously for centuries.","Archaeologists think people lived at the site on and off over a period of several hundred years.","Archaeologists think people lived at the site for only a few decades.","Archaeologists think the site was visited once, several centuries ago."], a:1,
  model:"Archaeologists think people lived at the site on and off over a period of several hundred years.",
  why:"Synonyms: believe = think, occupied = people lived, intermittently = on and off, several centuries = several hundred years. 'Proved' adds certainty and 'continuously' is the opposite of intermittently; 'a few decades' changes the period; 'visited once' changes frequency and time."},
 {id:"PP-030", type:"synonym", band:7.5, original:"The findings cast doubt on the conventional explanation of the collapse.",
  task:"complete", q:"The results ___ the traditional account of why the collapse happened.", a:["call into question","question","challenge","undermine"],
  model:"The results call into question the traditional account of why the collapse happened.",
  why:"Synonyms: findings = results, cast doubt on = call into question / challenge, conventional explanation = traditional account. 'Disprove' would be too strong."},

 // ---------- GRAMMATICAL TRANSFORMATION (PP-031 .. PP-055) ----------
 {id:"PP-031", type:"grammar", band:5.5, original:"The bus is cheaper than the train.",
  task:"choose", q:"Which sentence has the SAME meaning?",
  opts:["The train is cheaper than the bus.","The train is not as cheap as the bus.","The bus is as expensive as the train.","The train is not as expensive as the bus."], a:1,
  model:"The train is not as cheap as the bus.",
  why:"Grammar: comparative -> 'not as ... as' with the subjects swapped. Option 1 reverses the comparison; option 3 says they cost the same; option 4 makes the train cheaper."},
 {id:"PP-032", type:"grammar", band:6, original:"I started learning the piano five years ago.",
  task:"complete", q:"I ___ the piano for five years.", a:["have been learning","have learnt","have learned"],
  model:"I have been learning the piano for five years.",
  why:"Grammar: past simple + 'ago' -> present perfect (continuous) + 'for' to show an action that began in the past and continues now."},
 {id:"PP-033", type:"grammar", band:6.5, original:"If the city does not invest in public transport, congestion will get worse.",
  task:"choose", q:"Which sentence has the SAME meaning?",
  opts:["Unless the city invests in public transport, congestion will get worse.","Unless the city invests in public transport, congestion will improve.","If the city invests in public transport, congestion will get worse.","Congestion got worse because the city did not invest in public transport."], a:0,
  model:"Unless the city invests in public transport, congestion will get worse.",
  why:"Grammar: 'if ... not' = 'unless'. Option 2 reverses the result; option 3 removes the negative and so reverses the condition; option 4 turns a future condition into a past fact."},
 {id:"PP-034", type:"grammar", band:7, original:"The box was so heavy that nobody could lift it.",
  task:"complete", q:"The box was ___ for anyone to lift.", a:["too heavy","far too heavy","much too heavy"],
  model:"The box was too heavy for anyone to lift.",
  why:"Grammar: 'so + adjective + that ... could not' = 'too + adjective + for ... to'. Note the negative disappears because 'too' already carries it."},
 {id:"PP-035", type:"grammar", band:7.5, original:"As the population ages, the demand for healthcare increases.",
  task:"choose", q:"Which sentence has the SAME meaning?",
  opts:["The older the population becomes, the greater the demand for healthcare.","The older the population becomes, the smaller the demand for healthcare.","The greater the demand for healthcare, the older the population becomes.","The population is ageing because demand for healthcare is increasing."], a:0,
  model:"The older the population becomes, the greater the demand for healthcare.",
  why:"Grammar: proportional 'as ... , ...' -> 'the + comparative ..., the + comparative'. Option 2 reverses the effect; options 3 and 4 reverse cause and effect."},
 {id:"PP-036", type:"grammar", band:5.5, original:"It isn't necessary to book tickets in advance.",
  task:"complete", q:"You ___ book tickets in advance.", a:["don't have to","do not have to","don't need to","needn't"],
  model:"You don't have to book tickets in advance.",
  why:"Grammar: 'it isn't necessary to' = modal of no obligation 'don't have to / needn't'. Be careful: 'mustn't' means it is forbidden, which changes the meaning."},
 {id:"PP-037", type:"grammar", band:6, original:"I regret not taking a gap year before university.",
  task:"choose", q:"Which sentence has the SAME meaning?",
  opts:["I wish I had taken a gap year before university.","I'm glad I didn't take a gap year before university.","I wish I hadn't taken a gap year before university.","I am planning to take a gap year before university."], a:0,
  model:"I wish I had taken a gap year before university.",
  why:"Grammar: 'regret not doing' = 'wish + past perfect' (I wish I had done). Option 2 shows the opposite feeling; option 3 reverses what happened; option 4 changes the time to the future."},
 {id:"PP-038", type:"grammar", band:6.5, original:"This is the most ambitious project the company has ever undertaken.",
  task:"complete", q:"The company has ___ undertaken such an ambitious project.", a:["never","never before","not ever"],
  model:"The company has never undertaken such an ambitious project.",
  why:"Grammar: superlative + 'ever' -> negative 'never ... such a(n)'. Both say no previous project was as ambitious."},
 {id:"PP-039", type:"grammar", band:7, original:"There used to be a cinema on the corner of the high street.",
  task:"choose", q:"Which sentence has the SAME meaning?",
  opts:["There is still a cinema on the corner of the high street.","In the past there was a cinema on the corner of the high street, but there isn't now.","A cinema will be built on the corner of the high street.","People often used the cinema on the corner of the high street."], a:1,
  model:"In the past there was a cinema on the corner of the high street, but there isn't now.",
  why:"Grammar: 'used to' = a past state that no longer exists (useful for Writing Task 1 maps). 'Still' contradicts the change; 'will be built' changes the time; the last option confuses 'used to' with the verb 'use'."},
 {id:"PP-040", type:"grammar", band:7.5, original:"We didn't leave early, so we missed the last ferry.",
  task:"complete", q:"If we ___ early, we wouldn't have missed the last ferry.", a:["had left","had set off"],
  model:"If we had left early, we wouldn't have missed the last ferry.",
  why:"Grammar: past facts -> third conditional (if + past perfect, would have + past participle). The negative fact 'didn't leave' becomes the positive hypothetical 'had left'."},
 {id:"PP-041", type:"grammar", band:5.5, original:"The hall is not big enough for 500 people.",
  task:"choose", q:"Which sentence has the SAME meaning?",
  opts:["The hall is too big for 500 people.","The hall is too small for 500 people.","The hall is big enough for 500 people.","The hall was too small for 500 people last year."], a:1,
  model:"The hall is too small for 500 people.",
  why:"Grammar: 'not + adjective + enough' = 'too + opposite adjective'. Option 1 uses the wrong adjective; option 3 removes the negative; option 4 changes the time."},
 {id:"PP-042", type:"grammar", band:6, original:"It's possible that the meeting will be cancelled.",
  task:"complete", q:"The meeting ___ cancelled.", a:["might be","may be","could be"],
  model:"The meeting might be cancelled.",
  why:"Grammar: 'it's possible that ... will' = modal of possibility 'might / may / could' + passive infinitive. 'Will be' or 'must be' would make it too certain."},
 {id:"PP-043", type:"grammar", band:6.5, original:"The volunteers not only planted trees but also cleaned the river banks.",
  task:"choose", q:"Which sentence has the SAME meaning?",
  opts:["The volunteers planted trees instead of cleaning the river banks.","As well as planting trees, the volunteers cleaned the river banks.","The volunteers cleaned the river banks before they planted trees.","The volunteers planted trees so that the river banks would be clean."], a:1,
  model:"As well as planting trees, the volunteers cleaned the river banks.",
  why:"Grammar: 'not only ... but also' = 'as well as + -ing'. 'Instead of' says only one task was done; 'before' adds a time order not in the original; 'so that' invents a purpose."},
 {id:"PP-044", type:"grammar", band:7, original:"The scheme was such a success that it was extended to other regions.",
  task:"complete", q:"The scheme was ___ that it was extended to other regions.", a:["so successful"],
  model:"The scheme was so successful that it was extended to other regions.",
  why:"Grammar: 'such a + noun' -> 'so + adjective'. The noun 'success' becomes the adjective 'successful'."},
 {id:"PP-045", type:"grammar", band:7.5, original:"No other city in the region has grown as quickly as Marlow Bay.",
  task:"choose", q:"Which sentence has the SAME meaning?",
  opts:["Marlow Bay has grown more slowly than other cities in the region.","Marlow Bay has grown faster than any other city in the region.","Marlow Bay has grown as quickly as some other cities in the region.","Marlow Bay will soon be the fastest-growing city in the region."], a:1,
  model:"Marlow Bay has grown faster than any other city in the region.",
  why:"Grammar: 'no other ... as ... as' = comparative + 'than any other'. Option 1 reverses the comparison; option 3 says it is equal, not the fastest; option 4 changes the time to the future."},
 {id:"PP-046", type:"grammar", band:5.5, original:"My brother is a better cook than me.",
  task:"complete", q:"I can't cook as ___ my brother.", a:["well as"],
  model:"I can't cook as well as my brother.",
  why:"Grammar: comparative adjective (a better cook) -> 'not as + adverb + as' (can't cook as well as)."},
 {id:"PP-047", type:"grammar", band:6, original:"The last time I visited the coast was in 2019.",
  task:"choose", q:"Which sentence has the SAME meaning?",
  opts:["I first visited the coast in 2019.","I haven't visited the coast since 2019.","I have visited the coast every year since 2019.","I visited the coast for the whole of 2019."], a:1,
  model:"I haven't visited the coast since 2019.",
  why:"Grammar: 'the last time ... was' = present perfect negative + 'since'. 'First visited' confuses last with first; 'every year since' is the opposite; 'for the whole of 2019' changes the duration."},
 {id:"PP-048", type:"grammar", band:6.5, original:"It was wrong of the company to ignore the safety warnings.",
  task:"complete", q:"The company ___ ignored the safety warnings.", a:["shouldn't have","should not have","ought not to have"],
  model:"The company shouldn't have ignored the safety warnings.",
  why:"Grammar: criticism of a past action 'it was wrong to' = 'should not have + past participle'."},
 {id:"PP-049", type:"grammar", band:7, original:"You can borrow the equipment provided that you return it by Monday.",
  task:"choose", q:"Which sentence has the SAME meaning?",
  opts:["You can borrow the equipment as long as you bring it back by Monday.","You can borrow the equipment, but you can return it whenever you like.","You must borrow the equipment by Monday.","You can borrow the equipment only after Monday."], a:0,
  model:"You can borrow the equipment as long as you bring it back by Monday.",
  why:"Grammar: 'provided that' = 'as long as' (a condition). Option 2 removes the condition; option 3 moves the deadline to the borrowing; option 4 changes the time."},
 {id:"PP-050", type:"grammar", band:7.5, original:"It's a long time since anyone repaired this wall.",
  task:"complete", q:"This wall ___ for a long time.", a:["hasn't been repaired","has not been repaired"],
  model:"This wall hasn't been repaired for a long time.",
  why:"Grammar: 'it's a long time since + past' = present perfect negative + 'for'. Here the passive is needed because the wall becomes the subject."},
 {id:"PP-051", type:"grammar", band:5.5, original:"It took me three hours to finish the report.",
  task:"choose", q:"Which sentence has the SAME meaning?",
  opts:["I spent three hours finishing the report.","I finished the report three hours ago.","I spent less than three hours on the report.","I will need three hours to finish the report."], a:0,
  model:"I spent three hours finishing the report.",
  why:"Grammar: 'it took me + time + to do' = 'I spent + time + doing'. 'Three hours ago' changes duration into a point in time; 'less than' changes the quantity; 'will need' changes the time."},
 {id:"PP-052", type:"grammar", band:6, original:"Although she trained hard, she didn't qualify for the final.",
  task:"complete", q:"She trained hard, ___ she didn't qualify for the final.", a:["but","yet","but still"],
  model:"She trained hard, but she didn't qualify for the final.",
  why:"Grammar: subordinating 'although' -> coordinating 'but / yet'. Both express contrast between effort and result."},
 {id:"PP-053", type:"grammar", band:6.5, original:"I'd rather work from home than commute every day.",
  task:"choose", q:"Which sentence has the SAME meaning?",
  opts:["I prefer working from home to commuting every day.","I prefer commuting every day to working from home.","I have to work from home instead of commuting.","I used to work from home rather than commute."], a:0,
  model:"I prefer working from home to commuting every day.",
  why:"Grammar: 'would rather X than Y' = 'prefer X-ing to Y-ing'. Option 2 reverses the preference; option 3 turns preference into obligation; option 4 changes the time to the past."},
 {id:"PP-054", type:"grammar", band:7, original:"People say that the castle is haunted.",
  task:"complete", q:"The castle is said ___ haunted.", a:["to be"],
  model:"The castle is said to be haunted.",
  why:"Grammar: impersonal 'people say that ...' -> 'subject + is said + to-infinitive', a common academic reporting structure."},
 {id:"PP-055", type:"grammar", band:7.5, original:"The experiment failed because the samples had been contaminated.",
  task:"choose", q:"Which sentence has the SAME meaning?",
  opts:["Had the samples not been contaminated, the experiment would not have failed.","If the samples are not contaminated, the experiment will not fail.","Had the samples been contaminated, the experiment would have failed.","The samples were contaminated because the experiment had failed."], a:0,
  model:"Had the samples not been contaminated, the experiment would not have failed.",
  why:"Grammar: past cause -> inverted third conditional ('Had ... not been' = 'If ... had not been'). Option 2 changes to a future condition; option 3 imagines the opposite situation to what happened; option 4 reverses cause and effect."},

 // ---------- ACTIVE-PASSIVE (PP-056 .. PP-075) ----------
 {id:"PP-056", type:"active-passive", band:5.5, original:"The school offers free lunches to all pupils.",
  task:"complete", q:"Free lunches ___ to all pupils by the school.", a:["are offered","are provided","are given"],
  model:"Free lunches are offered to all pupils by the school.",
  why:"Active -> passive in the present simple: am/is/are + past participle. The object 'free lunches' becomes the subject."},
 {id:"PP-057", type:"active-passive", band:6, original:"A local architect designed the new library.",
  task:"choose", q:"Which sentence has the SAME meaning?",
  opts:["The new library was designed by a local architect.","The new library is being designed by a local architect.","A local architect was designed by the new library.","The new library will be designed by a local architect."], a:0,
  model:"The new library was designed by a local architect.",
  why:"Active -> passive in the past simple: was/were + past participle. Option 2 and 4 change the tense (in progress / future); option 3 swaps the roles of agent and object."},
 {id:"PP-058", type:"active-passive", band:6.5, original:"The city council is currently renovating the town hall.",
  task:"complete", q:"The town hall ___ by the city council at the moment.", a:["is being renovated","is being restored","is being refurbished"],
  model:"The town hall is being renovated by the city council at the moment.",
  why:"Active -> passive in the present continuous: is/are being + past participle. 'Currently' = 'at the moment'."},
 {id:"PP-059", type:"active-passive", band:7, original:"Researchers have identified three new species in the rainforest.",
  task:"choose", q:"Which sentence has the SAME meaning?",
  opts:["Three new species had been identified in the rainforest before the research began.","Three new species have been identified in the rainforest by researchers.","Three new species will be identified in the rainforest by researchers.","Three new species have identified researchers in the rainforest."], a:1,
  model:"Three new species have been identified in the rainforest by researchers.",
  why:"Active -> passive in the present perfect: have/has been + past participle. Option 1 changes the time order (before the research); option 3 is future; option 4 reverses the roles."},
 {id:"PP-060", type:"active-passive", band:7.5, original:"Engineers will have completed the tunnel by the end of next year.",
  task:"complete", q:"The tunnel ___ by the end of next year.", a:["will have been completed","will have been finished"],
  model:"The tunnel will have been completed by the end of next year.",
  why:"Active -> passive in the future perfect: will have been + past participle. The agent (engineers) is obvious, so it is omitted."},
 {id:"PP-061", type:"active-passive", band:5.5, original:"The tour guide will meet visitors at the main entrance.",
  task:"choose", q:"Which sentence has the SAME meaning?",
  opts:["Visitors will be met at the main entrance by the tour guide.","Visitors were met at the main entrance by the tour guide.","Visitors will meet at the main entrance without the tour guide.","The tour guide will be met by visitors at the side entrance."], a:0,
  model:"Visitors will be met at the main entrance by the tour guide.",
  why:"Active -> passive in the future: will be + past participle (a typical Listening note). Option 2 is past; option 3 removes the guide; option 4 changes the place."},
 {id:"PP-062", type:"active-passive", band:6, original:"Farmers grow most of the region's coffee on small plots.",
  task:"complete", q:"Most of the region's coffee ___ on small plots.", a:["is grown","is produced","is cultivated"],
  model:"Most of the region's coffee is grown on small plots.",
  why:"Active -> passive in the present simple, typical of Writing Task 1 process descriptions. 'Coffee' is uncountable, so the verb is singular: is grown."},
 {id:"PP-063", type:"active-passive", band:6.5, original:"The committee rejected the proposal after a long debate.",
  task:"choose", q:"Which sentence has the SAME meaning?",
  opts:["The proposal was accepted by the committee after a long debate.","After a long debate, the proposal was turned down by the committee.","The proposal led to the committee being rejected after a long debate.","The proposal was rejected by the committee before any debate."], a:1,
  model:"After a long debate, the proposal was turned down by the committee.",
  why:"Active -> passive plus synonym (rejected = turned down) and clause movement. 'Accepted' is the opposite; option 3 reverses the roles; 'before any debate' changes the time."},
 {id:"PP-064", type:"active-passive", band:7, original:"Someone had stolen the painting before the alarm went off.",
  task:"complete", q:"The painting ___ before the alarm went off.", a:["had been stolen","had already been stolen"],
  model:"The painting had been stolen before the alarm went off.",
  why:"Active -> passive in the past perfect: had been + past participle. With an unknown agent ('someone'), the 'by' phrase is dropped."},
 {id:"PP-065", type:"active-passive", band:7.5, original:"The authorities must address the housing shortage urgently.",
  task:"choose", q:"Which sentence has the SAME meaning?",
  opts:["The housing shortage might be addressed by the authorities eventually.","The housing shortage must be addressed urgently by the authorities.","The housing shortage has been addressed urgently by the authorities.","The authorities caused the housing shortage."], a:1,
  model:"The housing shortage must be addressed urgently by the authorities.",
  why:"Passive with a modal: must be + past participle. 'Might ... eventually' weakens both obligation and urgency; 'has been addressed' says it is already done; the last option invents a cause."},
 {id:"PP-066", type:"active-passive", band:5.5, original:"They clean the rooms every morning.",
  task:"complete", q:"The rooms ___ every morning.", a:["are cleaned","get cleaned"],
  model:"The rooms are cleaned every morning.",
  why:"Active -> passive in the present simple. 'They' is a vague agent, so it is left out."},
 {id:"PP-067", type:"active-passive", band:6, original:"The government introduced the tax in 1998.",
  task:"choose", q:"Which sentence has the SAME meaning?",
  opts:["The tax was introduced by the government in 1998.","The tax was abolished by the government in 1998.","The tax has been introduced by the government since 1998.","The government was introduced by the tax in 1998."], a:0,
  model:"The tax was introduced by the government in 1998.",
  why:"Active -> passive, past simple. 'Abolished' is the opposite action; 'has been ... since' confuses a single past event with a continuing period; the last option swaps the roles."},
 {id:"PP-068", type:"active-passive", band:6.5, original:"The organisers are going to announce the winners on Saturday.",
  task:"complete", q:"The winners are going to ___ on Saturday.", a:["be announced","be revealed","be made public"],
  model:"The winners are going to be announced on Saturday.",
  why:"Active -> passive with 'be going to': are going to + be + past participle. The organisers are omitted because the agent is obvious."},
 {id:"PP-069", type:"active-passive", band:7, original:"Critics have widely praised the director's latest film.",
  task:"choose", q:"Which sentence has the SAME meaning?",
  opts:["The director's latest film has been widely praised by critics.","The director's latest film has been praised by a few critics.","The director's latest film has been widely criticised.","The director has widely praised the critics' latest film."], a:0,
  model:"The director's latest film has been widely praised by critics.",
  why:"Active -> passive in the present perfect, keeping the adverb 'widely'. 'A few critics' changes the quantity; 'criticised' reverses the opinion; the last option reverses the roles."},
 {id:"PP-070", type:"active-passive", band:7.5, original:"Scientists believe that the comet last passed Earth 4,000 years ago.",
  task:"complete", q:"The comet ___ to have last passed Earth 4,000 years ago.", a:["is believed","is thought"],
  model:"The comet is believed to have last passed Earth 4,000 years ago.",
  why:"Impersonal passive: 'scientists believe that + past' = 'subject + is believed + to have + past participle'. The perfect infinitive keeps the past time."},
 {id:"PP-071", type:"active-passive", band:5.5, original:"Over two million tourists visit the gardens each year.",
  task:"choose", q:"Which sentence has the SAME meaning?",
  opts:["The gardens are visited by over two million tourists each year.","The gardens are visited by about one million tourists each year.","The gardens were visited by two million tourists in one year.","The gardens visit over two million tourists each year."], a:0,
  model:"The gardens are visited by over two million tourists each year.",
  why:"Active -> passive in the present simple. 'About one million' changes the number; 'were visited ... in one year' changes the time; the last option keeps the active verb with the wrong subject."},
 {id:"PP-072", type:"active-passive", band:6, original:"You can download the application form from the website.",
  task:"complete", q:"The application form ___ from the website.", a:["can be downloaded","may be downloaded"],
  model:"The application form can be downloaded from the website.",
  why:"Passive with a modal: can be + past participle. A typical Listening and notice paraphrase."},
 {id:"PP-073", type:"active-passive", band:6.5, original:"Heavy rain delayed the start of the match.",
  task:"choose", q:"Which sentence has the SAME meaning?",
  opts:["The start of the match was delayed by heavy rain.","The start of the match was cancelled because of heavy rain.","Heavy rain started after the match was delayed.","The start of the match was delayed in spite of heavy rain."], a:0,
  model:"The start of the match was delayed by heavy rain.",
  why:"Active -> passive with a non-human agent. 'Cancelled' is stronger than 'delayed'; option 3 reverses cause and effect; 'in spite of' contradicts the cause."},
 {id:"PP-074", type:"active-passive", band:7, original:"The company should have tested the product more thoroughly.",
  task:"complete", q:"The product should ___ more thoroughly.", a:["have been tested","have been checked"],
  model:"The product should have been tested more thoroughly.",
  why:"Passive with a past modal: should have been + past participle. It keeps the criticism of a past action."},
 {id:"PP-075", type:"active-passive", band:7.5, original:"It is widely reported that the merger created 500 jobs.",
  task:"choose", q:"Which sentence has the SAME meaning?",
  opts:["The merger is widely reported to create 500 jobs in the future.","The merger is widely reported to have created 500 jobs.","The merger is widely reported to have cost 500 jobs.","The merger has been proved to have created 500 jobs."], a:1,
  model:"The merger is widely reported to have created 500 jobs.",
  why:"Impersonal passive 'it is reported that + past' -> personal passive 'subject + is reported + to have + past participle'. 'In the future' changes the time; 'cost' reverses the effect; 'proved' adds certainty that a report does not give."},

 // ---------- NOUN-VERB TRANSFORMATION (PP-076 .. PP-100) ----------
 {id:"PP-076", type:"noun-verb", band:5.5, original:"We decided to move to the countryside.",
  task:"complete", q:"We ___ to move to the countryside.", a:["made a decision","took a decision","made the decision"],
  model:"We made a decision to move to the countryside.",
  why:"Noun-verb transformation: the verb 'decide' becomes the noun phrase 'make / take a decision'."},
 {id:"PP-077", type:"noun-verb", band:6, original:"The number of cyclists increased sharply between 2015 and 2020.",
  task:"choose", q:"Which sentence has the SAME meaning?",
  opts:["There was a slight increase in the number of cyclists between 2015 and 2020.","There was a sharp increase in the number of cyclists between 2015 and 2020.","There was a sharp decrease in the number of cyclists between 2015 and 2020.","There will be a sharp increase in the number of cyclists after 2020."], a:1,
  model:"There was a sharp increase in the number of cyclists between 2015 and 2020.",
  why:"Noun-verb transformation (Writing Task 1): verb + adverb 'increased sharply' -> 'there was a sharp increase in'. 'Slight' changes the degree; 'decrease' reverses the trend; 'there will be ... after 2020' changes the time."},
 {id:"PP-078", type:"noun-verb", band:6.5, original:"Sales fell dramatically in the final quarter.",
  task:"complete", q:"There was a ___ in sales in the final quarter.", a:["dramatic fall","dramatic drop","dramatic decline","dramatic decrease"],
  model:"There was a dramatic fall in sales in the final quarter.",
  why:"Noun-verb transformation: verb + adverb (fell dramatically) -> adjective + noun (a dramatic fall). The adverb must become an adjective."},
 {id:"PP-079", type:"noun-verb", band:7, original:"The government failed to respond quickly to the crisis.",
  task:"choose", q:"Which sentence has the SAME meaning?",
  opts:["The government's response to the crisis was slow.","The government's quick response ended the crisis.","The crisis was caused by the government's slow response.","The government's response to the crisis was quick but ineffective."], a:0,
  model:"The government's response to the crisis was slow.",
  why:"Noun-verb transformation: 'failed to respond quickly' -> 'the government's response ... was slow'. The second option reverses the speed and adds a result; the third reverses cause and effect; the fourth contradicts 'failed to respond quickly'."},
 {id:"PP-080", type:"noun-verb", band:7.5, original:"The region's economy has expanded rapidly since the port was built.",
  task:"complete", q:"The region has experienced ___ since the construction of the port.", a:["rapid economic expansion","rapid economic growth","rapid expansion","rapid growth"],
  model:"The region has experienced rapid economic expansion since the construction of the port.",
  why:"Double noun-verb transformation: 'economy has expanded rapidly' -> 'rapid economic expansion'; 'the port was built' -> 'the construction of the port'."},
 {id:"PP-081", type:"noun-verb", band:5.5, original:"The doctor advised me to rest for a week.",
  task:"choose", q:"Which sentence has the SAME meaning?",
  opts:["The doctor ordered me to rest for a month.","The doctor gave me advice to rest for a week.","I advised the doctor to rest for a week.","The doctor will advise me to rest for a week."], a:1,
  model:"The doctor gave me advice to rest for a week.",
  why:"Noun-verb transformation: 'advise' -> 'give advice'. 'Ordered' is stronger and 'a month' changes the time; the third option swaps the roles; 'will advise' changes the tense."},
 {id:"PP-082", type:"noun-verb", band:6, original:"The council will discuss the parking problem on Thursday.",
  task:"complete", q:"The council will have a ___ about the parking problem on Thursday.", a:["discussion","meeting","debate"],
  model:"The council will have a discussion about the parking problem on Thursday.",
  why:"Noun-verb transformation: 'discuss' -> 'have a discussion about'. Notice that 'discuss' takes no preposition but 'discussion' needs 'about'."},
 {id:"PP-083", type:"noun-verb", band:6.5, original:"Unemployment rose slightly in the first half of the year.",
  task:"choose", q:"Which sentence has the SAME meaning?",
  opts:["There was a significant rise in unemployment in the first half of the year.","There was a slight rise in unemployment in the second half of the year.","There was a slight fall in unemployment in the first half of the year.","The first half of the year saw a slight rise in unemployment."], a:3,
  model:"The first half of the year saw a slight rise in unemployment.",
  why:"Noun-verb transformation with a time-period subject: 'rose slightly' -> 'saw a slight rise in'. 'Significant' changes the degree; 'second half' changes the time; 'fall' reverses the trend."},
 {id:"PP-084", type:"noun-verb", band:7, original:"Residents strongly objected to the construction of the wind farm.",
  task:"complete", q:"There was strong ___ to the construction of the wind farm from residents.", a:["opposition","objection","resistance"],
  model:"There was strong opposition to the construction of the wind farm from residents.",
  why:"Noun-verb transformation: 'strongly objected to' -> 'there was strong opposition / objection to'. The adverb 'strongly' becomes the adjective 'strong'."},
 {id:"PP-085", type:"noun-verb", band:7.5, original:"Researchers analysed the data carefully before they published their conclusions.",
  task:"choose", q:"Which sentence has the SAME meaning?",
  opts:["Publication of the conclusions came before a careful analysis of the data.","A careful analysis of the data preceded the publication of the conclusions.","A brief analysis of the data preceded the publication of the conclusions.","The conclusions were published without any analysis of the data."], a:1,
  model:"A careful analysis of the data preceded the publication of the conclusions.",
  why:"Noun-verb transformation (nominalisation): 'analysed ... carefully' -> 'a careful analysis'; 'published' -> 'the publication'; 'before' -> 'preceded'. The first option reverses the order of events; 'brief' changes the qualifier; the last option contradicts the original."},
 {id:"PP-086", type:"noun-verb", band:5.5, original:"I need to choose between two job offers.",
  task:"complete", q:"I need to ___ between two job offers.", a:["make a choice","make a decision"],
  model:"I need to make a choice between two job offers.",
  why:"Noun-verb transformation: 'choose' -> 'make a choice'."},
 {id:"PP-087", type:"noun-verb", band:6, original:"The price of oil fluctuated wildly during the period.",
  task:"choose", q:"Which sentence has the SAME meaning?",
  opts:["The price of oil remained steady during the period.","There was a steady rise in the price of oil during the period.","There were wild fluctuations in the price of oil during the period.","There were minor fluctuations in the price of oil during the period."], a:2,
  model:"There were wild fluctuations in the price of oil during the period.",
  why:"Noun-verb transformation: 'fluctuated wildly' -> 'there were wild fluctuations in'. 'Remained steady' and 'a steady rise' describe different trends; 'minor' changes the degree."},
 {id:"PP-088", type:"noun-verb", band:6.5, original:"The airline has improved its customer service considerably.",
  task:"complete", q:"The airline has made considerable ___ to its customer service.", a:["improvements"],
  model:"The airline has made considerable improvements to its customer service.",
  why:"Noun-verb transformation: 'improved ... considerably' -> 'made considerable improvements to'. Use the plural noun after 'made considerable'."},
 {id:"PP-089", type:"noun-verb", band:7, original:"Many students fail to attend lectures regularly.",
  task:"choose", q:"Which sentence has the SAME meaning?",
  opts:["Lecture attendance is irregular among many students.","Lecture attendance is irregular among a few students.","Many students attend lectures regularly but fail their exams.","Lecture attendance has always been poor among all students."], a:0,
  model:"Lecture attendance is irregular among many students.",
  why:"Noun-verb transformation: 'fail to attend ... regularly' -> 'attendance is irregular'. 'A few' changes the quantity; the third option misreads 'fail' as failing exams; 'always' and 'all' exaggerate the time and quantity."},
 {id:"PP-090", type:"noun-verb", band:7.5, original:"The new drug significantly reduced the risk of infection.",
  task:"complete", q:"The new drug led to a ___ in the risk of infection.", a:["significant reduction","significant decrease","significant fall","significant drop"],
  model:"The new drug led to a significant reduction in the risk of infection.",
  why:"Noun-verb transformation with a cause-effect verb: 'significantly reduced' -> 'led to a significant reduction in'."},
 {id:"PP-091", type:"noun-verb", band:5.5, original:"The teacher explained the rules clearly.",
  task:"choose", q:"Which sentence has the SAME meaning?",
  opts:["The teacher gave a confusing explanation of the rules.","The teacher gave a clear explanation of the rules.","The teacher asked for a clear explanation of the rules.","The students gave a clear explanation of the rules."], a:1,
  model:"The teacher gave a clear explanation of the rules.",
  why:"Noun-verb transformation: 'explained ... clearly' -> 'gave a clear explanation of'. 'Confusing' is the opposite; 'asked for' reverses who explained; 'the students' changes the subject."},
 {id:"PP-092", type:"noun-verb", band:6, original:"Visitor numbers dropped steadily over the winter months.",
  task:"complete", q:"The winter months saw a ___ in visitor numbers.", a:["steady drop","steady fall","steady decline","steady decrease"],
  model:"The winter months saw a steady drop in visitor numbers.",
  why:"Noun-verb transformation with a time subject + 'saw': 'dropped steadily' -> 'saw a steady drop in'."},
 {id:"PP-093", type:"noun-verb", band:6.5, original:"The two companies have agreed to cooperate on the project.",
  task:"choose", q:"Which sentence has the SAME meaning?",
  opts:["The two companies have refused to cooperate on the project.","The two companies are considering cooperation on the project.","The two companies have reached an agreement to cooperate on the project.","One company has agreed to take over the other's project."], a:2,
  model:"The two companies have reached an agreement to cooperate on the project.",
  why:"Noun-verb transformation: 'agreed' -> 'reached an agreement'. 'Refused' is the opposite; 'considering' makes it uncertain; the last option changes the relationship completely."},
 {id:"PP-094", type:"noun-verb", band:7, original:"Several factors contributed to the collapse of the bank.",
  task:"complete", q:"Several factors made a ___ to the collapse of the bank.", a:["contribution"],
  model:"Several factors made a contribution to the collapse of the bank.",
  why:"Noun-verb transformation: 'contributed to' -> 'made a contribution to'. The preposition 'to' stays with both forms."},
 {id:"PP-095", type:"noun-verb", band:7.5, original:"Local people were not consulted before the factory was closed.",
  task:"choose", q:"Which sentence has the SAME meaning?",
  opts:["The closure of the factory took place without any consultation with local people.","The closure of the factory took place after a long consultation with local people.","Local people asked for the factory to be closed without consultation.","The factory will close once local people have been consulted."], a:0,
  model:"The closure of the factory took place without any consultation with local people.",
  why:"Nominalisation: 'was closed' -> 'the closure'; 'were not consulted' -> 'without any consultation'. The second option reverses the fact; the third makes local people responsible for the closure; the fourth changes the time."},
 {id:"PP-096", type:"noun-verb", band:5.5, original:"We arrived at the hotel late at night.",
  task:"complete", q:"Our ___ at the hotel was late at night.", a:["arrival"],
  model:"Our arrival at the hotel was late at night.",
  why:"Noun-verb transformation: 'we arrived' -> 'our arrival'. The subject pronoun becomes a possessive."},
 {id:"PP-097", type:"noun-verb", band:6, original:"The population of the town doubled between 1950 and 2000.",
  task:"choose", q:"Which sentence has the SAME meaning?",
  opts:["The town's population fell by half between 1950 and 2000.","There was a twofold increase in the town's population between 1950 and 2000.","There was a threefold increase in the town's population between 1950 and 2000.","The town's population will double between 2000 and 2050."], a:1,
  model:"There was a twofold increase in the town's population between 1950 and 2000.",
  why:"Noun-verb transformation: 'doubled' -> 'a twofold increase'. 'Fell by half' reverses the trend; 'threefold' changes the quantity; the last option changes the period."},
 {id:"PP-098", type:"noun-verb", band:6.5, original:"Scientists are investigating why the lake is shrinking.",
  task:"complete", q:"Scientists are carrying out an ___ into the shrinking of the lake.", a:["investigation","inquiry","enquiry"],
  model:"Scientists are carrying out an investigation into the shrinking of the lake.",
  why:"Noun-verb transformation: 'investigating' -> 'carrying out an investigation into'. 'Why the lake is shrinking' also becomes a noun phrase: 'the shrinking of the lake'."},
 {id:"PP-099", type:"noun-verb", band:7, original:"The museum intends to expand its collection of modern sculpture.",
  task:"choose", q:"Which sentence has the SAME meaning?",
  opts:["The museum has recently completed the expansion of its modern sculpture collection.","The museum intends to reduce its collection of modern sculpture.","The museum has plans for the expansion of its modern sculpture collection.","The museum's modern sculpture collection is the reason for its expansion."], a:2,
  model:"The museum has plans for the expansion of its modern sculpture collection.",
  why:"Noun-verb transformation: 'intends to expand' -> 'has plans for the expansion of'. 'Recently completed' changes a plan into a finished action; 'reduce' reverses the direction; the last option reverses cause and effect."},
 {id:"PP-100", type:"noun-verb", band:7.5, original:"Consumers are increasingly aware of how plastic harms the environment.",
  task:"complete", q:"There is growing ___ among consumers of the environmental harm caused by plastic.", a:["awareness","public awareness","understanding"],
  model:"There is growing awareness among consumers of the environmental harm caused by plastic.",
  why:"Nominalisation: 'are increasingly aware' -> 'there is growing awareness'; 'how plastic harms the environment' -> 'the environmental harm caused by plastic'."},

 // ---------- CHANGING SENTENCE STRUCTURE (PP-101 .. PP-120) ----------
 {id:"PP-101", type:"structure", band:5.5, original:"Although it was raining, the concert went ahead.",
  task:"choose", q:"Which sentence has the SAME meaning?",
  opts:["The concert was cancelled because it was raining.","Despite the rain, the concert went ahead.","Because of the rain, the concert went ahead.","The concert went ahead before it started raining."], a:1,
  model:"Despite the rain, the concert went ahead.",
  why:"Structure: 'although + clause' -> 'despite + noun'. 'Cancelled' contradicts the result; 'because of' turns contrast into cause; 'before it started raining' changes the time."},
 {id:"PP-102", type:"structure", band:6, original:"Although the hotel was expensive, we enjoyed our stay.",
  task:"complete", q:"Despite ___ expensive, we enjoyed our stay at the hotel.", a:["it being","its being","the hotel being"],
  model:"Despite it being expensive, we enjoyed our stay at the hotel.",
  why:"Structure: 'although + subject + verb' -> 'despite + (subject) + -ing'. 'Despite' cannot be followed by a full clause such as 'it was'."},
 {id:"PP-103", type:"structure", band:6.5, original:"The bridge was closed because of the strong winds.",
  task:"choose", q:"Which sentence has the SAME meaning?",
  opts:["The strong winds were caused by the closure of the bridge.","The strong winds led to the closure of the bridge.","The bridge was closed in spite of the strong winds.","The strong winds started after the bridge had closed."], a:1,
  model:"The strong winds led to the closure of the bridge.",
  why:"Structure: cause and effect reordered - 'X happened because of Y' -> 'Y led to X'. The first option reverses cause and effect; 'in spite of' turns cause into contrast; the last option changes the time order."},
 {id:"PP-104", type:"structure", band:7, original:"The lack of affordable housing is what worries young people most.",
  task:"complete", q:"What worries young people most ___ the lack of affordable housing.", a:["is"],
  model:"What worries young people most is the lack of affordable housing.",
  why:"Structure: a pseudo-cleft sentence ('What ... is ...') moves the focus to the end of the sentence. The meaning stays the same."},
 {id:"PP-105", type:"structure", band:7.5, original:"Only after the third trial did the researchers notice the error.",
  task:"choose", q:"Which sentence has the SAME meaning?",
  opts:["The researchers noticed the error before the third trial.","The researchers did not notice the error until the third trial was over.","The researchers noticed the error during every trial.","The error caused the researchers to run a third trial."], a:1,
  model:"The researchers did not notice the error until the third trial was over.",
  why:"Structure: inversion after 'only after' -> 'not ... until'. 'Before the third trial' reverses the time; 'during every trial' changes frequency; the last option invents a cause-effect link."},
 {id:"PP-106", type:"structure", band:5.5, original:"I went to bed early because I was tired.",
  task:"complete", q:"I was tired, ___ I went to bed early.", a:["so","and so","therefore"],
  model:"I was tired, so I went to bed early.",
  why:"Structure: the clause order changes, so 'because' (cause) is replaced by 'so' (result)."},
 {id:"PP-107", type:"structure", band:6, original:"The village is popular with tourists. It has a beautiful beach.",
  task:"choose", q:"Which sentence has the SAME meaning?",
  opts:["The village, which has a beautiful beach, is popular with tourists.","The village has a beautiful beach although it is popular with tourists.","The village became popular with tourists before it had a beach.","The village is popular with tourists who have a beautiful beach."], a:0,
  model:"The village, which has a beautiful beach, is popular with tourists.",
  why:"Structure: two simple sentences combined with a non-defining relative clause. 'Although' adds a contrast that does not exist; the third option changes the time; in the last option the relative clause describes the tourists instead of the village."},
 {id:"PP-108", type:"structure", band:6.5, original:"The manager, not the staff, made the final decision.",
  task:"complete", q:"It was the manager ___ made the final decision.", a:["who","that"],
  model:"It was the manager who made the final decision.",
  why:"Structure: a cleft sentence ('It was X who/that ...') emphasises the person responsible, just as 'not the staff' does."},
 {id:"PP-109", type:"structure", band:7, original:"While wind power is clean, it is less reliable than coal.",
  task:"choose", q:"Which sentence has the SAME meaning?",
  opts:["Wind power is both cleaner and more reliable than coal.","Wind power is clean; however, it is not as reliable as coal.","Wind power is less reliable than coal because it is clean.","Coal is cleaner than wind power, but less reliable."], a:1,
  model:"Wind power is clean; however, it is not as reliable as coal.",
  why:"Structure: concessive 'while' -> two clauses linked by 'however'. The first option loses the disadvantage; the third turns contrast into cause; the fourth swaps the qualities of the two energy sources."},
 {id:"PP-110", type:"structure", band:7.5, original:"The city did not begin to recover until the new port opened.",
  task:"complete", q:"It was not until the new port opened ___ the city began to recover.", a:["that"],
  model:"It was not until the new port opened that the city began to recover.",
  why:"Structure: 'not ... until' -> cleft 'It was not until ... that ...', which puts the turning point first."},
 {id:"PP-111", type:"structure", band:5.5, original:"Before I start work, I always have a coffee.",
  task:"choose", q:"Which sentence has the SAME meaning?",
  opts:["I always have a coffee after I start work.","I always have a coffee and then start work.","I sometimes have a coffee before work.","I start work because I have a coffee."], a:1,
  model:"I always have a coffee and then start work.",
  why:"Structure: time clause reordered with 'and then', keeping the same sequence. 'After' reverses the order; 'sometimes' changes the frequency; 'because' invents a cause."},
 {id:"PP-112", type:"structure", band:6, original:"Even though he had little experience, he got the job.",
  task:"complete", q:"In spite of having ___, he got the job.", a:["little experience","limited experience","not much experience"],
  model:"In spite of having little experience, he got the job.",
  why:"Structure: 'even though + clause' -> 'in spite of + -ing'. Keep the quantifier 'little' (= not much); 'a little' or 'no' would change the meaning."},
 {id:"PP-113", type:"structure", band:6.5, original:"Increased car use has led to worse air quality in cities.",
  task:"choose", q:"Which sentence has the SAME meaning?",
  opts:["Air quality in cities has improved despite increased car use.","Poor air quality in cities has made people use their cars more.","Air quality in cities has deteriorated as a result of increased car use.","Air quality in cities may get worse if car use increases."], a:2,
  model:"Air quality in cities has deteriorated as a result of increased car use.",
  why:"Structure: effect first, cause second ('X led to Y' -> 'Y as a result of X'). 'Improved' reverses the effect; the second option reverses cause and effect; the last changes a fact into a future possibility."},
 {id:"PP-114", type:"structure", band:7, original:"The professor's enthusiasm is the thing that students remember most.",
  task:"complete", q:"What students remember most ___ the professor's enthusiasm.", a:["is"],
  model:"What students remember most is the professor's enthusiasm.",
  why:"Structure: 'the thing that ... is' -> pseudo-cleft 'What ... is ...'."},
 {id:"PP-115", type:"structure", band:7.5, original:"The species survived only because the island was isolated.",
  task:"choose", q:"Which sentence has the SAME meaning?",
  opts:["Had the island not been isolated, the species would not have survived.","The species survived even though the island was isolated.","The island became isolated because the species survived.","The isolation of the island was one of many reasons the species survived."], a:0,
  model:"Had the island not been isolated, the species would not have survived.",
  why:"Structure: 'only because' -> a conditional showing the cause was essential. 'Even though' turns cause into contrast; the third option reverses cause and effect; 'one of many reasons' weakens 'only'."},
 {id:"PP-116", type:"structure", band:5.5, original:"The shop opens at nine, but the café doesn't open until ten.",
  task:"complete", q:"The café opens an hour ___ the shop.", a:["later than","after"],
  model:"The café opens an hour later than the shop.",
  why:"Structure: two contrasting clauses combined into one comparative sentence. Nine vs ten = an hour later."},
 {id:"PP-117", type:"structure", band:6, original:"You will improve your writing if you read more.",
  task:"choose", q:"Which sentence has the SAME meaning?",
  opts:["Reading more will help you improve your writing.","You should write more in order to read better.","You improved your writing because you read more.","Reading more will not affect your writing."], a:0,
  model:"Reading more will help you improve your writing.",
  why:"Structure: a conditional clause becomes the subject of the sentence (gerund 'Reading more'). The second option reverses the relationship; the third changes the time to the past; the fourth contradicts the original."},
 {id:"PP-118", type:"structure", band:6.5, original:"It is surprising that so few people use the new cycle lanes.",
  task:"complete", q:"___, very few people use the new cycle lanes.", a:["surprisingly","rather surprisingly","oddly enough"],
  model:"Surprisingly, very few people use the new cycle lanes.",
  why:"Structure: an introductory 'It is + adjective + that' clause is reduced to a sentence adverb ('Surprisingly, ...')."},
 {id:"PP-119", type:"structure", band:7, original:"However hard the team worked, they could not meet the deadline.",
  task:"choose", q:"Which sentence has the SAME meaning?",
  opts:["The team met the deadline because they worked hard.","No matter how hard the team worked, the deadline was impossible for them to meet.","The team did not work hard, so they missed the deadline.","The team worked hard only after the deadline had passed."], a:1,
  model:"No matter how hard the team worked, the deadline was impossible for them to meet.",
  why:"Structure: 'however + adjective' -> 'no matter how + adjective', with the main clause rephrased. The first option reverses the result; the third contradicts 'worked hard'; the fourth changes the time."},
 {id:"PP-120", type:"structure", band:7.5, original:"The scheme was so popular that the council decided to extend it.",
  task:"complete", q:"Such was the ___ of the scheme that the council decided to extend it.", a:["popularity","success"],
  model:"Such was the popularity of the scheme that the council decided to extend it.",
  why:"Structure: fronted 'Such was the + noun + of ...' (inversion) replaces 'so + adjective that'. The adjective 'popular' becomes the noun 'popularity'."},

 // ---------- REPORTING VERBS (PP-121 .. PP-140) ----------
 {id:"PP-121", type:"reporting", band:5.5, original:"\"The new park will open in May,\" the mayor said.",
  task:"choose", q:"Which sentence has the SAME meaning?",
  opts:["The mayor announced that the new park would open in May.","The mayor denied that the new park would open in May.","The mayor asked whether the new park would open in May.","The mayor announced that the new park had opened in May."], a:0,
  model:"The mayor announced that the new park would open in May.",
  why:"Reporting verb: 'said' -> 'announced', with 'will' backshifted to 'would'. 'Denied' reverses the statement; 'asked whether' turns it into a question; 'had opened' changes the time."},
 {id:"PP-122", type:"reporting", band:6, original:"\"You should book your tickets early,\" the travel agent told us.",
  task:"complete", q:"The travel agent ___ us to book our tickets early.", a:["advised","recommended","urged","encouraged"],
  model:"The travel agent advised us to book our tickets early.",
  why:"Reporting verb: 'should' suggests advice, so 'told us ... should' -> 'advised / urged us to + infinitive'. 'Ordered' would be too strong."},
 {id:"PP-123", type:"reporting", band:6.5, original:"Dr Okafor says that the results definitely show the treatment works.",
  task:"choose", q:"Which sentence has the SAME meaning?",
  opts:["Dr Okafor suggests that the treatment may work.","Dr Okafor claims that the results prove the treatment is effective.","Dr Okafor disputes the claim that the treatment works.","Dr Okafor hopes future results will show the treatment works."], a:1,
  model:"Dr Okafor claims that the results prove the treatment is effective.",
  why:"Reporting verb: a confident statement is reported with 'claims', and 'definitely show' = 'prove'. 'Suggests ... may' is too tentative; 'disputes' reverses her position; 'hopes ... future' changes certainty and time."},
 {id:"PP-124", type:"reporting", band:7, original:"\"I didn't take the files,\" the employee said.",
  task:"complete", q:"The employee ___ the files.", a:["denied taking","denied having taken","denied stealing"],
  model:"The employee denied taking the files.",
  why:"Reporting verb: a negative statement about one's own action is reported with 'deny + -ing'. Note the negative disappears because 'deny' already contains it."},
 {id:"PP-125", type:"reporting", band:7.5, original:"The author admits that her sample was small but insists the pattern is real.",
  task:"choose", q:"Which sentence has the SAME meaning?",
  opts:["The author acknowledges the limited size of her sample, yet maintains that the pattern is genuine.","The author denies that her sample was small and maintains that the pattern is genuine.","The author acknowledges that the small sample means the pattern is probably not real.","The author suggests that a larger sample might reveal a pattern."], a:0,
  model:"The author acknowledges the limited size of her sample, yet maintains that the pattern is genuine.",
  why:"Reporting verbs: 'admits' = 'acknowledges' (accepts a weakness), 'insists' = 'maintains' (holds firmly to a view). 'Denies' reverses the admission; the third option reverses her conclusion; the fourth says no pattern has been found yet."},
 // END
];
