/* ===== EXTRA WRITING & SPEAKING PROMPTS (original, IELTS-style). Chart figures are invented practice data. ===== */

export const WRITING_T1_EXTRA = [
 /* ---------- Line graphs ---------- */
 {id:"T1-x01", type:"Line graph", title:"Home heating fuels", prompt:"The graph below shows the percentage of households in one country using four main types of heating between 1990 and 2025.\n\nSummarise the information by selecting and reporting the main features, and make comparisons where relevant.",
  chart:{kind:"line", unit:"% of households", xLabels:["1990","1995","2000","2005","2010","2015","2020","2025"], series:[
   {name:"Gas",values:[45,52,58,61,60,57,51,44]},
   {name:"Oil",values:[38,32,26,20,16,12,9,6]},
   {name:"Heat pumps",values:[2,2,3,5,9,15,24,37]},
   {name:"Wood and other",values:[15,14,13,14,15,16,16,13]}]}},
 {id:"T1-x02", type:"Line graph", title:"Commuting times in four cities", prompt:"The graph below shows the average time (in minutes) that workers in four cities spent travelling to work each day between 2004 and 2024.\n\nSummarise the information by selecting and reporting the main features, and make comparisons where relevant.",
  chart:{kind:"line", unit:"minutes", xLabels:["2004","2008","2012","2016","2020","2024"], series:[
   {name:"Northbridge",values:[38,41,45,48,31,36]},
   {name:"Kelvale",values:[52,50,47,43,30,33]},
   {name:"Port Avery",values:[25,27,30,34,22,29]},
   {name:"Redmoor",values:[30,30,31,31,20,21]}]}},
 {id:"T1-x03", type:"Line graph", title:"Music sales by format", prompt:"The graph below shows revenue from four formats of recorded music in one country between 2000 and 2024.\n\nSummarise the information by selecting and reporting the main features, and make comparisons where relevant.",
  chart:{kind:"line", unit:"US$ million", xLabels:["2000","2004","2008","2012","2016","2020","2024"], series:[
   {name:"CDs",values:[820,760,540,310,150,70,45]},
   {name:"Digital downloads",values:[0,40,210,330,240,90,30]},
   {name:"Streaming",values:[0,0,15,80,290,560,740]},
   {name:"Vinyl records",values:[20,12,8,15,40,75,95]}]}},
 {id:"T1-x04", type:"Line graph", title:"Age of mothers at first birth", prompt:"The graph below shows the average age of women when they had their first child in three countries from 1970 to 2020.\n\nSummarise the information by selecting and reporting the main features, and make comparisons where relevant.",
  chart:{kind:"line", unit:"years", xLabels:["1970","1980","1990","2000","2010","2020"], series:[
   {name:"Country A",values:[23.5,24.8,26.9,28.6,29.8,31.0]},
   {name:"Country B",values:[21.2,22.0,23.1,25.4,27.9,29.6]},
   {name:"Country C",values:[24.6,25.1,25.6,26.0,26.3,26.5]}]}},
 {id:"T1-x05", type:"Line graph", title:"Monthly visitors to a national park", prompt:"The graph below shows the number of visitors (in thousands) to a national park in each month of 2015 and 2025.\n\nSummarise the information by selecting and reporting the main features, and make comparisons where relevant.",
  chart:{kind:"line", unit:"thousand visitors", xLabels:["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"], series:[
   {name:"2015",values:[12,14,22,35,48,70,95,98,52,30,15,10]},
   {name:"2025",values:[25,28,40,55,66,78,88,90,72,55,30,24]}]}},
 /* ---------- Bar charts ---------- */
 {id:"T1-x06", type:"Bar chart", title:"Household waste treatment", prompt:"The chart below shows the proportion of household waste that was recycled, burned for energy or sent to landfill in five countries in 2023.\n\nSummarise the information by selecting and reporting the main features, and make comparisons where relevant.",
  chart:{kind:"bar", unit:"%", categories:["Country A","Country B","Country C","Country D","Country E"], series:[
   {name:"Recycled",values:[62,45,28,51,18]},
   {name:"Incinerated",values:[30,20,10,42,5]},
   {name:"Landfill",values:[8,35,62,7,77]}]}},
 {id:"T1-x07", type:"Bar chart", title:"Housework by gender", prompt:"The chart below shows the average number of hours per week that men and women in one country spent on unpaid housework between 1985 and 2025.\n\nSummarise the information by selecting and reporting the main features, and make comparisons where relevant.",
  chart:{kind:"bar", unit:"hours per week", categories:["1985","1995","2005","2015","2025"], series:[
   {name:"Men",values:[6,8,10,12,14]},
   {name:"Women",values:[28,25,22,20,18]}]}},
 {id:"T1-x08", type:"Bar chart", title:"Research and development spending", prompt:"The chart below shows spending on research and development as a percentage of GDP in six countries in 2005 and 2025.\n\nSummarise the information by selecting and reporting the main features, and make comparisons where relevant.",
  chart:{kind:"bar", unit:"% of GDP", categories:["Country A","Country B","Country C","Country D","Country E","Country F"], series:[
   {name:"2005",values:[2.4,1.1,3.1,0.6,1.8,2.0]},
   {name:"2025",values:[3.3,1.9,3.0,1.4,1.7,2.9]}]}},
 {id:"T1-x09", type:"Bar chart", title:"Sports participation by gender", prompt:"The chart below shows the percentage of men and women in one country who took part in six physical activities at least once a month in 2024.\n\nSummarise the information by selecting and reporting the main features, and make comparisons where relevant.",
  chart:{kind:"bar", unit:"% of adults", categories:["Swimming","Cycling","Running","Football","Yoga","Gym"], series:[
   {name:"Men",values:[22,28,24,18,4,26]},
   {name:"Women",values:[27,15,19,4,17,23]}]}},
 {id:"T1-x10", type:"Bar chart", title:"Household food waste", prompt:"The chart below shows the average amount of food (in kilograms per year) thrown away by households in one country, by type of food, in 2012 and 2024.\n\nSummarise the information by selecting and reporting the main features, and make comparisons where relevant.",
  chart:{kind:"bar", unit:"kg per household per year", categories:["Fruit and vegetables","Bread","Dairy","Meat and fish","Ready meals"], series:[
   {name:"2012",values:[68,31,22,14,19]},
   {name:"2024",values:[52,26,18,9,30]}]}},
 /* ---------- Pie charts ---------- */
 {id:"T1-x11", type:"Pie chart", title:"Household electricity use", prompt:"The pie charts below show how electricity was used in an average home in one country in 2000 and 2025.\n\nSummarise the information by selecting and reporting the main features, and make comparisons where relevant.",
  chart:{kind:"pie", pies:[
   {title:"2000",slices:[{label:"Heating and cooling",value:42},{label:"Water heating",value:18},{label:"Lighting",value:12},{label:"Kitchen appliances",value:20},{label:"Electronic devices",value:8}]},
   {title:"2025",slices:[{label:"Heating and cooling",value:35},{label:"Water heating",value:15},{label:"Lighting",value:5},{label:"Kitchen appliances",value:22},{label:"Electronic devices",value:14},{label:"Electric car charging",value:9}]}]}},
 {id:"T1-x12", type:"Pie chart", title:"Population by age group", prompt:"The pie charts below show the age structure of the population of one country in 1975 and 2025, and the projected structure for 2075.\n\nSummarise the information by selecting and reporting the main features, and make comparisons where relevant.",
  chart:{kind:"pie", pies:[
   {title:"1975",slices:[{label:"0-14 years",value:34},{label:"15-64 years",value:58},{label:"65+ years",value:8}]},
   {title:"2025",slices:[{label:"0-14 years",value:18},{label:"15-64 years",value:64},{label:"65+ years",value:18}]},
   {title:"2075 (projected)",slices:[{label:"0-14 years",value:13},{label:"15-64 years",value:57},{label:"65+ years",value:30}]}]}},
 {id:"T1-x13", type:"Pie chart", title:"How students travel to campus", prompt:"The pie charts below show the main ways in which students at one university travelled to campus in 2010 and 2024.\n\nSummarise the information by selecting and reporting the main features, and make comparisons where relevant.",
  chart:{kind:"pie", pies:[
   {title:"2010",slices:[{label:"Car",value:38},{label:"Bus",value:27},{label:"Bicycle",value:10},{label:"Walking",value:15},{label:"Train",value:10}]},
   {title:"2024",slices:[{label:"Car",value:18},{label:"Bus",value:30},{label:"Bicycle",value:22},{label:"Walking",value:16},{label:"Train",value:9},{label:"E-scooter",value:5}]}]}},
 {id:"T1-x14", type:"Pie chart", title:"Reasons for leaving a job", prompt:"The pie charts below show the main reasons employees in one country gave for leaving their jobs in 2014 and 2024.\n\nSummarise the information by selecting and reporting the main features, and make comparisons where relevant.",
  chart:{kind:"pie", pies:[
   {title:"2014",slices:[{label:"Low salary",value:35},{label:"Lack of flexibility",value:8},{label:"Limited promotion",value:22},{label:"Workload and stress",value:15},{label:"Moving home",value:12},{label:"Other",value:8}]},
   {title:"2024",slices:[{label:"Low salary",value:26},{label:"Lack of flexibility",value:22},{label:"Limited promotion",value:18},{label:"Workload and stress",value:19},{label:"Moving home",value:8},{label:"Other",value:7}]}]}}
,
 /* ---------- Tables ---------- */
 {id:"T1-x15", type:"Table", title:"Tourism in five cities", prompt:"The table below shows the number of international visitors to five cities in 2015 and 2025, together with the average length of stay and average daily spending per visitor in 2025.\n\nSummarise the information by selecting and reporting the main features, and make comparisons where relevant.",
  chart:{kind:"table", head:["City","Visitors 2015 (millions)","Visitors 2025 (millions)","Average stay (nights)","Daily spending (US$)"], rows:[
   ["Alvara","4.2","6.8","3.1","145"],["Belmont","8.5","7.9","4.6","210"],["Cortez","1.3","3.9","2.4","95"],["Dunmore","6.1","6.4","5.8","180"],["Elsby","2.7","2.5","6.9","120"]]}},
 {id:"T1-x16", type:"Table", title:"Device ownership by age", prompt:"The table below shows the percentage of adults in one country who owned five types of digital device in 2025, by age group.\n\nSummarise the information by selecting and reporting the main features, and make comparisons where relevant.",
  chart:{kind:"table", head:["Age group","Smartphone","Laptop","Tablet","Smartwatch","Games console"], rows:[
   ["16-24","98%","71%","35%","38%","52%"],["25-34","97%","78%","44%","41%","39%"],["35-54","93%","74%","52%","30%","24%"],["55-74","81%","59%","48%","14%","8%"],["75+","52%","31%","29%","4%","2%"]]}},
 {id:"T1-x17", type:"Table", title:"Domestic water use", prompt:"The table below shows the average amount of water (in litres) used per person each day for different purposes in five countries.\n\nSummarise the information by selecting and reporting the main features, and make comparisons where relevant.",
  chart:{kind:"table", head:["Country","Drinking and cooking","Bathing","Toilet","Laundry","Garden","Total"], rows:[
   ["Country A","8","62","35","20","25","150"],["Country B","7","45","28","15","5","100"],["Country C","9","90","45","30","66","240"],["Country D","6","30","18","10","2","66"],["Country E","8","55","30","18","14","125"]]}},
 {id:"T1-x18", type:"Table", title:"Employment by sector", prompt:"The table below shows the number of people (in thousands) employed in different sectors in one region in 1980, 2000 and 2020.\n\nSummarise the information by selecting and reporting the main features, and make comparisons where relevant.",
  chart:{kind:"table", head:["Sector","1980","2000","2020"], rows:[
   ["Agriculture","120","70","35"],["Manufacturing","310","240","150"],["Construction","90","110","105"],["Retail","140","190","200"],["Health and education","110","180","265"],["Finance and IT","30","95","180"],["Total","800","885","935"]]}},
 /* ---------- Processes ---------- */
 {id:"T1-x19", type:"Process", title:"Life cycle of the salmon", prompt:"The diagram below shows the life cycle of a species of salmon.\n\nSummarise the information by selecting and reporting the main features.",
  chart:{kind:"process", steps:["Adult salmon lay eggs in gravel on a shallow river bed","Eggs hatch after about 2-3 months into small 'alevins'","Alevins stay hidden in the gravel, feeding on their yolk sacs","Young fish ('fry') emerge and feed in the upper river for up to 2 years","Fish turn silver ('smolts') and swim downstream to the sea","Salmon grow to adult size in the ocean over 1-4 years","Adults return upstream to the river where they were born","Adults spawn and the cycle begins again"]}},
 {id:"T1-x20", type:"Process", title:"Making chocolate", prompt:"The diagram below shows the stages in the production of chocolate from cocoa beans.\n\nSummarise the information by selecting and reporting the main features.",
  chart:{kind:"process", steps:["Ripe cocoa pods harvested by hand","Pods split open and beans removed","Beans fermented under banana leaves for 5-7 days","Beans dried in the sun for about a week","Dried beans packed in sacks and shipped to a factory","Beans roasted at 120-150°C","Shells removed, leaving cocoa 'nibs'","Nibs ground into a thick cocoa paste","Paste mixed with sugar and milk, then poured into moulds and cooled"]}},
 {id:"T1-x21", type:"Process", title:"Producing olive oil", prompt:"The diagram below shows how olive oil is produced.\n\nSummarise the information by selecting and reporting the main features.",
  chart:{kind:"process", steps:["Olives harvested from trees in late autumn","Leaves and twigs removed by a blower","Olives washed in cold water","Olives crushed, with their stones, into a paste","Paste slowly mixed for 30-45 minutes","Oil separated from water and solids in a centrifuge","Oil filtered and stored in steel tanks","Oil bottled, labelled and distributed"]}},
 {id:"T1-x22", type:"Process", title:"How a fossil is formed", prompt:"The diagram below shows how a fossil is formed.\n\nSummarise the information by selecting and reporting the main features.",
  chart:{kind:"process", steps:["An animal dies and its body sinks to the bottom of a lake or sea","Soft parts decay, leaving bones or shell","Layers of mud and sand gradually cover the remains","Over millions of years the layers are pressed into rock","Minerals in water replace the bone, creating a stone copy","Movements of the earth push the rock layers upwards","Wind and rain wear away the rock, exposing the fossil"]}},
 /* ---------- Maps ---------- */
 {id:"T1-x23", type:"Map", title:"Riverside park redevelopment", prompt:"The maps below show an area beside a river in 1995 and today.\n\nSummarise the information by selecting and reporting the main features, and make comparisons where relevant.",
  chart:{kind:"map", maps:[
   {title:"1995",features:[{x:0,y:0,w:260,h:28,label:"River Lune"},{x:10,y:38,w:110,h:60,label:"Warehouses"},{x:140,y:38,w:110,h:60,label:"Car park"},{x:0,y:106,w:260,h:20,label:"Mill Road",road:true},{x:10,y:134,w:110,h:56,label:"Allotments"},{x:140,y:134,w:110,h:56,label:"Grassland"}]},
   {title:"Today",features:[{x:0,y:0,w:260,h:28,label:"River Lune"},{x:180,y:0,w:16,h:38,label:"Footbridge",road:true},{x:10,y:38,w:110,h:60,label:"Café & riverside walk"},{x:140,y:38,w:110,h:60,label:"Playground & skate park"},{x:0,y:106,w:260,h:20,label:"Mill Road (with cycle lane)",road:true},{x:10,y:134,w:55,h:56,label:"Allotments"},{x:70,y:134,w:50,h:56,label:"Wildflower meadow"},{x:140,y:134,w:110,h:56,label:"Sports pitches"}]}]}},
 {id:"T1-x24", type:"Map", title:"University campus changes", prompt:"The maps below show a university campus in 2005 and 2025.\n\nSummarise the information by selecting and reporting the main features, and make comparisons where relevant.",
  chart:{kind:"map", maps:[
   {title:"2005",features:[{x:10,y:10,w:100,h:60,label:"Main building"},{x:120,y:10,w:60,h:60,label:"Library"},{x:190,y:10,w:60,h:60,label:"Car park"},{x:0,y:80,w:260,h:20,label:"College Road",road:true},{x:10,y:110,w:140,h:80,label:"Sports field"},{x:160,y:110,w:90,h:80,label:"Student housing"}]},
   {title:"2025",features:[{x:10,y:10,w:100,h:60,label:"Main building"},{x:120,y:10,w:130,h:60,label:"Learning centre (library + IT)"},{x:0,y:80,w:260,h:20,label:"College Road (bus stop)",road:true},{x:10,y:110,w:70,h:80,label:"Sports hall"},{x:85,y:110,w:62,h:80,label:"Multi-storey car park"},{x:150,y:100,w:8,h:100,label:"Footpath",road:true},{x:160,y:110,w:90,h:80,label:"Student housing (3 new blocks)"}]}]}},
 {id:"T1-x25", type:"Map", title:"A fishing village becomes a resort", prompt:"The maps below show a coastal village in 1980 and today.\n\nSummarise the information by selecting and reporting the main features, and make comparisons where relevant.",
  chart:{kind:"map", maps:[
   {title:"1980",features:[{x:10,y:10,w:90,h:68,label:"Fishermen's cottages"},{x:110,y:10,w:140,h:68,label:"Farmland"},{x:0,y:85,w:260,h:18,label:"Coast Road",road:true},{x:10,y:110,w:90,h:35,label:"Fishing harbour"},{x:110,y:110,w:140,h:35,label:"Beach"},{x:0,y:152,w:260,h:48,label:"Sea"}]},
   {title:"Today",features:[{x:10,y:10,w:90,h:68,label:"Cottages (holiday lets)"},{x:110,y:10,w:70,h:68,label:"Hotel"},{x:185,y:10,w:65,h:68,label:"Caravan park"},{x:0,y:85,w:260,h:18,label:"Coast Road (widened)",road:true},{x:10,y:110,w:90,h:35,label:"Marina (yachts)"},{x:110,y:110,w:90,h:35,label:"Beach"},{x:0,y:152,w:260,h:48,label:"Sea"},{x:210,y:110,w:30,h:70,label:"Pier"}]}]}},
 /* ---------- Mixed charts ---------- */
 {id:"T1-x26", type:"Mixed charts", title:"Online shopping", prompt:"The line graph shows the percentage of all retail sales made online in one country between 2012 and 2024. The pie chart shows online sales by product category in 2024.\n\nSummarise the information by selecting and reporting the main features, and make comparisons where relevant.",
  chart:{kind:"multi", charts:[
   {kind:"line", unit:"% of retail sales", xLabels:["2012","2014","2016","2018","2020","2022","2024"], series:[{name:"Online share",values:[6,8,11,15,27,24,26]}]},
   {kind:"pie", pies:[{title:"Online sales by category, 2024",slices:[{label:"Clothing and shoes",value:28},{label:"Electronics",value:22},{label:"Groceries",value:17},{label:"Home and garden",value:14},{label:"Books and media",value:8},{label:"Other",value:11}]}]}]}},
 {id:"T1-x27", type:"Mixed charts", title:"Public library use", prompt:"The bar chart shows the percentage of people in each age group who were members of public libraries in one city in 2015 and 2025. The table shows the number of items borrowed, by format, in the same years.\n\nSummarise the information by selecting and reporting the main features, and make comparisons where relevant.",
  chart:{kind:"multi", charts:[
   {kind:"bar", unit:"% of age group", categories:["Under 12","12-17","18-34","35-59","60+"], series:[{name:"2015",values:[58,34,22,27,41]},{name:"2025",values:[63,25,29,24,45]}]},
   {kind:"table", head:["Format","Loans 2015 (thousands)","Loans 2025 (thousands)"], rows:[["Printed books","2,450","1,620"],["E-books","180","940"],["Audiobooks","95","610"],["DVDs","520","40"]]}]}},
 {id:"T1-x28", type:"Mixed charts", title:"A charity's income and spending", prompt:"The bar chart shows the sources of a charity's income in 2020 and 2024. The pie chart shows how the charity spent its money in 2024.\n\nSummarise the information by selecting and reporting the main features, and make comparisons where relevant.",
  chart:{kind:"multi", charts:[
   {kind:"bar", unit:"£ million", categories:["Individual donations","Legacies","Charity shops","Government grants","Corporate partners"], series:[{name:"2020",values:[14.2,6.1,8.4,5.5,2.0]},{name:"2024",values:[18.9,7.3,6.2,3.1,4.6]}]},
   {kind:"pie", pies:[{title:"Spending, 2024",slices:[{label:"Projects overseas",value:54},{label:"Emergency relief",value:18},{label:"Fundraising",value:14},{label:"Campaigns and education",value:9},{label:"Administration",value:5}]}]}]}}
];

export const WRITING_T2_EXTRA = [
 /* ---------- Opinion ---------- */
 {id:"T2-x01", type:"Opinion essay", prompt:"Some people argue that schools should stop giving homework to children under the age of twelve. To what extent do you agree or disagree?"},
 {id:"T2-x02", type:"Opinion essay", prompt:"Governments should place a high tax on sugary drinks and fast food in order to improve public health. To what extent do you agree or disagree?"},
 {id:"T2-x03", type:"Opinion essay", prompt:"Some people believe that private cars should be banned from city centres altogether. To what extent do you agree or disagree?"},
 {id:"T2-x04", type:"Opinion essay", prompt:"Space exploration is a waste of money, and the funds would be better spent solving problems on Earth. To what extent do you agree or disagree?"},
 {id:"T2-x05", type:"Opinion essay", prompt:"Some people think that the best way to reduce crime is to give longer prison sentences. To what extent do you agree or disagree?"},
 {id:"T2-x06", type:"Opinion essay", prompt:"Companies should be legally required to offer a four-day working week to all their employees. To what extent do you agree or disagree?"},
 {id:"T2-x07", type:"Opinion essay", prompt:"Newspapers and news websites should be prohibited from publishing details of the private lives of politicians and celebrities. To what extent do you agree or disagree?"},
 {id:"T2-x08", type:"Opinion essay", prompt:"Learning a foreign language is no longer necessary because translation technology is becoming so accurate. To what extent do you agree or disagree?"},
 /* ---------- Discussion ---------- */
 {id:"T2-x09", type:"Discussion essay", prompt:"Some people believe that children should be taught to be competitive at school, while others think that cooperation and teamwork are more valuable. Discuss both views and give your own opinion."},
 {id:"T2-x10", type:"Discussion essay", prompt:"Some people think that protecting the environment is the responsibility of governments, while others believe individuals must change their own behaviour. Discuss both views and give your own opinion."},
 {id:"T2-x11", type:"Discussion essay", prompt:"Some argue that old buildings in city centres should be preserved, while others believe they should be replaced with modern buildings that meet current needs. Discuss both views and give your own opinion."},
 {id:"T2-x12", type:"Discussion essay", prompt:"Some people say that the main purpose of television and online media is to entertain, while others think it should educate and inform. Discuss both views and give your own opinion."},
 {id:"T2-x13", type:"Discussion essay", prompt:"Some people believe that scientific research should be funded mainly by governments, while others think private companies are better placed to pay for it. Discuss both views and give your own opinion."},
 {id:"T2-x14", type:"Discussion essay", prompt:"Some people think that elderly parents should live with their adult children, while others believe they are better cared for in specialist homes. Discuss both views and give your own opinion."},
 {id:"T2-x15", type:"Discussion essay", prompt:"Some people believe that globalisation helps poorer countries to develop, while others argue that it mainly benefits wealthy nations and large corporations. Discuss both views and give your own opinion."},
 {id:"T2-x16", type:"Discussion essay", prompt:"Some people think that young offenders should be punished in the same way as adults, while others believe they should be given education and support instead. Discuss both views and give your own opinion."},
 /* ---------- Advantages / disadvantages ---------- */
 {id:"T2-x17", type:"Advantages/Disadvantages", prompt:"In many countries, artificial intelligence is now being used to mark students' exams and essays. Do the advantages of this outweigh the disadvantages?"},
 {id:"T2-x18", type:"Advantages/Disadvantages", prompt:"More and more cities are hosting major international sporting events such as the Olympic Games. Do the advantages of hosting such events outweigh the disadvantages?"},
 {id:"T2-x19", type:"Advantages/Disadvantages", prompt:"Many people now prefer to rent a home for their whole lives rather than buy one. Do the advantages of this outweigh the disadvantages?"},
 {id:"T2-x20", type:"Advantages/Disadvantages", prompt:"Some supermarkets and banks are replacing human staff with self-service machines. Do the advantages of this outweigh the disadvantages?"},
 {id:"T2-x21", type:"Advantages/Disadvantages", prompt:"In some countries, a growing number of children are educated at home by their parents rather than at school. Do the advantages of home schooling outweigh the disadvantages?"},
 {id:"T2-x22", type:"Advantages/Disadvantages", prompt:"Many governments are investing in high-speed rail networks to connect their major cities. Do the advantages of this outweigh the disadvantages?"},
 {id:"T2-x23", type:"Advantages/Disadvantages", prompt:"Some popular tourist destinations now charge visitors a daily entry fee. Do the advantages of this policy outweigh the disadvantages?"},
 {id:"T2-x24", type:"Advantages/Disadvantages", prompt:"Increasingly, people are using smartwatches and health apps to monitor their sleep, diet and exercise. Do the advantages of this outweigh the disadvantages?"},
 /* ---------- Problem / solution ---------- */
 {id:"T2-x25", type:"Problem/Solution", prompt:"In many countries, the amount of plastic waste in the oceans is increasing rapidly. What are the causes of this problem and what measures could be taken to solve it?"},
 {id:"T2-x26", type:"Problem/Solution", prompt:"Many young people leave rural areas to find work in cities, leaving villages with ageing populations. What are the causes of this problem and what measures could be taken to solve it?"},
 {id:"T2-x27", type:"Problem/Solution", prompt:"Levels of childhood obesity are rising in many parts of the world. What are the causes of this problem and what measures could be taken to solve it?"},
 {id:"T2-x28", type:"Problem/Solution", prompt:"Traffic congestion is becoming worse in many large cities, despite investment in new roads. What are the causes of this problem and what measures could be taken to solve it?"},
 {id:"T2-x29", type:"Problem/Solution", prompt:"Many traditional crafts and local languages are in danger of disappearing. What are the causes of this problem and what measures could be taken to solve it?"},
 {id:"T2-x30", type:"Problem/Solution", prompt:"Online fraud and identity theft are increasing as more people shop and bank on the internet. What are the causes of this problem and what measures could be taken to solve it?"},
 {id:"T2-x31", type:"Problem/Solution", prompt:"In many workplaces, employees report high levels of stress and burnout. What are the causes of this problem and what measures could be taken to solve it?"},
 {id:"T2-x32", type:"Problem/Solution", prompt:"A large number of university graduates are unable to find jobs that match their qualifications. What are the causes of this problem and what measures could be taken to solve it?"},
 /* ---------- Two-part question ---------- */
 {id:"T2-x33", type:"Two-part question", prompt:"Fewer people today attend live theatre, opera and classical music concerts than in the past. Why is this? What could be done to attract new audiences?"},
 {id:"T2-x34", type:"Two-part question", prompt:"In many countries, people are spending more time alone than ever before. Why is this happening? What effects does it have on individuals and society?"},
 {id:"T2-x35", type:"Two-part question", prompt:"Governments have limited budgets. Which areas of public spending do you think should be given the highest priority? Should citizens have a direct say in how this money is spent?"},
 {id:"T2-x36", type:"Two-part question", prompt:"Many people today get most of their news from social media rather than from newspapers or television. Why is this? What problems might this cause?"},
 {id:"T2-x37", type:"Two-part question", prompt:"Some people choose to buy second-hand clothes and furniture rather than new products. Why do they do this? Should this practice be encouraged?"},
 {id:"T2-x38", type:"Two-part question", prompt:"Scientists are able to extend human life expectancy further every year. What challenges does an ageing population create? How should society prepare for them?"},
 {id:"T2-x39", type:"Two-part question", prompt:"Many cities are becoming more and more alike, with the same shops, restaurants and architecture. Why is this happening? Is it something that should be prevented?"},
 {id:"T2-x40", type:"Two-part question", prompt:"Some parents give their children a great deal of freedom, while others set strict rules. What are the reasons for these different approaches? Which do you think produces better results?"},
 /* ---------- Positive / negative development ---------- */
 {id:"T2-x41", type:"Positive/Negative development", prompt:"In many countries, people are increasingly paying for goods and services with mobile phones instead of cash. Is this a positive or negative development?"},
 {id:"T2-x42", type:"Positive/Negative development", prompt:"More and more adults are returning to university or college to retrain for a completely different career in their forties or fifties. Is this a positive or negative development?"},
 {id:"T2-x43", type:"Positive/Negative development", prompt:"Large numbers of tourists now visit remote and fragile places such as Antarctica and high mountain regions. Is this a positive or negative development?"},
 {id:"T2-x44", type:"Positive/Negative development", prompt:"Many museums and galleries now use virtual reality and interactive screens instead of traditional displays. Is this a positive or negative development?"},
 {id:"T2-x45", type:"Positive/Negative development", prompt:"In some cities, surveillance cameras with facial recognition are being installed on streets and in public transport to prevent crime. Is this a positive or negative development?"},
 {id:"T2-x46", type:"Positive/Negative development", prompt:"Nowadays many young people become famous through online videos rather than through traditional careers in film, music or sport. Is this a positive or negative development?"},
 {id:"T2-x47", type:"Positive/Negative development", prompt:"An increasing number of people are choosing to work as freelancers rather than as permanent employees of one company. Is this a positive or negative development?"},
 {id:"T2-x48", type:"Positive/Negative development", prompt:"More and more food is being produced in laboratories and vertical indoor farms rather than on traditional farms. Is this a positive or negative development?"}
];

export const SPEAKING_P1_EXTRA = {
 "Music":["What kind of music do you usually listen to?","Did you learn to play a musical instrument as a child?","Do you prefer listening to music alone or with other people?","Has your taste in music changed as you have got older?"],
 "Reading":["Do you read much in your free time?","What did you like to read when you were a child?","Do you prefer printed books or reading on a screen?","Is there a book you would like to read again?"],
 "Sport":["Do you play any sports?","Which sport is the most popular in your country?","Did you enjoy sport lessons at school?","Do you prefer watching sport or taking part?"],
 "Shopping":["Do you enjoy going shopping?","Do you prefer shopping online or in shops?","What was the last thing you bought for yourself?","Are there any shops near your home that you go to often?"],
 "Mornings":["Are you a morning person?","What is the first thing you do after you wake up?","Do you have breakfast every day?","Are your mornings different at the weekend?"],
 "Cooking":["How often do you cook at home?","Who taught you to cook?","What dish would you cook for a guest?","Do you think children should learn to cook at school?"],
 "Neighbours":["Do you know your neighbours well?","How often do you talk to them?","Have your neighbours ever helped you with anything?","What makes someone a good neighbour?"],
 "Colours":["What is your favourite colour?","Are there any colours you would never wear?","What colours are the rooms in your home painted?","Do colours have special meanings in your culture?"],
 "Photography":["Do you like taking photos?","What do you usually take photos of?","Do you prefer taking photos with a phone or a camera?","Do you ever print your photos?"],
 "Plants":["Do you have any plants in your home?","Did you grow plants when you were a child?","Is there a plant or flower that is special in your country?","Would you like to have a garden?"],
 "Public transport":["What kinds of public transport are there in your town?","How often do you use public transport?","What do you like or dislike about it?","How could public transport in your area be improved?"],
 "Sleep":["How many hours do you usually sleep?","Do you ever take a nap during the day?","What do you do if you can't get to sleep?","Do you think people sleep less nowadays than in the past?"],
 "Clothes":["What kind of clothes do you usually wear?","Do you wear different clothes at work and at home?","Do you spend a lot of time choosing clothes?","Is there an item of clothing you have kept for a long time?"],
 "Birthdays":["How do you usually celebrate your birthday?","Which birthday do you remember most from your childhood?","Are birthdays more important for children or adults?","Do you prefer big parties or quiet celebrations?"],
 "Libraries":["Is there a library near where you live?","How often did you go to a library as a child?","What do people do in libraries in your country nowadays?","Do you think libraries are still necessary?"],
 "Rain":["Does it rain a lot where you live?","Do you like rainy days?","What do you usually do when it rains?","Can you remember a time when you got caught in the rain?"],
 "Museums":["Are there many museums in your hometown?","Did you visit museums on school trips?","What kind of museum do you find most interesting?","Do you prefer to visit a museum alone or with a guide?"],
 "Social media":["Which social media platforms do you use?","How much time do you spend on social media each day?","What kind of things do you post online?","Have you ever taken a break from social media?"],
 "Languages":["How many languages can you speak?","Which language would you like to learn next?","What is the most difficult part of learning a new language?","Do people in your country learn foreign languages from a young age?"],
 "Patience":["Would you describe yourself as a patient person?","In what situations do you find it hard to be patient?","Were you more patient as a child or are you more patient now?","Do you think modern technology makes people less patient?"],
 "Gifts":["Do you enjoy choosing gifts for other people?","What is the best gift you have ever received?","Do you prefer giving gifts or receiving them?","Is it acceptable to give money as a gift in your country?"],
 "Noise":["Is the area where you live noisy or quiet?","What kinds of noise annoy you most?","Do you prefer to work or study in silence?","Do you think cities are getting noisier?"],
 "Water":["How much water do you drink every day?","Do you prefer bottled water or tap water?","Do you enjoy being near water, for example rivers or the sea?","What do people in your country do to save water?"],
 "Maps":["Do you often use maps?","Do you prefer paper maps or digital maps on your phone?","Are you good at finding your way in a new place?","Did you learn how to read maps at school?"]
};

export const SPEAKING_P2_EXTRA = [
 {id:"C-x01",topic:"Describe an elderly person you admire.",points:["who this person is","how you know them","what they are like","and explain why you admire them"],p3:["What can young people learn from older people?","How are elderly people treated in your country?","Should older people be encouraged to keep working?","How will an ageing population change society in the future?"]},
 {id:"C-x02",topic:"Describe a neighbour who has helped you.",points:["who the neighbour is","how long you have known them","how they helped you","and explain how you felt about their help"],p3:["Do you think people know their neighbours less than in the past?","Why do some people prefer not to get to know their neighbours?","What can local councils do to build stronger communities?","Is a sense of community more important in cities or in the countryside?"]},
 {id:"C-x03",topic:"Describe a teacher who made a subject interesting for you.",points:["who the teacher was","what subject they taught","how they taught it","and explain why it made the subject interesting"],p3:["What qualities does a good teacher need?","Is teaching a well-respected job in your country?","Can technology ever replace teachers?","How should teachers be trained in the future?"]},
 {id:"C-x04",topic:"Describe a person you know who is good at their job.",points:["who the person is","what job they do","how you know them","and explain what makes them good at it"],p3:["Which jobs are most valued in your country?","Is it more important to enjoy your job or to earn a high salary?","How can employers motivate their staff?","Will people have more than one career in their lifetime in the future?"]},
 {id:"C-x05",topic:"Describe a famous person from your country who you would like to meet.",points:["who the person is","what they are famous for","how you know about them","and explain why you would like to meet them"],p3:["Why are people interested in the lives of celebrities?","Do famous people have a responsibility to be good role models?","Is it easier to become famous today than in the past?","Should the media respect the privacy of famous people?"]},
 {id:"C-x06",topic:"Describe a quiet place where you like to spend time.",points:["where it is","how often you go there","what you do there","and explain why you like it"],p3:["Why do people need quiet places?","Are there enough quiet public spaces in cities?","Do young people find it harder to be alone and quiet?","How can city planners reduce noise in urban areas?"]},
 {id:"C-x07",topic:"Describe a park or garden that you enjoy visiting.",points:["where it is","what it looks like","what people do there","and explain why you enjoy visiting it"],p3:["Why are parks important in cities?","Should new housing developments include green spaces?","Who should pay for the upkeep of public parks?","How might parks be used differently in the future?"]},
 {id:"C-x08",topic:"Describe a shop or market you often go to.",points:["where it is","what it sells","how often you go there","and explain why you like going there"],p3:["Why do some people prefer small local shops to supermarkets?","How has online shopping changed the high street?","Do traditional markets have a future?","Should governments protect small independent businesses?"]},
 {id:"C-x09",topic:"Describe a restaurant or café that you would recommend to visitors.",points:["where it is","what kind of food or drinks it serves","what the atmosphere is like","and explain why you would recommend it"],p3:["How often do people in your country eat out?","Is eating out a social activity or just a convenience?","How has the food people eat changed in recent years?","Will traditional dishes disappear because of global food chains?"]},
 {id:"C-x10",topic:"Describe a place in your country that is popular with tourists.",points:["where it is","what visitors can do there","when is the best time to go","and explain why it is so popular"],p3:["What do tourists usually want to see in your country?","Does tourism bring more benefits or problems to local people?","How can popular places be protected from too many visitors?","How will tourism change in the next twenty years?"]},
 {id:"C-x11",topic:"Describe an object in your home that is important to you.",points:["what the object is","where it came from","how long you have had it","and explain why it is important to you"],p3:["Why do people keep objects with sentimental value?","Do people today own too many things?","Is it better to spend money on experiences or possessions?","Will people value physical objects less in a digital future?"]},
 {id:"C-x12",topic:"Describe a piece of technology you find difficult to use.",points:["what it is","when you started using it","what problems you have with it","and explain how you deal with these difficulties"],p3:["Why do some people find new technology difficult?","Should older people be given training in using technology?","Do companies make technology unnecessarily complicated?","Is society becoming too dependent on technology?"]},
 {id:"C-x13",topic:"Describe something you bought that you were disappointed with.",points:["what you bought","where you bought it","why you bought it","and explain why you were disappointed"],p3:["What do people usually do when a product is faulty?","Are consumers well protected by the law in your country?","Does advertising encourage people to buy things they do not need?","Should companies be responsible for recycling the products they sell?"]},
 {id:"C-x14",topic:"Describe a gift you gave to someone that they really liked.",points:["what the gift was","who you gave it to","why you chose it","and explain why they liked it"],p3:["On what occasions do people give gifts in your country?","Is the price of a gift important?","Has the custom of giving gifts become too commercial?","Why do some cultures have strict rules about gift-giving?"]},
 {id:"C-x15",topic:"Describe a traditional festival or celebration in your country.",points:["what the festival is","when it takes place","what people do during it","and explain why it is important"],p3:["Do young people enjoy traditional festivals as much as older people?","How have festivals changed in your lifetime?","Should governments spend money on festivals?","Is it important to keep traditions alive in a globalised world?"]},
 {id:"C-x16",topic:"Describe a wedding or family celebration you attended.",points:["whose celebration it was","where it took place","what happened","and explain how you felt about it"],p3:["Why do people spend so much money on weddings?","How are family celebrations different from in the past?","Is it important for extended families to meet regularly?","Will traditional family events become less common in the future?"]},
 {id:"C-x17",topic:"Describe a sports event you watched or took part in.",points:["what the event was","where and when it took place","what happened","and explain why you remember it"],p3:["Why do people enjoy watching sport?","Are professional athletes paid too much?","Should schools put more emphasis on sport?","Does hosting a major sports event benefit a country in the long term?"]},
 {id:"C-x18",topic:"Describe a time when you were very busy.",points:["when it was","why you were busy","what you had to do","and explain how you managed your time"],p3:["Why are people so busy nowadays?","Is being busy a sign of success?","What can employers do to help staff balance work and life?","Will technology give people more free time in the future?"]}
,
 {id:"C-x19",topic:"Describe a time when you got lost.",points:["where you were","why you got lost","what you did","and explain how you felt"],p3:["Why do some people have a better sense of direction than others?","Have smartphones changed the way people find their way?","Should children be taught to read maps?","What happens when people rely completely on technology for navigation?"]},
 {id:"C-x20",topic:"Describe an occasion when you tried a new activity for the first time.",points:["what the activity was","when and where you tried it","who you were with","and explain how you felt about it"],p3:["Why are some people afraid of trying new things?","Is it easier for children or adults to try new activities?","Should people step outside their comfort zone regularly?","How can society encourage people to be more adventurous?"]},
 {id:"C-x21",topic:"Describe a time when you helped someone.",points:["who you helped","what the situation was","how you helped them","and explain how you felt afterwards"],p3:["Why do people help strangers?","Is volunteering common in your country?","Should schools require students to do voluntary work?","Are people becoming more or less helpful in modern society?"]},
 {id:"C-x22",topic:"Describe a time when you changed your mind about something.",points:["what you changed your mind about","what you thought before","what made you change your mind","and explain how you feel about it now"],p3:["Is it a sign of weakness to change your opinion?","Who influences young people's opinions most?","Why is it difficult for some people to accept new ideas?","How does the media shape public opinion?"]},
 {id:"C-x23",topic:"Describe a film or TV series that made a strong impression on you.",points:["what it was","when you watched it","what it was about","and explain why it made a strong impression"],p3:["What kinds of films are popular in your country?","Do films and TV series influence how people behave?","Should governments support their national film industry?","Will cinemas survive in the age of streaming?"]},
 {id:"C-x24",topic:"Describe a website or app you use regularly.",points:["what it is","how you found out about it","what you use it for","and explain why it is useful to you"],p3:["What kinds of apps are most popular among people in your country?","Do people spend too much time on their phones?","Should apps that collect personal data be more strictly controlled?","How will the way we use the internet change in the future?"]},
 {id:"C-x25",topic:"Describe a news story that interested you.",points:["what the story was about","where you heard or read it","when it happened","and explain why it interested you"],p3:["How do people in your country usually get their news?","Why do some people avoid the news?","How can people tell whether a news story is reliable?","Should news organisations be independent of governments?"]},
 {id:"C-x26",topic:"Describe a song or piece of music that is special to you.",points:["what the song or music is","when you first heard it","what it is like","and explain why it is special to you"],p3:["Why does music have such a strong effect on people's emotions?","Should all children learn to play an instrument?","How has technology changed the music industry?","Is traditional music in danger of disappearing?"]},
 {id:"C-x27",topic:"Describe a trip you are planning to take in the future.",points:["where you want to go","who you would like to go with","what you plan to do there","and explain why you want to take this trip"],p3:["How do people usually plan their holidays?","Is it better to plan everything in advance or to be spontaneous?","Why do some people prefer to travel abroad rather than in their own country?","How might climate change affect the way people travel?"]},
 {id:"C-x28",topic:"Describe a change you would like to make in your local area.",points:["what the change is","why it is needed","how it could be done","and explain how it would benefit local people"],p3:["What facilities are most important in a neighbourhood?","Should local people have a say in planning decisions?","Why do some people oppose new developments in their area?","How will cities need to change to cope with growing populations?"]},
 {id:"C-x29",topic:"Describe an achievement you are proud of.",points:["what you achieved","when it happened","how you achieved it","and explain why you are proud of it"],p3:["What kinds of achievements are most admired in your country?","Should children receive prizes for their achievements at school?","Is luck or hard work more important for success?","Does society place too much emphasis on individual success?"]},
 {id:"C-x30",topic:"Describe a competition you took part in or would like to enter.",points:["what the competition was","how you heard about it","what you had to do","and explain how you felt about it"],p3:["Why do people enjoy competitions?","Is competition good for children?","Do television talent shows help people develop real talent?","Can competition between companies benefit consumers?"]},
 {id:"C-x31",topic:"Describe a problem in your town or city and how it could be solved.",points:["what the problem is","who it affects","what causes it","and explain how it could be solved"],p3:["What are the most common problems in cities today?","Who is responsible for solving local problems?","Do people complain too much rather than taking action?","Will technology help to solve urban problems in the future?"]},
 {id:"C-x32",topic:"Describe a time when something you owned broke or stopped working.",points:["what it was","what happened to it","what you did about it","and explain how this affected you"],p3:["Do people repair things less often than in the past?","Why are many products designed not to last long?","Should manufacturers be required to make products easier to repair?","What effect does a throwaway culture have on the environment?"]},
 {id:"C-x33",topic:"Describe a natural place you visited that impressed you.",points:["where it was","when you went there","what you saw and did","and explain why it impressed you"],p3:["Why do people like to visit natural places?","Do people in cities spend enough time in nature?","Should some natural areas be closed to tourists?","How can governments balance economic development and nature protection?"]},
 {id:"C-x34",topic:"Describe an animal you find interesting.",points:["what the animal is","where you can see it","what it looks like and how it behaves","and explain why you find it interesting"],p3:["Why do people keep pets?","Is it right to keep animals in zoos?","What can be done to protect endangered species?","Should animals have the same rights as humans?"]},
 {id:"C-x35",topic:"Describe a time when you experienced extreme weather.",points:["when and where it happened","what the weather was like","what you did","and explain how you felt"],p3:["How does the weather affect people's daily lives?","Is extreme weather becoming more common in your country?","How should governments prepare for natural disasters?","Can individuals do anything to slow down climate change?"]},
 {id:"C-x36",topic:"Describe a time when you saw a beautiful view.",points:["where you were","when it was","what you could see","and explain why you found it beautiful"],p3:["Why do people take photos of beautiful views?","Do houses with good views cost more in your country?","Should tall buildings be banned if they block views?","Is natural beauty more important than economic growth?"]}
];
