/* ===== READING BANK — band 7.0 practice sets (original material written for this app) ===== */
export const SETS = [
{
 id:"R70-01", title:"What the Sleeping Brain Remembers", category:"Science", band:7, mock:null, mins:20,
 paras:[
 ["A","For most of the twentieth century, sleep was regarded by many scientists as little more than a period of enforced idleness, a state in which the brain, like a machine switched to standby, simply waited for the morning. That view has not survived the past three decades of laboratory work. It is now widely, if not universally, accepted that sleep plays an active part in memory consolidation – the process by which fragile, newly acquired information is converted into a more durable form. What remains far less settled is how this happens, which kinds of memory benefit, and whether the effects observed in the laboratory are large enough to matter in everyday life."],
 ["B","The earliest evidence was behavioural and, in retrospect, somewhat crude. Volunteers learned lists of words or pairs of nonsense syllables and were tested after an interval spent either asleep or awake. Those who had slept typically recalled more. Sceptics, however, pointed out a serious weakness in the design: the sleepers had also been spared the stream of new experiences that fills a waking day, and so their advantage might reflect nothing more than reduced interference from competing information. For several decades this objection proved difficult to answer, because it is almost impossible to keep a waking person in a state that resembles sleep in every respect except consciousness."],
 ["C","The debate shifted when researchers began to look inside the sleeping brain rather than simply comparing scores. Recordings from rodents navigating mazes revealed that groups of cells in the hippocampus, a structure deep in the brain associated with forming new memories, fired in particular sequences as the animals explored. Remarkably, the same sequences reappeared during subsequent sleep, often compressed into a fraction of their original duration. This 'replay', as it came to be known, suggested that the sleeping brain was rehearsing the day's experiences – and, crucially, the amount of replay recorded in some studies predicted how well the animals performed the following day."],
 ["D","Much of this activity occurs during slow-wave sleep, the deep stage that dominates the first part of the night. According to an influential model, the hippocampus acts as a temporary store, holding new memories until they can be gradually transferred to the cortex, the brain's outer layer, where they are integrated with existing knowledge. Slow oscillations in the cortex, brief bursts of activity known as spindles and sharp electrical ripples in the hippocampus appear to be coordinated in time, and many researchers believe this coordination is the mechanism that carries information from one region to the other. The role of rapid eye movement (REM) sleep, the stage most closely associated with vivid dreaming, is more contested; some evidence links it to emotional memories and to the learning of motor skills, but the findings are inconsistent."],
 ["E","Perhaps the most striking experiments have attempted to manipulate consolidation directly. In one design, participants learn the locations of objects on a screen while a particular sound or smell is present. If the same cue is then presented quietly during slow-wave sleep, without waking them, their recall of the associated items tends to improve compared with items whose cues were not replayed. A team led by Dr Imogen Vance at the Halvorsen Sleep Institute reported that this technique, known as targeted memory reactivation, produced gains of around ten per cent. Such results are often cited as the strongest evidence that sleep does more than passively protect memories from disruption."],
 ["F","Nevertheless, a note of caution is warranted. Several large replication attempts have found effects considerably smaller than those reported in the original studies, which typically involved fewer than thirty participants. Moreover, most laboratory tasks bear little resemblance to the kinds of learning that occupy students or workers, and a ten per cent improvement in remembering the position of cards on a screen does not necessarily translate into better examination results. It is also worth noting that much of the replay research has been conducted on rats, and the extent to which human sleep operates in the same way can only be inferred indirectly, through scalp recordings and brain imaging."],
 ["G","None of this means that the practical advice usually drawn from the research is wrong. Losing sleep before learning appears to impair the ability to form new memories, and losing it afterwards seems to weaken their retention; on both counts the evidence is reasonably consistent. What is less certain is the more ambitious claim, sometimes made in popular books, that sleep can be engineered to boost learning on demand. For the present, the most defensible conclusion may be a modest one: sleep is not a luxury that competes with study, but a stage of the learning process in its own right."]
 ],
 groups:[
 {qtype:"Matching Headings", instr:"The passage has seven paragraphs, A-G. Choose the correct heading for paragraphs B-F from the list of headings below.", options:["i  A design flaw that early findings could not overcome","ii  Direct observation of the brain rehearsing experience","iii  How activity in different brain regions may be synchronised","iv  Efforts to strengthen memories while people sleep","v  Grounds for questioning the size and relevance of the results","vi  Why dreaming is essential for emotional well-being","vii  The advantages of studying animals rather than humans","viii  The effect of sounds and smells on the quality of sleep"], optKey:"roman", items:[
  {q:"Paragraph B", a:"i", ev:"this objection proved difficult to answer", ex:"Paragraph B describes the early sleep-versus-wake studies and the 'serious weakness in the design' (reduced interference) that could not be answered for decades. It is about a flaw, not simply about early results."},
  {q:"Paragraph C", a:"ii", ev:"the sleeping brain was rehearsing the day's experiences", ex:"The key idea is 'replay': recordings show the same cell sequences during sleep, i.e. the brain rehearsing experience. Rodents are only the subjects, so vii is a trap."},
  {q:"Paragraph D", a:"iii", ev:"appear to be coordinated in time", ex:"The central point is the coordination of oscillations, spindles and ripples that may move information from hippocampus to cortex. REM and dreaming are mentioned only briefly and the findings are called 'inconsistent', so vi is wrong."},
  {q:"Paragraph E", a:"iv", ev:"have attempted to manipulate consolidation directly", ex:"Targeted memory reactivation is an attempt to influence (strengthen) memory during sleep. Sounds and smells are tools of the experiment, not the topic, so viii is a distractor."},
  {q:"Paragraph F", a:"v", ev:"effects considerably smaller than those reported in the original studies", ex:"F lists reasons for caution: small samples, artificial tasks and reliance on rats. It does not praise animal research (vii); it treats it as a limitation."}
 ]},
 {qtype:"True/False/Not Given", instr:"Do the following statements agree with the information given in the passage? Choose TRUE, FALSE or NOT GIVEN.", options:["TRUE","FALSE","NOT GIVEN"], items:[
  {q:"In certain studies, the quantity of replay observed in rodents was linked to how well they performed later.", a:"TRUE", ev:"the amount of replay recorded in some studies predicted how well the animals performed the following day", ex:"'Predicted how well the animals performed' = linked to later performance; 'some studies' matches 'certain studies'."},
  {q:"The sequences replayed during sleep lasted longer than the original experiences.", a:"FALSE", ev:"often compressed into a fraction of their original duration", ex:"'Compressed into a fraction' means shorter, the opposite of 'lasted longer'."},
  {q:"Slow-wave sleep is concentrated in the final hours of the night.", a:"FALSE", ev:"the deep stage that dominates the first part of the night", ex:"The passage places slow-wave sleep in the first part of the night, contradicting 'final hours'."},
  {q:"Researchers broadly agree that REM sleep plays no part in learning physical skills.", a:"FALSE", ev:"some evidence links it to emotional memories and to the learning of motor skills, but the findings are inconsistent", ex:"There is some evidence linking REM to motor skills and the role is 'contested', so there is no agreement that it plays no part."},
  {q:"Targeted memory reactivation has been used to treat people with memory disorders.", a:"NOT GIVEN", ev:"this technique, known as targeted memory reactivation, produced gains of around ten per cent", ex:"Only laboratory gains in healthy participants are reported. Clinical treatment is never mentioned, so the answer is NOT GIVEN."},
  {q:"The early cueing experiments generally relied on relatively small groups of participants.", a:"TRUE", ev:"which typically involved fewer than thirty participants", ex:"'Fewer than thirty participants' is a small sample; 'typically' matches 'generally'."}
 ]},
 {qtype:"Sentence Completion", instr:"Complete the sentences below. Write NO MORE THAN TWO WORDS from the passage for each answer.", limit:2, items:[
  {q:"In one widely accepted model, the hippocampus functions as a ___ for newly formed memories before they reach the cortex.", a:["temporary store"], ev:"the hippocampus acts as a temporary store", ex:"'Functions as' paraphrases 'acts as'; the memories are later 'transferred to the cortex'."},
  {q:"Knowledge of how human sleep works depends on indirect evidence from recordings taken at the scalp and from ___.", a:["brain imaging"], ev:"through scalp recordings and brain imaging", ex:"The two indirect sources are scalp recordings and brain imaging; the gap needs the second."},
  {q:"The writer concludes that sleep is best viewed not as a rival to study but as a ___ of learning.", a:["stage"], ev:"a stage of the learning process in its own right", ex:"'Not a luxury that competes with study' is paraphrased as 'not a rival to study'; the answer is 'stage'."}
 ]}
 ]
},
{
 id:"R70-02", title:"The Garden City and Its Inheritors", category:"Urban planning", band:7, mock:null, mins:20,
 paras:[
 ["A","Few ideas in the history of town planning have travelled as far, or been as frequently misunderstood, as the garden city. Proposed by the English reformer Ebenezer Howard at the end of the nineteenth century, it was conceived as a response to two problems that seemed, to many of his contemporaries, to be pulling in opposite directions: the overcrowding and squalor of industrial cities, and the depopulation and economic decline of the countryside. Howard's solution was not to choose between town and country but to combine them, creating new settlements that would offer the employment and culture of the former alongside the fresh air and open space of the latter."],
 ["B","It is easy to forget how radical the proposal was. Howard envisaged a town of limited size – around 32,000 people – surrounded by a permanent belt of farmland that would prevent it from sprawling outwards. When the population reached its limit, growth would continue not by expansion but by founding a new town beyond the belt, connected to its neighbours by rail. More unusual still was his approach to land. The entire site would be bought at agricultural prices and held in trust on behalf of the community, so that the rise in land values produced by development would flow back to residents in the form of lower rents and public services rather than into the pockets of private landlords."],
 ["C","The first experiment, begun in Hertfordshire in the early years of the twentieth century, proved that the idea could be built, though not quite in the form its author intended. Financing was a persistent difficulty: investors were reluctant to accept the limited returns the scheme offered, and compromises were made to attract industry and residents. The physical character of the town, with its low-density cottages, generous gardens and tree-lined roads, was widely admired and imitated. The economic model, by contrast, was diluted almost from the outset, and the cooperative ownership that Howard regarded as the heart of his plan was only partly realised."],
 ["D","This divergence between form and substance shaped the idea's subsequent legacy. Across Europe, North America and beyond, the label 'garden city' was attached to developments that borrowed the curving streets and green verges while ignoring the commitment to local employment and shared land ownership. Many became, in effect, commuter suburbs for wealthier households – precisely the kind of dormitory settlement Howard had hoped to avoid. Critics have argued, with some justice, that the garden city thereby helped to legitimise the low-density sprawl that later planners would spend decades trying to contain."],
 ["E","Yet to judge the idea solely by its imitators would be unfair. The green belts that now encircle many cities owe a clear intellectual debt to Howard's agricultural ring, and the large programmes of new towns built in several countries after the Second World War drew directly on his principle of planned, self-sufficient communities. A study by the urban historian Dr Tomasz Wren of twelve post-war new towns found that those which retained public ownership of their land were consistently better able to finance parks, community buildings and local transport than those that sold it to private developers. Wren is careful to note that his sample was small and that other factors, such as the strength of local industry, also played a part, but the pattern is at least consistent with Howard's central economic argument."],
 ["F","Interest in the garden city has revived in recent years, partly because the housing shortages facing many countries have prompted governments to consider building entire new settlements rather than adding piecemeal to existing ones. Some of these proposals invoke Howard's name with enthusiasm. It would be naïve, however, to assume that the label guarantees the substance. The true test of any new 'garden city' should surely be not whether it has trees and gardens – almost every modern development claims those – but whether it captures the increase in land value for the benefit of the people who live there. On that measure, few contemporary schemes would qualify."],
 ["G","There is also a case for asking whether the model suits an age of high car ownership and remote working. Howard's towns were designed around walking and the railway; a settlement of 32,000 surrounded by farmland may, today, simply generate long car journeys to larger cities. Advocates respond that this is an argument for better public transport rather than against the principle itself. Whatever position one takes, the garden city remains less a blueprint to be copied than a set of questions about who should benefit when land is developed – questions that are as pressing now as they were when Howard first posed them."]
 ],
 groups:[
 {qtype:"Matching Information", instr:"The passage has seven paragraphs, A-G. Which paragraph contains the following information? You may use any letter more than once.", options:["A","B","C","D","E","F","G"], items:[
  {q:"a reference to the original plan being modified because of problems raising money", a:"C", ev:"Financing was a persistent difficulty", ex:"C explains that investors disliked the limited returns, so 'compromises were made' – the plan was modified for financial reasons."},
  {q:"evidence that the way land was owned affected the provision of public facilities", a:"E", ev:"those which retained public ownership of their land were consistently better able to finance parks", ex:"Wren's study links public land ownership to the ability to pay for parks and community buildings. B describes Howard's land idea but gives no evidence of results."},
  {q:"a description of how a settlement was supposed to grow once it reached its maximum size", a:"B", ev:"growth would continue not by expansion but by founding a new town beyond the belt", ex:"B explains that a full town would grow by founding a new town beyond the farmland belt."},
  {q:"a concern that the concept may be poorly suited to present-day travel habits", a:"G", ev:"may, today, simply generate long car journeys to larger cities", ex:"G questions whether a small town fits an age of car ownership, since it may create long car journeys."},
  {q:"an account of the two difficulties the concept was originally intended to solve", a:"A", ev:"the overcrowding and squalor of industrial cities, and the depopulation and economic decline of the countryside", ex:"A names the two problems: crowded industrial cities and a declining countryside."}
 ]},
 {qtype:"Yes/No/Not Given", instr:"Do the following statements agree with the views of the writer? Choose YES, NO or NOT GIVEN.", options:["YES","NO","NOT GIVEN"], items:[
  {q:"The garden city proposal was bolder than people now tend to recognise.", a:"YES", ev:"It is easy to forget how radical the proposal was.", ex:"'Easy to forget how radical' means people underestimate how bold it was – the writer agrees with the statement."},
  {q:"The physical layout of the first garden city was its least successful aspect.", a:"NO", ev:"was widely admired and imitated", ex:"The writer contrasts the admired physical character with the economic model, which was 'diluted'. The layout was the more successful part."},
  {q:"The claim that garden cities encouraged suburban sprawl has no basis.", a:"NO", ev:"Critics have argued, with some justice", ex:"'With some justice' shows the writer thinks the criticism is partly valid, so it is not baseless."},
  {q:"Post-war new towns were more successful overall than Howard's first experiment.", a:"NOT GIVEN", ev:"drew directly on his principle of planned, self-sufficient communities", ex:"The writer says new towns were influenced by Howard but never compares their overall success with the first experiment."},
  {q:"Most recent schemes using the garden city name fail to meet its most important condition.", a:"YES", ev:"On that measure, few contemporary schemes would qualify.", ex:"The 'true test' is capturing land value for residents; 'few would qualify' means most fail it."}
 ]},
 {qtype:"Summary Completion", instr:"Complete the summary below. Write NO MORE THAN TWO WORDS from the passage for each answer.", limit:2, items:[
  {q:"Howard proposed that each town should be enclosed by a permanent ring of ___ to stop it spreading outwards.", a:["farmland"], ev:"surrounded by a permanent belt of farmland", ex:"'Ring' paraphrases 'belt'; 'spreading outwards' paraphrases 'sprawling outwards'."},
  {q:"The land would be purchased cheaply, at ___ prices,", a:["agricultural"], ev:"bought at agricultural prices", ex:"The site was to be bought at agricultural prices, which were low because the land was not yet developed."},
  {q:"and kept in ___ for the community, so that rising values would benefit residents.", a:["trust"], ev:"held in trust on behalf of the community", ex:"'Kept in trust' = 'held in trust'."},
  {q:"However, many later developments that copied only the appearance became ___ for the well-off.", a:["commuter suburbs","suburbs"], ev:"Many became, in effect, commuter suburbs for wealthier households", ex:"'For the well-off' paraphrases 'for wealthier households'. 'Dormitory settlement' describes the same idea but is not what these developments 'became' in the text, and it would not fit grammatically after a plural subject."}
 ]}
 ]
},
{
 id:"R70-03", title:"Running on Empty? The Decision Fatigue Debate", category:"Psychology", band:7, mock:null, mins:20,
 paras:[
 ["A","The notion that making choices wears us out has an intuitive appeal that few psychological theories can match. Most people have experienced the peculiar exhaustion that follows a day of decisions – choosing a supplier, approving a budget, deciding what to cook – and many have noticed that their judgement seems to deteriorate as the day goes on. The term 'decision fatigue' captures this experience neatly, and it has migrated from academic journals into management books, where it is used to justify everything from simplified wardrobes to the scheduling of important meetings early in the morning. Whether the phenomenon exists in the form popularly described, however, has become one of the more contentious questions in contemporary psychology."],
 ["B","The idea grew out of a broader theory proposed by researchers including Professor Hannah Lindqvist, who argued that self-control draws on a limited mental resource that is depleted by use. In a typical early experiment, participants who had first been asked to resist a tempting snack, or to make a long series of consumer choices, subsequently gave up sooner on an unsolvable puzzle than those who had not. Lindqvist interpreted such findings as evidence that decision-making and self-control share a common 'fuel', and that exhausting it in one activity leaves less available for the next. For a decade or so the theory accumulated hundreds of supporting studies and was regarded by many as one of the discipline's most robust discoveries."],
 ["C","Real-world data seemed to point in the same direction. One widely publicised analysis examined over a thousand rulings made by a panel reviewing applications for early release from prison. The proportion of favourable decisions was high at the start of each session, declined steadily, and then recovered after the panel's food breaks. The pattern was interpreted as a vivid demonstration that tired decision-makers fall back on the safest option – in this case, refusing the application. Professor Daniel Ferreira, an economist who later re-examined the data, has questioned this conclusion, noting that cases were not heard in random order: prisoners without legal representation, whose applications were less likely to succeed, tended to be scheduled at the end of each session. Ferreira does not deny that fatigue may have played some role, but he argues that the data cannot distinguish it from this simpler explanation."],
 ["D","The more fundamental challenge came from attempts to reproduce the laboratory findings. A coordinated project involving more than twenty laboratories, led by Dr Marcus Obi, applied a standardised version of a classic depletion task to over two thousand participants. Its design had been agreed with several of the theory's original proponents before any data were collected, a precaution intended to forestall later objections. The effect it detected was close to zero. Obi has been careful not to claim that the phenomenon is entirely illusory; his position is rather that the original effect sizes were inflated by small samples and by a publication system that favoured positive results. Supporters of the theory countered that the chosen task was too mild to deplete anyone, a criticism Obi regards as unfalsifiable, since any failure can be attributed after the event to an insufficiently demanding procedure."],
 ["E","A third position, associated with Dr Selin Arkan, accepts that people often perform worse after demanding mental work but rejects the idea of a depleting resource. In her account, what changes is not capacity but motivation: after a period of effort, the mind shifts its priorities towards rest or towards activities that feel more rewarding. Arkan points to studies in which participants who had been told that willpower is unlimited showed no decline at all, and to evidence that small incentives can restore performance almost immediately. If a fuel were genuinely exhausted, she argues, a change of belief or a modest reward should make little difference. Critics respond that motivation and capacity may be hard to separate in practice, since the feeling of being drained could itself be the signal that a resource is running low. Arkan accepts that the distinction is subtle but maintains that it has testable consequences."],
 ["F","It would be premature to declare a winner. The resource model, at least in its original form, has clearly been weakened, and its more confident applications deserve scepticism. Yet the motivational account is itself still being tested, and the everyday observation that people choose less carefully when tired is not refuted merely because a particular laboratory task fails to capture it. For organisations, the sensible lesson may be less dramatic than the popular literature implies: reducing trivial choices and spacing out important ones is probably harmless and may be helpful, but it should be recommended as prudent practice rather than as a proven scientific law."]
 ],
 groups:[
 {qtype:"Matching Features", instr:"Look at the following statements and the list of researchers below. Match each statement with the correct researcher, A-D. You may use any letter more than once.", options:["A  Hannah Lindqvist","B  Daniel Ferreira","C  Marcus Obi","D  Selin Arkan"], optKey:"letter", items:[
  {q:"suggests that a different factor may account for a pattern observed in real-world decisions", a:"B", ev:"cases were not heard in random order", ex:"Ferreira argues that the order of cases (unrepresented prisoners heard last), not fatigue, may explain the decline in favourable rulings."},
  {q:"claims that poorer performance reflects altered priorities rather than reduced capacity", a:"D", ev:"what changes is not capacity but motivation", ex:"Arkan's account replaces a depleted resource with a shift in motivation and priorities."},
  {q:"proposed that choosing and resisting temptation depend on the same limited supply", a:"A", ev:"decision-making and self-control share a common 'fuel'", ex:"Lindqvist's 'common fuel' is the shared limited resource."},
  {q:"rejects a defence that could be used to dismiss any negative finding", a:"C", ev:"a criticism Obi regards as unfalsifiable", ex:"Obi says the 'task too mild' reply can explain away any failure after the event, so it cannot be tested."},
  {q:"believes early results were exaggerated partly because of the way research is published", a:"C", ev:"a publication system that favoured positive results", ex:"Obi blames inflated effects on small samples and publication bias. Ferreira also criticises earlier work, but on different grounds."}
 ]},
 {qtype:"Yes/No/Not Given", instr:"Do the following statements agree with the claims of the writer? Choose YES, NO or NOT GIVEN.", options:["YES","NO","NOT GIVEN"], items:[
  {q:"The popularity of the idea of decision fatigue owes much to how closely it matches personal experience.", a:"YES", ev:"has an intuitive appeal that few psychological theories can match", ex:"The writer stresses its 'intuitive appeal' and the fact that 'most people have experienced' the exhaustion – the popularity comes from familiarity."},
  {q:"The resource model has emerged from recent challenges largely unharmed.", a:"NO", ev:"has clearly been weakened", ex:"'Clearly been weakened' contradicts 'largely unharmed'."},
  {q:"Arkan's motivational explanation has now been firmly established.", a:"NO", ev:"the motivational account is itself still being tested", ex:"The writer says it is 'still being tested', so it is not yet established."},
  {q:"Management books have done serious damage by promoting the concept of decision fatigue.", a:"NOT GIVEN", ev:"it is used to justify everything from simplified wardrobes to the scheduling of important meetings early in the morning", ex:"The writer describes how management books use the term and later calls such advice 'probably harmless', but never claims the books caused serious damage. Do not over-read the slightly ironic tone."}
 ]},
 {qtype:"Multiple Choice", instr:"Choose the correct letter, A, B, C or D.", items:[
  {q:"The analysis of release decisions described in paragraph C was originally taken to show that", opts:["the panel was prejudiced against prisoners without lawyers.","exhausted decision-makers tend to choose the least risky option.","the panel's breaks were too short to be effective.","favourable rulings became more frequent as sessions went on."], a:"B", ev:"tired decision-makers fall back on the safest option", ex:"'Fall back on the safest option' = choose the least risky option. A is Ferreira's later point about scheduling, not the original interpretation; D reverses the pattern."},
  {q:"What does the writer indicate about the replication project led by Obi?", opts:["It proved that decision fatigue does not exist.","Its conclusions were later withdrawn by Obi.","It found virtually no effect, yet Obi does not dismiss the phenomenon entirely.","It used a more demanding task than the original studies."], a:"C", ev:"Obi has been careful not to claim that the phenomenon is entirely illusory", ex:"The effect was 'close to zero', but Obi avoids saying it is 'entirely illusory'. A overstates; D is the opposite of the critics' complaint that the task was too mild."},
  {q:"Arkan regards the effect of small rewards on performance as evidence that", opts:["willpower can be increased through training.","the idea of a depleted resource is probably mistaken.","participants in earlier studies were not genuinely tired.","people's beliefs about willpower are usually accurate."], a:"B", ev:"If a fuel were genuinely exhausted, she argues, a change of belief or a modest reward should make little difference.", ex:"Because a reward restores performance, Arkan infers that no fuel has really been used up – i.e. the resource model is likely wrong."},
  {q:"The writer's advice to organisations is best described as", opts:["an urgent call to adopt scientifically proven rules.","cautious guidance that should not be presented as established fact.","a complete rejection of the popular literature.","a recommendation to make all important decisions in the morning."], a:"B", ev:"it should be recommended as prudent practice rather than as a proven scientific law", ex:"The writer calls the measures 'probably harmless' and 'prudent practice', explicitly not 'a proven scientific law'. C is too strong: the writer does not reject the advice, only its overconfidence."}
 ]}
 ]
},
{
 id:"R70-04", title:"Nudging the Public", category:"Economics", band:7, mock:null, mins:20,
 paras:[
 ["A","For much of the twentieth century, governments seeking to change behaviour relied on a familiar set of instruments: laws that prohibited or required certain actions, taxes and subsidies that altered prices, and information campaigns that urged citizens to do better. Since the early years of this century, a fourth approach has attracted considerable attention. Drawing on research in behavioural economics, it holds that people's choices are shaped by the way options are presented – their 'choice architecture' – and that small, inexpensive changes to that architecture can steer behaviour without restricting freedom or significantly altering incentives. Such interventions have come to be known as nudges."],
 ["B","The intellectual foundation of the approach is a rejection of the assumption, central to traditional economics, that people consistently weigh costs and benefits before acting. Experimental work has documented a range of systematic departures from this ideal. People tend to stick with whatever option is pre-selected, give disproportionate weight to immediate rewards over future ones, and are strongly influenced by what they believe others are doing. Advocates of nudging argue that, since some form of choice architecture is unavoidable – a form must list options in some order, a canteen must display food somewhere – it is better to design it deliberately than to leave it to chance."],
 ["C","The most frequently cited success concerns retirement saving. Where employees must actively sign up for a workplace pension, many never get round to doing so, even when they say they intend to. When enrolment is made automatic, with workers free to leave the scheme if they wish, participation rates have in many cases risen dramatically. A similar logic underlies the use of social comparison in tax collection: letters informing late payers that most people in their area have already paid have, in several trials, produced measurable increases in prompt payment at almost no cost to the public purse. In both cases the intervention left the underlying choice unchanged; only the way it was framed or presented was altered."],
 ["D","Encouraged by such results, a number of governments established specialised units to apply behavioural insights across policy areas. One unit attached to a northern European finance ministry ran more than a hundred randomised trials in its first five years, covering matters as diverse as organ donation, household energy use and attendance at medical appointments. According to an internal review by its former director, Dr Leona Marsh, around a third of these interventions produced effects that were both statistically reliable and large enough to justify wider adoption. The remainder either had no detectable impact or produced changes too small to be worth the administrative effort of scaling them up."],
 ["E","Critics, however, have raised doubts on several fronts. A recent analysis by the economist Professor Arturo Benn suggests that the average effect of nudges reported in academic journals is substantially larger than that found in trials run by government units themselves, a gap he attributes to the tendency of journals to publish striking results and overlook disappointing ones. If he is right, the typical nudge may achieve considerably less than its reputation suggests. Others contend that the more modest effects are not a failure but a realistic reflection of what light-touch measures can accomplish, and that even a small improvement may be worthwhile when it costs almost nothing."],
 ["F","A second line of criticism is ethical rather than empirical. Because nudges often work by exploiting habits and biases of which people are unaware, some philosophers argue that they are manipulative, bypassing the rational deliberation that respect for citizens would seem to require. Defenders reply that a nudge is acceptable provided it is transparent and easy to resist, and that the alternative – leaving choice architecture to commercial firms with their own interests – is hardly more respectful. The line between a legitimate nudge and manipulation is nonetheless difficult to draw with precision, and public trust may suffer if citizens come to feel that they are being quietly steered."],
 ["G","Perhaps the most serious concern is that the popularity of nudging may divert attention from problems that require more forceful action. Encouraging households to reduce energy consumption through comparisons with their neighbours is cheap and politically painless; restructuring energy prices or tightening building regulations is neither. There is a risk, as some observers have put it, of treating the symptoms of policy failure while leaving its causes untouched. Seen in this light, nudges are probably best understood not as an alternative to conventional policy but as a modest complement to it – useful at the margins, and most effective when combined with the very instruments they were once expected to replace."]
 ],
 groups:[
 {qtype:"Matching Headings", instr:"The passage has seven paragraphs, A-G. Choose the correct heading for paragraphs B, C, E, F and G from the list of headings below.", options:["i  Doubts about how much nudges really achieve","ii  A challenge to a long-held view of human reasoning","iii  Two cases where minor changes brought major gains","iv  Is it fair to influence people in this way?","v  The danger of neglecting tougher measures","vi  Why governments closed their behavioural units","vii  The high cost of running randomised trials","viii  How businesses use nudges to increase profits"], optKey:"roman", items:[
  {q:"Paragraph B", a:"ii", ev:"a rejection of the assumption, central to traditional economics, that people consistently weigh costs and benefits before acting", ex:"B questions the traditional economic idea that people reason carefully about costs and benefits. The examples of biases support this main point."},
  {q:"Paragraph C", a:"iii", ev:"participation rates have in many cases risen dramatically", ex:"C gives two successes – automatic pension enrolment and tax letters – where small changes had large effects."},
  {q:"Paragraph E", a:"i", ev:"the typical nudge may achieve considerably less than its reputation suggests", ex:"E is about whether reported effects are exaggerated. The low cost of nudges is mentioned, but not the cost of trials, so vii is a trap."},
  {q:"Paragraph F", a:"iv", ev:"A second line of criticism is ethical rather than empirical.", ex:"F debates whether nudging is manipulative – an ethical question of fairness. Commercial firms appear only as part of the defenders' reply, so viii is a distractor."},
  {q:"Paragraph G", a:"v", ev:"may divert attention from problems that require more forceful action", ex:"G warns that nudges may distract from stronger action such as price reform or regulation. Nothing says units were closed (vi)."}
 ]},
 {qtype:"Note Completion", instr:"Complete the notes below. Write NO MORE THAN TWO WORDS from the passage for each answer.", limit:2, items:[
  {q:"Traditional policy tools: laws, taxes and subsidies, and ___ campaigns", a:["information"], ev:"information campaigns that urged citizens to do better", ex:"The third traditional instrument is information campaigns."},
  {q:"Typical bias: people keep the option that is ___", a:["pre-selected"], ev:"stick with whatever option is pre-selected", ex:"'Keep' paraphrases 'stick with'. A hyphenated word counts as one word."},
  {q:"Pensions: enrolment made ___, though workers may leave", a:["automatic"], ev:"When enrolment is made automatic", ex:"Automatic enrolment with freedom to opt out raised participation."},
  {q:"Tax collection: letters use ___ to encourage prompt payment", a:["social comparison"], ev:"the use of social comparison in tax collection", ex:"Telling late payers that neighbours have paid is a form of social comparison."}
 ]},
 {qtype:"Short Answer", instr:"Answer the questions below. Write NO MORE THAN THREE WORDS from the passage for each answer.", limit:3, items:[
  {q:"According to Dr Marsh, what proportion of the unit's interventions deserved to be used more widely?", a:["around a third","a third"], ev:"around a third of these interventions", ex:"'Deserved to be used more widely' paraphrases 'large enough to justify wider adoption'."},
  {q:"What do some philosophers say nudges bypass?", a:["rational deliberation"], ev:"bypassing the rational deliberation", ex:"The philosophers' objection is that nudges bypass rational deliberation, which respect for citizens requires."},
  {q:"Who, according to defenders, would otherwise shape the way choices are presented?", a:["commercial firms"], ev:"leaving choice architecture to commercial firms with their own interests", ex:"Defenders argue that if governments do not design choice architecture, commercial firms will."},
  {q:"What does the writer believe nudges should be in relation to conventional policy?", a:["a modest complement","modest complement","complement"], ev:"a modest complement to it", ex:"The writer rejects the idea of nudges as an 'alternative' and calls them 'a modest complement'."}
 ]}
 ]
},
{
 id:"R70-05", title:"Reading Time in the Ground", category:"Archaeology", band:7, mock:null, mins:20,
 paras:[
 ["A","Ask an archaeologist how old an object is and the answer is likely to come with qualifications. Dating is not a single technique but a family of methods, each with its own assumptions, limitations and margins of error, and the most reliable conclusions usually emerge when several of them point in the same direction. A useful distinction is commonly drawn between relative dating, which establishes whether one object or layer is older or younger than another, and absolute dating, which attempts to assign an age in years. For most of the discipline's history only the first was available, and it remains far more important than its modest name implies."],
 ["B","The foundation of relative dating is stratigraphy, the study of the layers of soil and debris that accumulate on a site over time. Under normal conditions, lower layers were deposited before those above them, so objects found deeper are generally older. The qualification 'generally' matters. Burrowing animals, the digging of pits and foundations, and later disturbance by ploughing can move material between layers, and an excavator who fails to recognise such intrusions may draw entirely misleading conclusions. Careful recording of the precise position of every find is therefore not a bureaucratic formality but the evidence on which any later interpretation depends."],
 ["C","A second relative method relies on the observation that the styles of manufactured objects change over time in broadly predictable ways. By arranging pottery, tools or ornaments into sequences according to their form and decoration – a procedure known as seriation – researchers can estimate the order in which sites were occupied. The method works best where a particular style rose in popularity, peaked and declined, leaving a characteristic pattern in the proportions found at different sites. Its weakness is that styles do not change at the same pace everywhere, and an old-fashioned design may persist in a remote area long after it has been abandoned elsewhere."],
 ["D","The development of radiocarbon dating in the mid-twentieth century transformed the field by offering, for the first time, a means of measuring age directly in organic remains such as wood, bone, seeds and charcoal. Living organisms absorb carbon from their environment, including a small proportion of a radioactive form, carbon-14. When an organism dies, it stops taking in carbon, and the radioactive form decays at a known rate, halving roughly every 5,700 years. By measuring how much remains, scientists can estimate how long ago death occurred. Beyond about 50,000 years, too little is left to measure reliably, which confines the method to relatively recent periods of the human past."],
 ["E","Early radiocarbon dates proved to be somewhat inaccurate because the technique assumed that the proportion of carbon-14 in the atmosphere had been constant. It has not. Dates must therefore be calibrated against an independent record, and the most important such record comes from tree rings. Because trees in many regions add one ring per year, and because the width of the rings varies with climate, the patterns from living trees can be matched with those in older timber preserved in buildings, bogs and riverbeds. In this way overlapping sequences extending back thousands of years have been assembled. Dendrochronology, as the study of tree rings is called, can sometimes date a piece of wood to the exact year in which the tree was felled – a level of precision no other method can match."],
 ["F","For materials containing no carbon, other approaches are needed. Thermoluminescence exploits the fact that certain minerals gradually accumulate energy from natural background radiation, energy that is released as light when they are heated. Firing pottery resets this 'clock' to zero, so measuring the light emitted when a fragment is reheated in the laboratory indicates how long it has been since it was last fired. The method is valuable for ceramics and burnt stone, but its margins of error, often around ten per cent of the age, are considerably wider than those of radiocarbon. Related techniques, which measure when buried sediment was last exposed to sunlight, have extended this approach to soils and windblown sand."],
 ["G","None of these methods can be applied mechanically. A radiocarbon date reveals when a tree died, not when its timber was used; a beam reused from an older building may suggest a date centuries too early. Similarly, a coin found in a grave indicates only that the burial took place after the coin was made, not how long afterwards. Interpreting dates thus demands an understanding of how objects entered the ground in the first place. Arguably, it is this interpretive judgement, rather than the sophistication of laboratory equipment, that distinguishes good archaeological dating from bad."]
 ],
 groups:[
 {qtype:"True/False/Not Given", instr:"Do the following statements agree with the information given in the passage? Choose TRUE, FALSE or NOT GIVEN.", options:["TRUE","FALSE","NOT GIVEN"], items:[
  {q:"Relative dating is of less value than its name might lead people to expect.", a:"FALSE", ev:"it remains far more important than its modest name implies", ex:"The text says relative dating is MORE important than its 'modest name' suggests – the opposite of the statement."},
  {q:"Animals can be responsible for moving objects from one layer to another.", a:"TRUE", ev:"Burrowing animals, the digging of pits and foundations, and later disturbance by ploughing can move material between layers", ex:"Burrowing animals are listed among the causes of material moving between layers."},
  {q:"Seriation was originally devised as a way of studying pottery.", a:"NOT GIVEN", ev:"By arranging pottery, tools or ornaments into sequences", ex:"Pottery is one example of material used, but the passage says nothing about where or for what the method was first developed."},
  {q:"Radiocarbon dating cannot reliably be used for remains older than about 50,000 years.", a:"TRUE", ev:"Beyond about 50,000 years, too little is left to measure reliably", ex:"Too little carbon-14 remains after about 50,000 years, so the method stops being reliable."},
  {q:"Trees in a given region produce rings of identical width every year.", a:"FALSE", ev:"the width of the rings varies with climate", ex:"Ring width varies with climate; this variation is exactly what allows sequences to be matched."}
 ]},
 {qtype:"Table Completion", instr:"Complete the table below. Write NO MORE THAN TWO WORDS from the passage for each answer.", limit:2, table:{head:["Method","Type","Applied to","Main limitation"], rows:[["Stratigraphy","relative","layers on a site","disturbance by animals, pits or [1]"],["Seriation","relative","[2] objects, e.g. pottery","styles change at a different [3] in different areas"],["Radiocarbon","absolute","[4] remains","must be calibrated"],["Thermoluminescence","absolute","ceramics and [5]","wide margins of error"]]}, items:[
  {q:"Stratigraphy – limitation: disturbance by animals, pits or ___", a:["ploughing"], ev:"later disturbance by ploughing", ex:"Ploughing is the third source of disturbance named in paragraph B."},
  {q:"Seriation – applied to: ___ objects", a:["manufactured"], ev:"the styles of manufactured objects change over time", ex:"Seriation relies on changes in the style of manufactured objects such as pottery, tools and ornaments."},
  {q:"Seriation – limitation: styles change at a different ___", a:["pace"], ev:"styles do not change at the same pace everywhere", ex:"'Not at the same pace everywhere' = a different pace in different areas."},
  {q:"Radiocarbon – applied to: ___ remains", a:["organic"], ev:"measuring age directly in organic remains", ex:"Radiocarbon works on organic remains (wood, bone, seeds, charcoal) because living things absorb carbon."},
  {q:"Thermoluminescence – applied to: ceramics and ___", a:["burnt stone"], ev:"valuable for ceramics and burnt stone", ex:"The method needs material that has been heated, such as fired ceramics and burnt stone."}
 ]},
 {qtype:"Multiple Choice", instr:"Choose the correct letter, A, B, C or D.", items:[
  {q:"Why does the writer stress the importance of recording exactly where each find is located?", opts:["It is a legal requirement on most excavations.","Any later interpretation of the site relies on it.","It allows excavation to proceed more quickly.","It prevents burrowing animals from disturbing the site."], a:"B", ev:"the evidence on which any later interpretation depends", ex:"The writer says recording is 'not a bureaucratic formality' (so not A) but the evidence that later interpretation depends on."},
  {q:"Radiocarbon dates need to be calibrated because", opts:["carbon-14 decays at an unpredictable rate.","the level of carbon-14 in the atmosphere has not been constant.","organic remains continue to absorb carbon after death.","many tree-ring sequences are incomplete."], a:"B", ev:"assumed that the proportion of carbon-14 in the atmosphere had been constant", ex:"The early assumption of a constant atmospheric level was wrong ('It has not'), so calibration is needed. A contradicts 'a known rate'; C contradicts 'stops taking in carbon'."},
  {q:"Which advantage of dendrochronology does the writer emphasise?", opts:["It can be used on any type of material.","It can occasionally identify a single calendar year.","It is cheaper than other absolute methods.","It reaches further back in time than radiocarbon."], a:"B", ev:"a level of precision no other method can match", ex:"Dating wood 'to the exact year' is unmatched precision. The passage does not discuss cost or compare time ranges."},
  {q:"The example of a reused beam is given to show that", opts:["timber is unsuitable for radiocarbon dating.","a date may relate to an earlier event than the one being investigated.","coins provide more accurate dates than wood.","older buildings were constructed with better timber."], a:"B", ev:"a beam reused from an older building may suggest a date centuries too early", ex:"The date records when the tree died, which may be long before the beam was used in the building under study."}
 ]}
 ]
},
{
 id:"R70-06", title:"Water from the Sea", category:"Technology", band:7, mock:null, mins:20,
 paras:[
 ["A","To a world in which freshwater supplies are under growing strain, the oceans present an obvious temptation. Roughly 97 per cent of the planet's water is salt water, and for coastal cities facing drought, rising populations and depleted aquifers, the prospect of turning seawater into drinking water can appear to offer something close to an unlimited supply. Desalination is no longer an experimental technology: thousands of plants now operate worldwide, and in some arid countries they provide the majority of municipal water. Yet the enthusiasm with which it is sometimes promoted deserves closer scrutiny, for the technology's costs – financial, energetic and environmental – are real, even if they have fallen substantially."],
 ["B","The earliest large-scale plants relied on distillation: seawater was heated until it evaporated, and the vapour was condensed as fresh water, leaving the salt behind. Although effective, thermal methods consume enormous amounts of energy, and they were viable mainly in regions where fuel was cheap and abundant. Since the late twentieth century they have been largely overtaken by reverse osmosis, a process that uses pressure rather than heat. Seawater is forced through semi-permeable membranes whose microscopic pores allow water molecules to pass while blocking dissolved salts. Because no change of state is involved, the energy needed is far lower, although the membranes themselves are costly and must be replaced every few years."],
 ["C","In a typical reverse osmosis plant, the process begins at the intake, where seawater is drawn from the ocean, often through screens designed to exclude fish and debris. The water then undergoes pre-treatment, in which suspended particles and organic matter are removed by filtration, since even small quantities of such material can clog the delicate membranes. Next, high-pressure pumps push the water through the membrane units, separating it into two streams: fresh water and a concentrated salty residue known as brine. Finally, because water stripped of almost all its minerals is corrosive to pipes and tastes flat, the product undergoes post-treatment, in which minerals are added back before it enters the distribution network."],
 ["D","The cost of the resulting water has declined markedly over recent decades, thanks largely to improved membranes and to devices that recover energy from the high-pressure brine stream and reuse it to pressurise incoming seawater. According to Dr Farida Okonjo of the Coastal Water Research Group, modern plants use less than half the energy per cubic metre that comparable facilities required in the 1990s. Even so, desalinated water typically remains several times more expensive than water drawn from rivers or underground sources, and the large capital investment required means that plants built during droughts can become financial burdens when rainfall returns and demand for their output falls. Several such facilities have spent long periods operating well below capacity, while their owners continued to repay the loans used to build them."],
 ["E","Energy consumption raises a further difficulty. If a plant draws its power from fossil fuels, it adds to the very emissions that contribute to the changing rainfall patterns which prompted its construction. Some newer facilities are linked to solar or wind generation, and this is clearly a welcome development, but intermittent renewable supply sits awkwardly with plants that operate most efficiently when running continuously. Storage can bridge the gap only at additional expense. Claims that desalination can easily be made carbon-neutral should therefore probably be treated with some caution."],
 ["F","The environmental consequences extend beyond energy. For every litre of fresh water produced, reverse osmosis plants typically discharge more than a litre of brine, roughly twice as salty as seawater and sometimes containing residues of the chemicals used in pre-treatment. Being denser than seawater, brine tends to sink and spread across the seabed, where it can harm organisms adapted to stable conditions. Well-designed outfalls that diffuse the brine rapidly can reduce this damage considerably, and research into extracting valuable minerals from brine may one day turn a waste product into a resource. At present, though, such recovery is rarely economic."],
 ["G","None of this suggests that desalination should be rejected. For some regions it is, quite simply, the only reliable source of additional supply, and its role is likely to grow. What the evidence does suggest is that it should be treated as one element in a broader strategy rather than as a substitute for reducing leakage, recycling wastewater and using water more efficiently – measures that are usually cheaper and less damaging. A litre of water saved, after all, is almost always less expensive than a litre produced from the sea. Policymakers who reach for desalination first, before these cheaper options have been exhausted, may find that they have solved a short-term shortage at a lasting price."]
 ],
 groups:[
 {qtype:"Flow-chart Completion", instr:"Complete the flow-chart below. Write NO MORE THAN TWO WORDS from the passage for each answer.", limit:2, flow:true, items:[
  {q:"Intake: seawater is drawn in through ___ that keep out fish and debris", a:["screens"], ev:"often through screens designed to exclude fish and debris", ex:"'Keep out' paraphrases 'exclude'; the device is screens."},
  {q:"___: particles and organic matter are filtered out to protect the membranes", a:["pre-treatment"], ev:"The water then undergoes pre-treatment", ex:"The second stage is pre-treatment, which stops material clogging the membranes."},
  {q:"High-pressure ___ force the water through membrane units", a:["pumps"], ev:"high-pressure pumps push the water through the membrane units", ex:"'Force' paraphrases 'push'."},
  {q:"Output is divided into fresh water and a salty residue called ___", a:["brine"], ev:"a concentrated salty residue known as brine", ex:"The second stream is brine."},
  {q:"Post-treatment: ___ are restored so the water is less corrosive and tastes better", a:["minerals"], ev:"minerals are added back before it enters the distribution network", ex:"'Restored' paraphrases 'added back'; without minerals the water is corrosive and flat."}
 ]},
 {qtype:"Yes/No/Not Given", instr:"Do the following statements agree with the views of the writer? Choose YES, NO or NOT GIVEN.", options:["YES","NO","NOT GIVEN"], items:[
  {q:"The advantages of desalination are sometimes overstated by those who promote it.", a:"YES", ev:"the enthusiasm with which it is sometimes promoted deserves closer scrutiny", ex:"Saying the enthusiasm 'deserves closer scrutiny' because costs are real implies that promoters overstate the benefits."},
  {q:"Thermal distillation was an unreliable way of producing fresh water.", a:"NO", ev:"Although effective, thermal methods consume enormous amounts of energy", ex:"The writer calls distillation 'effective'; its problem was energy use, not reliability."},
  {q:"Connecting desalination plants to renewable power is a positive step.", a:"YES", ev:"this is clearly a welcome development", ex:"'Clearly a welcome development' – despite the problem of intermittent supply mentioned afterwards."},
  {q:"Governments should avoid building desalination plants during droughts.", a:"NOT GIVEN", ev:"plants built during droughts can become financial burdens when rainfall returns", ex:"The writer notes a financial risk but does not say governments should avoid building them. Do not turn a description of a risk into a recommendation."},
  {q:"Cutting water waste is generally a cheaper option than desalination.", a:"YES", ev:"measures that are usually cheaper and less damaging", ex:"Reducing leakage and using water efficiently are 'usually cheaper'; the final sentence reinforces this."}
 ]},
 {qtype:"Matching Information", instr:"The passage has seven paragraphs, A-G. Which paragraph contains the following information? You may use any letter more than once.", options:["A","B","C","D","E","F","G"], items:[
  {q:"a comparison between the energy efficiency of current and earlier plants", a:"D", ev:"modern plants use less than half the energy per cubic metre", ex:"Okonjo compares modern plants with those of the 1990s. B also mentions energy, but compares methods, not periods."},
  {q:"a reason why desalination might make worse the problem it is intended to solve", a:"E", ev:"it adds to the very emissions that contribute to the changing rainfall patterns which prompted its construction", ex:"Fossil-fuelled plants add to emissions that alter rainfall – the cause of the water shortage itself."},
  {q:"an explanation of why a by-product tends to collect on the ocean floor", a:"F", ev:"Being denser than seawater, brine tends to sink and spread across the seabed", ex:"Brine is denser, so it sinks to the seabed (ocean floor)."},
  {q:"a figure indicating how much of the Earth's water is salty", a:"A", ev:"Roughly 97 per cent of the planet's water is salt water", ex:"The figure of 97 per cent appears in paragraph A."}
 ]}
 ]
}
];
