/* ===== READING BANK — band 6.0 practice sets (original material written for this app) ===== */
export const SETS = [
{
 id:"R60-01", title:"Building the Roads of Rome", category:"Archaeology", band:6, mock:null, mins:15,
 paras:[
 ["A","At its height, the Roman state was connected by tens of thousands of kilometres of roads, stretching from northern Britain to the deserts of North Africa. These roads allowed armies to move quickly, carried officials and messengers between cities, and made trade far easier than before. For archaeologists, the roads are also a valuable source of information, because the way they were planned and built reveals a great deal about Roman engineering, organisation and everyday life."],
 ["B","Before any digging began, the route had to be surveyed. Roman surveyors used a simple but effective instrument called a groma, which consisted of a vertical pole with two cross-pieces at the top. A weight hung from the end of each arm, and by lining up these hanging cords with marker posts placed further away, the surveyor could set out a perfectly straight line. Over longer distances, teams are thought to have used fires or smoke on high ground so that they could sight from one hilltop to the next."],
 ["C","The famous straightness of Roman roads is often exaggerated, however. Engineers did prefer direct routes, since they were shorter for marching soldiers, but they were also practical. In hilly country, roads frequently turned to follow the shape of the land rather than climbing steep slopes, and planners went to considerable lengths to avoid marshes and areas that flooded regularly. A road that zigzagged up a valley side was sometimes the most sensible solution, even if it added a few kilometres to the journey."],
 ["D","Once the line was fixed, workers dug a trench along it, often down to firm ground. The trench was then filled in layers. Large stones were placed at the bottom to provide a solid foundation. Above these came smaller stones and gravel, frequently mixed with lime to bind them together. On the most important roads, the top surface was made of carefully fitted stone slabs, while minor roads were simply covered with packed gravel. The surface was usually curved, higher in the middle than at the edges, so that rainwater ran off, and ditches were dug along both sides to carry the water away."],
 ["E","Much of this heavy work was carried out by soldiers, who had the skills, the tools and the discipline required, although local labourers were also used. Along many routes, stone columns known as milestones were set up at regular intervals. These showed the distance to the nearest town and often named the emperor or official responsible for building or repairing the road, which makes them extremely useful to historians trying to date construction."],
 ["F","Modern technology is now changing how these roads are studied. At an excavation near the fictional town of Calvenna, a team led by Dr Helena Marsh combined ground-penetrating radar with careful digging and found that a single stretch of road had been resurfaced at least five times over three centuries. Each repair used slightly different materials, suggesting that local builders adapted the standard method to whatever stone was available nearby."],
 ["G","Many of today's main roads in Europe still follow Roman routes, which is a powerful reminder of how well they were planned. Nevertheless, researchers warn against imagining that every Roman road was a grand paved highway. Most of the network probably consisted of gravel tracks, and the impressive stone-paved sections that tourists visit today represent only a small part of the original system."]
 ],
 groups:[
 {qtype:"Matching Headings", instr:"The passage has seven paragraphs, A-G. Choose the correct heading for paragraphs B-F from the list of headings below.", optKey:"roman",
  options:["i  Evidence of repeated repairs","ii  Why Romans abandoned straight roads","iii  Setting out the line of the road","iv  Who did the work and how roads were recorded","v  A myth about direction","vi  The cost of road building","vii  Layer upon layer","viii  Roads as routes for invading armies"], items:[
  {q:"Paragraph B", a:"iii", ev:"the surveyor could set out a perfectly straight line", ex:"Paragraph B describes surveying with the groma before digging, i.e. setting out the line. Heading v is tempting because it mentions direction, but that is the topic of C."},
  {q:"Paragraph C", a:"v", ev:"The famous straightness of Roman roads is often exaggerated", ex:"The paragraph corrects a popular belief (a myth) that Roman roads were always straight. Heading ii goes too far: the Romans still preferred direct routes; they did not abandon them."},
  {q:"Paragraph D", a:"vii", ev:"The trench was then filled in layers", ex:"Paragraph D explains how the road was built up in layers, from large stones to the surface."},
  {q:"Paragraph E", a:"iv", ev:"Much of this heavy work was carried out by soldiers", ex:"E covers the workers (soldiers and labourers) and milestones, which recorded distances and builders. No costs are discussed, so heading vi is wrong."},
  {q:"Paragraph F", a:"i", ev:"had been resurfaced at least five times over three centuries", ex:"The key finding in F is that the road was resurfaced at least five times: evidence of repeated repairs."}
 ]},
 {qtype:"True/False/Not Given", instr:"Do the following statements agree with the information in the passage? Choose TRUE, FALSE or NOT GIVEN.", options:["TRUE","FALSE","NOT GIVEN"], items:[
  {q:"Roman engineers sometimes chose a winding route instead of a steep climb.", a:"TRUE", ev:"roads frequently turned to follow the shape of the land rather than climbing steep slopes", ex:"'Turned to follow the shape of the land rather than climbing steep slopes' = chose a winding route instead of a steep climb."},
  {q:"Milestones were usually made from the same stone as the road surface.", a:"NOT GIVEN", ev:"stone columns known as milestones were set up at regular intervals", ex:"Milestones are described as stone columns, but the passage never compares their stone with the road surface."},
  {q:"Dr Marsh's team found that the builders near Calvenna used local materials for repairs.", a:"TRUE", ev:"adapted the standard method to whatever stone was available nearby", ex:"'Whatever stone was available nearby' paraphrases 'local materials'."},
  {q:"Most Roman roads had a surface of stone slabs.", a:"FALSE", ev:"Most of the network probably consisted of gravel tracks", ex:"Paragraph G says most roads were probably gravel tracks; stone slabs were used only on the most important roads (paragraph D)."}
 ]},
 {qtype:"Flow-chart Completion", instr:"Complete the flow-chart. Write ONE WORD ONLY from the passage for each answer.", limit:1, flow:true, items:[
  {q:"A trench is dug, often as far as ___ ground.", a:["firm"], ev:"often down to firm ground", ex:"Paragraph D: workers dug 'down to firm ground'."},
  {q:"Large stones form a solid ___ at the bottom.", a:["foundation"], ev:"Large stones were placed at the bottom to provide a solid foundation", ex:"The large stones provide 'a solid foundation'."},
  {q:"Smaller stones and gravel are added, often bound with ___ .", a:["lime"], ev:"frequently mixed with lime to bind them together", ex:"Lime was mixed in 'to bind them together' — the question paraphrases this as 'bound with'."},
  {q:"A curved surface lets rain run off, and ___ on both sides carry it away.", a:["ditches"], ev:"ditches were dug along both sides to carry the water away", ex:"The ditches carried the water away. 'Trench' is a distractor: it was dug at the start, under the road."}
 ]}
 ]
},
{
 id:"R60-02", title:"The Cold Chain", category:"Technology", band:6, mock:null, mins:15,
 paras:[
 ["A","Walk into almost any supermarket and you will find fresh fish, yoghurt, salad leaves and fruit that may have travelled thousands of kilometres. This is possible only because of the cold chain: an unbroken series of refrigerated stores, vehicles and display cabinets that keeps food at a controlled low temperature from the moment it is harvested or produced until it reaches the shopper. If any link in the chain fails, even for a few hours, the food can spoil and become unsafe to eat."],
 ["B","Before mechanical refrigeration, keeping food cold depended on nature. In the early nineteenth century, a profitable trade developed in natural ice. Workers cut large blocks from frozen lakes in winter, packed them in sawdust and stored them in thick-walled ice houses. Some of this ice was shipped to hot countries, where wealthy customers paid high prices for it. However, the supply was unreliable: a mild winter could mean a poor harvest of ice and a summer of shortages."],
 ["C","The situation changed in the second half of the century, when engineers developed machines that could produce cold artificially by compressing and expanding a gas. One of the most dramatic early uses was at sea. In the late nineteenth century, ships fitted with refrigeration machinery began carrying frozen meat from Australia and New Zealand to Britain, a voyage of many weeks. For farmers in the southern hemisphere, who had previously been able to sell only wool and hides abroad, this opened up an enormous new market."],
 ["D","On land, refrigerated railway wagons allowed meat and fruit to be moved quickly across large countries such as the United States. Cities no longer had to rely on animals raised and slaughtered nearby, and growers in warm regions could send their crops to customers far away. Yet for several decades the chain was incomplete, since most households still had no way of keeping food cold once they had bought it."],
 ["E","That final link arrived with the domestic refrigerator, which became a normal part of the kitchen in wealthier countries by the middle of the twentieth century. Families could now buy food once or twice a week instead of every day, and the range of products sold by shops expanded greatly. Frozen vegetables and ready meals, unknown to earlier generations, became everyday items."],
 ["F","The most recent stage has been the refrigerated shipping container. These standard-sized steel boxes contain their own cooling units and can be transferred from ship to train to lorry without being opened. According to Dr Priya Anand of the fictional Harlow Institute of Food Logistics, this development matters less for the distance food can travel than for the reliability of its condition on arrival. Sensors inside modern containers record the temperature throughout the journey, so any break in the chain can be identified."],
 ["G","Despite this progress, the cold chain remains weak in many parts of the world. In regions where electricity is expensive or unreliable, a large share of fruit, vegetables and fish is lost before it can be sold. Some researchers argue that improving cold storage close to farms would reduce hunger more effectively than increasing production. Others point out that refrigeration itself consumes large amounts of energy, and that expanding it must go hand in hand with cleaner power if it is not to add to climate change."]
 ],
 groups:[
 {qtype:"Matching Information", instr:"The passage has seven paragraphs, A-G. Which paragraph contains the following information? You may use any letter more than once.", options:["A","B","C","D","E","F","G"], items:[
  {q:"a reason why the supply of cold was not dependable in the past", a:"B", ev:"a mild winter could mean a poor harvest of ice and a summer of shortages", ex:"Paragraph B explains that natural ice depended on the weather, so supply was unreliable."},
  {q:"a description of how a technology can track conditions during transport", a:"F", ev:"Sensors inside modern containers record the temperature throughout the journey", ex:"Sensors recording the temperature = tracking conditions during transport."},
  {q:"a definition of the cold chain", a:"A", ev:"an unbroken series of refrigerated stores, vehicles and display cabinets", ex:"Paragraph A explains what the term means."},
  {q:"a change in how often people went shopping", a:"E", ev:"Families could now buy food once or twice a week instead of every day", ex:"Paragraph E describes families shopping once or twice a week rather than daily."},
  {q:"a concern about the environmental impact of refrigeration", a:"G", ev:"refrigeration itself consumes large amounts of energy", ex:"G mentions energy use and climate change — an environmental concern."}
 ]},
 {qtype:"Multiple Choice", instr:"Choose the correct letter, A, B, C or D.", items:[
  {q:"According to paragraph C, refrigerated ships benefited southern hemisphere farmers because", opts:["they could sell wool at higher prices.","they could export a product they had not been able to sell abroad before.","the voyage to Britain became much shorter.","they no longer needed to raise animals for hides."], a:"B", ev:"who had previously been able to sell only wool and hides abroad, this opened up an enormous new market", ex:"Before, they could export only wool and hides; frozen meat was a new export. A and D mention wool and hides but are not stated benefits; the voyage still took 'many weeks', so C is wrong."},
  {q:"What does the writer say about the period described in paragraph D?", opts:["Railways replaced ships for long-distance trade.","Cities began to raise more animals nearby.","The cold chain still had a missing stage.","Fruit growers preferred to sell to local customers."], a:"C", ev:"for several decades the chain was incomplete", ex:"The chain was 'incomplete' because homes could not keep food cold. Option B is the opposite: cities no longer had to rely on local animals."},
  {q:"Dr Anand believes that the main importance of refrigerated containers is that", opts:["food can now travel greater distances.","food arrives in a more predictable state.","they are cheaper than older methods.","they can be opened at each stage of transport."], a:"B", ev:"matters less for the distance food can travel than for the reliability of its condition on arrival", ex:"She says distance matters LESS than reliable condition on arrival, so A is the trap. D contradicts 'without being opened'."},
  {q:"What do some researchers suggest in paragraph G?", opts:["Farmers should grow more food.","Electricity should be made cheaper for farms.","Better storage near farms could help reduce hunger.","Refrigeration should be limited because of climate change."], a:"C", ev:"improving cold storage close to farms would reduce hunger more effectively than increasing production", ex:"C paraphrases the researchers' argument. A is what they consider LESS effective; D goes further than the text, which says refrigeration needs cleaner power, not limits."}
 ]},
 {qtype:"Table Completion", instr:"Complete the table. Write NO MORE THAN TWO WORDS from the passage for each answer.", limit:2,
  table:{head:["Period","Development","Result"], rows:[
   ["Early 19th century","Natural ice stored in [1]","Ice sold to rich buyers in hot countries"],
   ["Late 19th century","Refrigerated ships","Frozen [2] exported to Britain"],
   ["Late 19th / early 20th century","Refrigerated [3]","Food moved quickly across large countries"],
   ["Mid 20th century","Domestic refrigerator","New products such as frozen vegetables and [4]"]
  ]}, items:[
  {q:"Storage for natural ice: ___", a:["ice houses","thick-walled ice houses"], ev:"stored them in thick-walled ice houses", ex:"Blocks were packed in sawdust and kept in ice houses. 'Sawdust' is a packing material, not a storage building."},
  {q:"Product exported to Britain: frozen ___", a:["meat"], ev:"carrying frozen meat from Australia and New Zealand to Britain", ex:"The ships carried frozen meat."},
  {q:"Land transport: refrigerated ___", a:["railway wagons","wagons"], ev:"refrigerated railway wagons allowed meat and fruit to be moved quickly", ex:"Paragraph D: 'refrigerated railway wagons'."},
  {q:"New product: ___", a:["ready meals"], ev:"Frozen vegetables and ready meals, unknown to earlier generations", ex:"Ready meals are listed with frozen vegetables as new everyday items."}
 ]}
 ]
},
{
 id:"R60-03", title:"Trees Against the Heat", category:"Environment", band:6, mock:null, mins:15,
 paras:[
 ["A","On a hot summer afternoon, the centre of a large city can be several degrees warmer than the countryside around it. This effect, known as the urban heat island, occurs because roads, roofs and walls absorb the sun's energy during the day and release it slowly, often well into the night. Traffic, air-conditioning units and factories add further heat. As heatwaves become more frequent, city authorities are searching for affordable ways to keep streets cooler, and one of the oldest solutions is attracting new attention: planting trees."],
 ["B","Trees cool their surroundings in two main ways. The first is simple shade. A leafy canopy stops sunlight before it reaches the pavement, so the ground beneath stays cooler and stores less heat. The second process is less obvious. Trees draw water up from the soil and release it as vapour through tiny openings in their leaves. Turning liquid water into vapour uses energy, and this takes heat out of the surrounding air, in much the same way that sweating cools the human body."],
 ["C","In the fictional coastal city of Port Ellery, a team led by Dr Tomas Reyna attached temperature sensors to bicycles and rode them along hundreds of streets during a summer heatwave. They found that the surface of pavements under a full canopy was often more than ten degrees cooler than on treeless streets nearby. The difference in air temperature was much smaller, typically one or two degrees, but Reyna points out that even this can make a noticeable difference to how comfortable people feel and to the number of heat-related illnesses."],
 ["D","Not all trees are equally useful, however. Professor Anika Lund, a plant scientist, stresses that species with broad, dense leaves provide far more shade than those with narrow or sparse foliage. She also warns that cooling depends on water. During long droughts, many trees partly close the openings in their leaves to save moisture, and their cooling effect falls sharply at exactly the moment it is needed most. For this reason, she recommends choosing species that can cope with dry conditions and designing streets so that rainwater drains towards tree roots rather than into drains."],
 ["E","Street trees also bring practical problems. Roots can lift and crack pavements, falling leaves block gutters, and branches must be cut back from power lines and buildings. Young trees need regular watering for their first few years, and many die before they are established. The urban planner Dr Samuel Okafor argues that cities often plant large numbers of saplings for publicity but fail to budget for their care, so that a planting scheme announced with great enthusiasm may leave few surviving trees a decade later."],
 ["F","Another issue is fairness. Studies in many countries have found that wealthier districts tend to have more trees than poorer ones, which means that the residents least able to afford air-conditioning often live in the hottest streets. Mei Watanabe, who manages a neighbourhood greening programme, believes that cooling projects should begin in these areas. Her team asks residents to help decide where trees should go, and she reports that people who are involved in planting are more likely to water and protect the young trees."],
 ["G","Trees alone will not solve the problem of urban heat. Lighter-coloured roofs, more open water and better building design all have a part to play. Nevertheless, few other measures offer such a wide range of benefits, from cleaner air and reduced flooding to more attractive places to walk, at a relatively modest cost."]
 ],
 groups:[
 {qtype:"Matching Features", instr:"Look at the following statements and the list of people below. Match each statement with the correct person, A-D.", optKey:"letter",
  options:["A  Dr Tomas Reyna","B  Professor Anika Lund","C  Dr Samuel Okafor","D  Mei Watanabe"], items:[
  {q:"Local people should take part in choosing planting locations.", a:"D", ev:"Her team asks residents to help decide where trees should go", ex:"Watanabe's team involves residents in deciding where trees go."},
  {q:"A small drop in air temperature can still have health benefits.", a:"A", ev:"even this can make a noticeable difference to how comfortable people feel and to the number of heat-related illnesses", ex:"Reyna says even one or two degrees affects comfort and heat-related illness."},
  {q:"Authorities often do not plan enough money for looking after new trees.", a:"C", ev:"fail to budget for their care", ex:"Okafor argues cities 'fail to budget for their care'. Watanabe also mentions watering, but by residents, not budgets."},
  {q:"The shape and density of leaves affect how much a tree cools a street.", a:"B", ev:"species with broad, dense leaves provide far more shade than those with narrow or sparse foliage", ex:"Lund compares broad, dense leaves with narrow or sparse foliage."}
 ]},
 {qtype:"Summary Completion", instr:"Complete the summary below. Write NO MORE THAN TWO WORDS from the passage for each answer.", limit:2, items:[
  {q:"Cities become hotter than the countryside because building materials take in the sun's energy and give it out slowly, sometimes until well into the ___ .", a:["night"], ev:"release it slowly, often well into the night", ex:"Paragraph A: heat is released 'often well into the night'."},
  {q:"Trees reduce heat partly by providing ___ , which keeps the ground below from storing as much heat.", a:["shade","simple shade"], ev:"The first is simple shade", ex:"The first cooling method is shade from the canopy."},
  {q:"They also release water as ___ through their leaves, which removes heat from the air.", a:["vapour"], ev:"release it as vapour through tiny openings in their leaves", ex:"Water is released 'as vapour'; turning it into vapour uses energy."},
  {q:"This works in a similar way to ___ in people.", a:["sweating"], ev:"in much the same way that sweating cools the human body", ex:"The passage compares the process to sweating."}
 ]},
 {qtype:"Short Answer", instr:"Answer the questions below. Write NO MORE THAN THREE WORDS from the passage for each answer.", limit:3, items:[
  {q:"What did Dr Reyna's team fix the temperature sensors to?", a:["bicycles"], ev:"attached temperature sensors to bicycles", ex:"The sensors were attached to bicycles ridden along the streets."},
  {q:"According to Professor Lund, what kind of weather greatly reduces the cooling effect of trees?", a:["long droughts","droughts"], ev:"During long droughts, many trees partly close the openings in their leaves", ex:"In long droughts trees save water, so they cool less. 'Heatwave' is mentioned in C but not as the cause of reduced cooling."},
  {q:"Which kind of trees often die before they are established?", a:["young trees"], ev:"Young trees need regular watering for their first few years, and many die before they are established", ex:"Young trees need watering and many die early."},
  {q:"Which districts tend to have more trees, according to studies?", a:["wealthier districts"], ev:"wealthier districts tend to have more trees than poorer ones", ex:"Studies found wealthier districts have more trees than poorer ones."}
 ]}
 ]
},
{
 id:"R60-04", title:"Why Habits Stick", category:"Psychology", band:6, mock:null, mins:15,
 paras:[
 ["A","Every January, millions of people promise themselves that this will be the year they exercise more, eat better or spend less time on their phones. By February, most of these promises have been forgotten. It is tempting to blame weak willpower, but I believe this explanation misses the point. Psychologists who study habits have found that lasting change has much less to do with determination than with the way our behaviour is linked to the situations we find ourselves in."],
 ["B","A habit, in the psychological sense, is an action that is triggered automatically by a familiar cue, with little or no conscious thought. The cue might be a place, a time of day, a feeling or the action that came just before. Walking into the kitchen in the morning, for example, may lead straight to switching on the kettle. When the action is followed by some kind of reward, such as the pleasant taste of tea, the connection between cue and action becomes a little stronger each time it is repeated."],
 ["C","How long does this take? A popular claim says that any habit can be formed in twenty-one days, but there is little evidence for such a neat figure. In a fictional study at Linwood University, volunteers chose a simple daily behaviour, such as drinking a glass of water after breakfast, and reported each evening whether it had felt automatic. On average, it took about two months for the behaviour to reach its peak level of automaticity, but the range was enormous: some people managed it in under three weeks, while others were still making progress after eight months. Missing a single day, interestingly, made little difference to the final result."],
 ["D","These findings carry an encouraging message. If habits depend on repetition in a stable context, then the most effective strategy is not to rely on motivation, which rises and falls, but to attach the new behaviour to an existing routine. Someone who wants to stretch every day could decide to do so immediately after brushing their teeth. In my experience, plans that state exactly when and where an action will happen are far more successful than general intentions to 'be more active'."],
 ["E","Breaking an unwanted habit is harder, because the old connection does not simply disappear. Research suggests that habits are rarely erased; instead, they are gradually overridden by new responses. One useful approach is to change the environment so that the cue no longer appears. People who move house or start a new job often find this a good moment to change their behaviour, since many of their old cues have vanished. Another approach is to make the unwanted action more difficult, for example by leaving a phone in another room at night."],
 ["F","It would be a mistake, though, to conclude that individuals alone are responsible for their habits. Many of the cues that shape our daily behaviour are designed by others. Shops place sweets beside the checkout, and apps send notifications that draw us back again and again. In my opinion, governments and businesses have a responsibility to consider how their decisions shape the habits of ordinary people."],
 ["G","None of this means that change is impossible. It simply means that we should think less about willpower and more about patterns. A new habit is rarely built through one dramatic decision; it grows quietly, through small actions repeated in the same place, at the same time, until one day they no longer require any effort at all."]
 ],
 groups:[
 {qtype:"Yes/No/Not Given", instr:"Do the following statements agree with the claims of the writer in the passage? Choose YES, NO or NOT GIVEN.", options:["YES","NO","NOT GIVEN"], items:[
  {q:"Lack of willpower is the main reason why New Year promises fail.", a:"NO", ev:"It is tempting to blame weak willpower, but I believe this explanation misses the point", ex:"The writer rejects the willpower explanation, so the answer is NO."},
  {q:"Detailed plans about the time and place of an action work better than vague goals.", a:"YES", ev:"plans that state exactly when and where an action will happen are far more successful than general intentions", ex:"The writer's own view ('In my experience') agrees with this statement."},
  {q:"Moving house is the most effective way to break a bad habit.", a:"NOT GIVEN", ev:"People who move house or start a new job often find this a good moment to change their behaviour", ex:"The writer says moving house is a good moment for change, but never claims it is the MOST effective method."},
  {q:"Companies should think about how their decisions influence people's habits.", a:"YES", ev:"governments and businesses have a responsibility to consider how their decisions shape the habits of ordinary people", ex:"'Businesses' = companies; 'have a responsibility to consider' = should think about."},
  {q:"Large changes in behaviour usually result from a single important decision.", a:"NO", ev:"A new habit is rarely built through one dramatic decision", ex:"The writer says habits are 'rarely' built by one dramatic decision, which contradicts the statement."}
 ]},
 {qtype:"Note Completion", instr:"Complete the notes below. Write ONE WORD ONLY from the passage for each answer.", limit:1, items:[
  {q:"Habit = action started automatically by a familiar ___", a:["cue"], ev:"an action that is triggered automatically by a familiar cue", ex:"Paragraph B defines a habit as triggered by a familiar cue."},
  {q:"Link between cue and action grows stronger when action is followed by a ___", a:["reward"], ev:"When the action is followed by some kind of reward", ex:"A reward (e.g. the taste of tea) strengthens the connection."},
  {q:"Better strategy than depending on ___, which changes over time: link new behaviour to an existing routine", a:["motivation"], ev:"not to rely on motivation, which rises and falls", ex:"Motivation 'rises and falls' — the notes paraphrase this as 'changes over time'."},
  {q:"Old habits are not erased but slowly ___ by new responses", a:["overridden"], ev:"they are gradually overridden by new responses", ex:"'Gradually overridden' = slowly overridden."}
 ]},
 {qtype:"Multiple Choice", instr:"Choose the correct letter, A, B, C or D.", items:[
  {q:"What does the writer say about the claim that habits form in twenty-one days?", opts:["It is true for simple behaviours only.","It is not well supported by research.","It was first made at Linwood University.","It applies to most people."], a:"B", ev:"there is little evidence for such a neat figure", ex:"'Little evidence' = not well supported. The Linwood study is mentioned next, but it did not make this claim."},
  {q:"What did the Linwood University study find?", opts:["Most volunteers formed their habit in three weeks.","Volunteers who missed a day had to start again.","The time needed to form a habit varied greatly between people.","Drinking water was the easiest habit to form."], a:"C", ev:"the range was enormous", ex:"Some needed under three weeks, others over eight months. A describes only some people; B is contradicted ('Missing a single day ... made little difference')."},
  {q:"Why does the writer mention sweets beside the checkout?", opts:["to show that habits are partly shaped by other people's choices","to give an example of a habit that is easy to break","to criticise people who lack self-control","to show how rewards strengthen good habits"], a:"A", ev:"Many of the cues that shape our daily behaviour are designed by others", ex:"The example supports the point that cues are designed by others, so individuals are not solely responsible."}
 ]}
 ]
},
{
 id:"R60-05", title:"Money That Stays at Home", category:"Economics", band:6, mock:null, mins:15,
 paras:[
 ["A","Most people never think twice about the money in their pockets: it is issued by a central bank and accepted everywhere in the country. Yet in hundreds of towns around the world, residents also use a second kind of money that can only be spent locally. These community currencies, as they are known, are not meant to replace national money. Their purpose is to encourage people to spend with local businesses and so keep wealth circulating within the community."],
 ["B","The idea is not new. During periods of economic crisis in the twentieth century, when national money was scarce, a number of towns printed their own notes so that workers could be paid and shops could keep trading. Most of these schemes were closed down once conditions improved, often because national governments disliked the competition. Interest returned towards the end of the century, this time driven less by emergency than by concern about the decline of small high-street shops."],
 ["C","A typical modern scheme works quite simply. Residents exchange national money for local notes, usually at a rate of one to one, at banks, libraries or community centres. They can then spend the notes at any business that has joined the scheme. Some schemes offer a small bonus to encourage people to take part, so that, for instance, ten pounds of national money buys eleven local pounds. Increasingly, payments are made through a mobile phone app rather than with paper notes, which reduces the cost of printing and makes the currency harder to forge."],
 ["D","Supporters base their case on what economists call the local multiplier effect. When a customer spends money in a large chain store, much of it quickly leaves the area as profits for distant shareholders or payments to suppliers elsewhere. When the same money is spent in an independent shop, a larger share is likely to be passed on to local workers, local suppliers and other nearby businesses. Because a community currency cannot be spent outside the area, every unit must stay in the local economy until somebody exchanges it back."],
 ["E","In practice, however, results have often been disappointing. In the fictional market town of Brackwater, the local pound was launched with great publicity, and more than two hundred businesses signed up. Three years later, a review by the economist Dr Ruth Calloway found that only a small fraction of residents used the currency regularly. Many shopkeepers complained that they had little to spend their local pounds on, since their main suppliers would not accept them. As a result, the notes were frequently exchanged back into national money almost as soon as they were received."],
 ["F","Calloway nevertheless believes the scheme was not a failure. She argues that its main value lay in raising awareness: residents reported thinking more carefully about where they shopped, even when they paid with ordinary money. Several businesses also said that joining the scheme had introduced them to other local firms with whom they now trade directly."],
 ["G","Some communities have experimented with an alternative known as time banking, in which the unit of exchange is not money but an hour of work. A person who spends an hour helping a neighbour with gardening earns one time credit, which they can later use to receive an hour of help with something else, such as computer repairs. Every hour is valued equally, whatever the skill involved. Supporters say this approach recognises contributions, such as caring for elderly people, that the ordinary economy tends to undervalue."]
 ],
 groups:[
 {qtype:"True/False/Not Given", instr:"Do the following statements agree with the information in the passage? Choose TRUE, FALSE or NOT GIVEN.", options:["TRUE","FALSE","NOT GIVEN"], items:[
  {q:"Community currencies are intended to take the place of national money.", a:"FALSE", ev:"These community currencies, as they are known, are not meant to replace national money", ex:"The passage states they are NOT meant to replace national money."},
  {q:"Many early schemes ended because governments were unhappy about them.", a:"TRUE", ev:"often because national governments disliked the competition", ex:"'Disliked the competition' paraphrases 'were unhappy about them'."},
  {q:"Digital versions of local currencies are more popular with older residents than paper notes.", a:"NOT GIVEN", ev:"Increasingly, payments are made through a mobile phone app rather than with paper notes", ex:"Apps are mentioned, but nothing is said about which age groups prefer them."},
  {q:"In some schemes, people receive more local money than the national money they pay.", a:"TRUE", ev:"ten pounds of national money buys eleven local pounds", ex:"The bonus means ten pounds buys eleven local pounds."},
  {q:"Most Brackwater residents used the local pound regularly after three years.", a:"FALSE", ev:"only a small fraction of residents used the currency regularly", ex:"Only a small fraction used it, not most. The large number of businesses (over 200) is a distractor."}
 ]},
 {qtype:"Matching Information", instr:"The passage has seven paragraphs, A-G. Which paragraph contains the following information?", options:["A","B","C","D","E","F","G"], items:[
  {q:"an explanation of why money spent in chain stores tends to leave an area", a:"D", ev:"much of it quickly leaves the area as profits for distant shareholders", ex:"Paragraph D explains the local multiplier effect and where chain-store money goes."},
  {q:"a system in which all kinds of work receive the same value", a:"G", ev:"Every hour is valued equally, whatever the skill involved", ex:"Time banking values every hour equally."},
  {q:"a benefit for businesses that was not directly about the currency", a:"F", ev:"joining the scheme had introduced them to other local firms", ex:"Businesses met other local firms — a side benefit, not about spending the currency."},
  {q:"places where people can obtain local notes", a:"C", ev:"at banks, libraries or community centres", ex:"Paragraph C lists where national money can be exchanged for local notes."}
 ]},
 {qtype:"Sentence Completion", instr:"Complete the sentences below. Write NO MORE THAN TWO WORDS from the passage for each answer.", limit:2, items:[
  {q:"Late twentieth-century schemes were mainly motivated by worries about the decline of small ___ shops.", a:["high-street"], ev:"concern about the decline of small high-street shops", ex:"The revival was driven by concern about small high-street shops, not by emergency."},
  {q:"Using an app makes a local currency cheaper to run and more difficult to ___ .", a:["forge"], ev:"makes the currency harder to forge", ex:"'Harder to forge' = more difficult to forge."},
  {q:"Brackwater shopkeepers found it hard to use local pounds because their main ___ refused them.", a:["suppliers"], ev:"since their main suppliers would not accept them", ex:"The suppliers would not accept local pounds."},
  {q:"In a time bank, an hour of help earns one ___ .", a:["time credit"], ev:"earns one time credit", ex:"An hour of work earns one time credit."}
 ]}
 ]
},
{
 id:"R60-06", title:"Saving the Walls", category:"Art", band:6, mock:null, mins:15,
 paras:[
 ["A","Large painted murals have become a familiar sight in towns and cities around the world. They decorate the sides of apartment blocks, schools, railway bridges and shops, and many have become local landmarks. Unlike paintings in a museum, however, these works are exposed day and night to sun, rain, frost and pollution. As a result, a growing number of conservators are now specialising in the difficult task of keeping outdoor murals alive."],
 ["B","The greatest enemy of an outdoor mural is usually water. Rain that soaks into a brick or concrete wall carries salts with it, and when the water evaporates the salts form crystals that push paint away from the surface. In cold climates, water that freezes inside the wall expands and causes further cracking. Sunlight adds to the damage: ultraviolet rays break down the binders that hold paint together, so that colours fade, with reds and purples often disappearing first."],
 ["C","Restoration therefore begins not with paint but with investigation. Conservators photograph the mural in detail, record every crack and area of loss, and take tiny samples to identify the original materials. They also try to find out where the moisture is coming from. In one case described by the conservator Lucia Ferrante, a mural that had been repainted twice in ten years kept peeling because of a broken gutter above it. 'Until the water problem is solved,' she says, 'any new paint is simply wasted money.'"],
 ["D","Once the wall is dry and stable, the surface is cleaned, often with soft brushes and low-pressure water rather than harsh chemicals. Loose paint is fixed back onto the wall with special adhesives. Only then are missing areas filled in. Here conservators face a difficult choice. Some prefer to retouch damaged areas so that they cannot be distinguished from the original, while others use a slightly lighter tone or fine lines, so that a viewer standing close can see what has been added. Finally, a transparent protective coating may be applied, although experts disagree about whether such coatings trap moisture beneath them."],
 ["E","Outdoor murals raise questions that museum conservators rarely face. Many were painted by living artists, who may have strong views about what should happen to their work. Dr Kwame Asante, who teaches conservation at a fictional arts college in Northfield, believes the original artist should be consulted whenever possible, even if this slows down the project. Some artists are happy to repaint their own murals; others feel that a work made for the street should be allowed to age and eventually disappear."],
 ["F","Local residents often have opinions too. Community organiser Jo Pemberton describes a project in which neighbours were invited to vote on whether a faded mural from the 1980s should be restored or replaced with a new design. To the surprise of the organisers, a large majority voted for restoration, explaining that the old painting reminded them of the history of the area. Pemberton now argues that any decision about a public mural should include the people who live alongside it."],
 ["G","New technology is also helping. High-resolution digital scans allow conservators to keep an exact record of a mural's condition, so that future damage can be measured accurately. The materials scientist Dr Henrik Solberg is testing paints that resist ultraviolet light for much longer than traditional products. Even so, most specialists accept that no outdoor mural will last for ever, and that regular, modest maintenance is far more effective than an expensive rescue every few decades."]
 ],
 groups:[
 {qtype:"Matching Headings", instr:"The passage has seven paragraphs, A-G. Choose the correct heading for paragraphs B-F from the list of headings below.", optKey:"roman",
  options:["i  Respecting the creator's wishes","ii  How weather destroys paintings","iii  Why museums refuse outdoor works","iv  Steps in repairing the surface","v  A neighbourhood chooses the past","vi  Finding the cause before acting","vii  The high cost of new murals","viii  Artists who paint only in museums"], items:[
  {q:"Paragraph B", a:"ii", ev:"The greatest enemy of an outdoor mural is usually water", ex:"B explains how water, frost and sunlight damage murals."},
  {q:"Paragraph C", a:"vi", ev:"Restoration therefore begins not with paint but with investigation", ex:"C is about investigating — including finding where the moisture comes from — before painting. The mention of 'wasted money' may suggest vii, but the paragraph is not about the cost of new murals."},
  {q:"Paragraph D", a:"iv", ev:"Once the wall is dry and stable, the surface is cleaned", ex:"D describes the repair sequence: cleaning, fixing loose paint, filling gaps, coating."},
  {q:"Paragraph E", a:"i", ev:"the original artist should be consulted whenever possible", ex:"E focuses on living artists and consulting them about their work."},
  {q:"Paragraph F", a:"v", ev:"a large majority voted for restoration", ex:"Residents voted to restore the old mural because it reminded them of local history — they chose the past."}
 ]},
 {qtype:"Matching Features", instr:"Look at the following statements and the list of people below. Match each statement with the correct person, A-D.", optKey:"letter",
  options:["A  Lucia Ferrante","B  Dr Kwame Asante","C  Jo Pemberton","D  Dr Henrik Solberg"], items:[
  {q:"is developing products that are less affected by sunlight", a:"D", ev:"is testing paints that resist ultraviolet light for much longer than traditional products", ex:"Solberg tests paints that resist ultraviolet light (sunlight)."},
  {q:"thinks people living near a mural should have a say in its future", a:"C", ev:"any decision about a public mural should include the people who live alongside it", ex:"Pemberton argues decisions should include the people who live alongside a mural."},
  {q:"warns that repainting is pointless if damp has not been dealt with", a:"A", ev:"Until the water problem is solved,' she says, 'any new paint is simply wasted money.", ex:"Ferrante says new paint is wasted money until the water problem is solved."},
  {q:"accepts that consulting the painter may cause delays", a:"B", ev:"even if this slows down the project", ex:"Asante wants artists consulted 'even if this slows down the project'."}
 ]},
 {qtype:"Summary Completion", instr:"Complete the summary below. Write ONE WORD ONLY from the passage for each answer.", limit:1, items:[
  {q:"Water carries ___ into walls, and these form crystals that push the paint off.", a:["salts"], ev:"carries salts with it", ex:"Rain carries salts, which crystallise as the water evaporates."},
  {q:"Ultraviolet light breaks down the ___ in paint, causing colours to fade.", a:["binders"], ev:"ultraviolet rays break down the binders that hold paint together", ex:"UV rays break down the binders."},
  {q:"When repairing, some conservators make additions visible by using a lighter tone or fine ___ .", a:["lines"], ev:"use a slightly lighter tone or fine lines", ex:"Fine lines let a close viewer see what has been added."},
  {q:"Experts disagree about protective coatings because they may trap ___ .", a:["moisture"], ev:"whether such coatings trap moisture beneath them", ex:"The disagreement is about coatings trapping moisture."}
 ]}
 ]
}
];
