/* ===== READING BANK — band 5.5 practice sets (original material written for this app) ===== */
export const SETS = [
{
 id:"R55-01", title:"Why Teenagers Stay Up Late", category:"Health", band:5.5, mock:null, mins:15,
 paras:[
 ["A","Many parents complain that their teenage children refuse to go to bed at a sensible hour and then cannot get up in the morning. For a long time, this behaviour was seen as a sign of laziness or too much screen time. However, research over the past few decades suggests that there is a biological reason why young people sleep later than adults and younger children."],
 ["B","The main explanation involves the body clock, an internal system that controls when we feel sleepy and when we feel awake. This clock is affected by a hormone called melatonin, which the brain releases in the evening to prepare the body for sleep. In younger children, melatonin is usually released at around eight or nine o'clock. During puberty, however, the release of this hormone moves later, often by up to two hours. As a result, many teenagers simply do not feel tired until eleven o'clock or even midnight."],
 ["C","A second factor is what scientists call sleep pressure. This is the need for sleep that builds up the longer a person stays awake. In a study at the Harwell Institute of Child Health, Dr Miriam Okafor and her team measured sleep pressure in 300 volunteers aged between 10 and 18. They found that in older teenagers, sleep pressure grew more slowly during the day. \"This means a 16-year-old can stay alert in the evening in a way that a 10-year-old cannot,\" Okafor explains."],
 ["D","The problem is that school days usually start early. Experts recommend that teenagers get between eight and ten hours of sleep each night, but many get fewer than seven on school nights. Lack of sleep can affect concentration, memory and mood. It has also been linked to a higher risk of accidents among young drivers. At weekends, many teenagers try to catch up by sleeping until late morning, but this can make it even harder to fall asleep on Sunday night."],
 ["E","Some schools have responded by starting lessons later. In the town of Marlow Bridge, two secondary schools moved their start time from 8.15 to 9.00 in 2019. After one year, a report by the local education office found that attendance had risen and fewer students were late. Students also reported feeling less sleepy in morning classes. However, not everyone was in favour of the change. Some parents found it difficult to organise their working day, and bus timetables had to be changed."],
 ["F","Technology also plays a part, although it is not the main cause. The bright light from phones and tablets can delay the release of melatonin further. For this reason, doctors advise teenagers to stop using screens at least an hour before bed and to keep their bedrooms dark and cool. Getting outside in natural daylight in the morning can also help to move the body clock earlier. Above all, researchers say, adults should understand that a teenager's late nights are not simply a matter of bad habits."]
 ],
 groups:[
 {qtype:"True/False/Not Given", instr:"Do the following statements agree with the information in the passage? Choose TRUE, FALSE or NOT GIVEN.", options:["TRUE","FALSE","NOT GIVEN"], items:[
  {q:"Research suggests that teenagers' late bedtimes may have a physical cause.", a:"TRUE", ev:"there is a biological reason why young people sleep later than adults and younger children", ex:"'Biological reason' is a synonym for 'physical cause'. The passage says research suggests this, so the statement is TRUE."},
  {q:"Melatonin is released in the morning to help people wake up.", a:"FALSE", ev:"which the brain releases in the evening to prepare the body for sleep", ex:"The passage says melatonin is released in the evening and prepares the body for sleep, which is the opposite of the statement."},
  {q:"The delay in melatonin release is greater for boys than for girls.", a:"NOT GIVEN", ev:"the release of this hormone moves later, often by up to two hours", ex:"The passage gives the size of the delay but never compares boys and girls. When a comparison is not made, the answer is NOT GIVEN.", strat:"If you cannot find the key idea (here: boys vs girls) anywhere, think NOT GIVEN."},
  {q:"Not getting enough sleep has been connected with road accidents involving young drivers.", a:"TRUE", ev:"It has also been linked to a higher risk of accidents among young drivers", ex:"'Linked to' = 'connected with'. The statement matches the passage."},
  {q:"The two schools in Marlow Bridge plan to start lessons even later in the future.", a:"NOT GIVEN", ev:"moved their start time from 8.15 to 9.00 in 2019", ex:"The passage describes the change made in 2019 and its results, but says nothing about future plans."}
 ]},
 {qtype:"Multiple Choice", instr:"Choose the correct letter, A, B, C or D.", items:[
  {q:"What did Dr Okafor's study find about older teenagers?", opts:["They need more sleep than younger children.","Their sleep pressure builds up more slowly.","They produce less melatonin.","They sleep better at weekends."], a:"B", ev:"in older teenagers, sleep pressure grew more slowly during the day", ex:"'Grew more slowly' = 'builds up more slowly'. Melatonin (C) is discussed in paragraph B, not in the study."},
  {q:"According to paragraph D, what is the result of sleeping late at weekends?", opts:["It improves memory and mood.","It makes it harder to sleep on Sunday night.","It lowers the risk of accidents.","It gives teenagers ten hours of sleep."], a:"B", ev:"this can make it even harder to fall asleep on Sunday night", ex:"The passage says catching up at weekends can make Sunday night sleep more difficult. Memory and mood (A) are affected by lack of sleep, not by weekend lie-ins."},
  {q:"What was one problem with the later start time in Marlow Bridge?", opts:["Attendance went down.","Students felt more tired in the morning.","Some parents had trouble planning their working day.","School buses stopped running."], a:"C", ev:"Some parents found it difficult to organise their working day", ex:"'Organise their working day' = 'planning their working day'. Attendance actually rose (A), and bus timetables were changed, not stopped (D)."}
 ]},
 {qtype:"Sentence Completion", instr:"Complete the sentences below. Write NO MORE THAN TWO WORDS from the passage for each answer.", limit:2, items:[
  {q:"The body clock is affected by a hormone known as ___.", a:["melatonin"], ev:"This clock is affected by a hormone called melatonin", ex:"'Known as' paraphrases 'called'. The hormone is named in paragraph B."},
  {q:"The need for sleep that increases while a person is awake is called ___.", a:["sleep pressure"], ev:"what scientists call sleep pressure", ex:"Paragraph C names the idea and then defines it as 'the need for sleep that builds up the longer a person stays awake'."},
  {q:"The light from phones and tablets can ___ the release of melatonin.", a:["delay"], ev:"can delay the release of melatonin further", ex:"Paragraph F says screen light can delay melatonin. One word fits the grammar of the gap (a verb after 'can')."},
  {q:"Spending time in natural ___ in the morning can help move the body clock earlier.", a:["daylight"], ev:"Getting outside in natural daylight in the morning", ex:"'Spending time' paraphrases 'getting outside'. The word after 'natural' is 'daylight'."}
 ]}
 ]
},
{
 id:"R55-02", title:"Kelderby's Protected Bike Lanes", category:"Urban planning", band:5.5, mock:null, mins:15,
 paras:[
 ["A","Ten years ago, the town of Kelderby, with a population of about 48,000, had a traffic problem. Its narrow streets were crowded with cars, especially during the morning rush hour, and fewer than three per cent of journeys were made by bicycle. Local surveys showed that many residents wanted to cycle but felt it was too dangerous to share the road with cars and lorries."],
 ["B","In 2016 the town council decided to act. Its transport officer, Helen Varga, proposed a network of protected bike lanes. Unlike painted lanes, which are only marked by a white line, protected lanes are separated from traffic by a physical barrier such as a kerb, a row of plant boxes or a line of parked cars. Varga's plan included 22 kilometres of these lanes, linking the town centre with the railway station, the hospital and the three largest schools."],
 ["C","The plan was not popular with everyone. Shop owners on the main street, Bridge Road, were worried that removing parking spaces would mean fewer customers. Some drivers argued that narrower roads would cause even worse traffic jams. At a public meeting in 2017, more than 400 people came to express their views, and the council agreed to build the network in stages so that its effects could be measured."],
 ["D","The first stage, 6 kilometres long, opened in 2018. The second stage added another 9 kilometres in 2020, and the final stage, completed in 2022, finished the network. In total the project cost £7.4 million, most of which came from a national government fund for sustainable transport. The council paid about a fifth of the cost itself, and local volunteers helped to plant the flower boxes that line many of the routes."],
 ["E","The results have been clear. By 2023, cycling made up 14 per cent of all journeys in the town, compared with under three per cent before. The number of children cycling to school rose fourfold. Road injuries to cyclists fell by around a third, even though there were far more cyclists on the roads. Surprisingly, traffic jams did not get worse. In fact, average car journey times in the centre stayed almost the same, because many short trips that had been made by car were now made by bike."],
 ["F","Even the shop owners have changed their minds. A study by the Kelderby Chamber of Commerce found that sales on Bridge Road rose by 9 per cent in the two years after the lanes opened. Cyclists tend to spend less on each visit than drivers, but they visit more often. Sandra Oyelaran, who runs a bakery on the street, says, \"I was against the lanes at first, but now I have customers who stop every morning on their way to work.\""],
 ["G","Other towns are now studying Kelderby's experience. Varga believes the most important lesson is to build lanes that connect to each other. \"A short lane that ends suddenly is no use to anyone,\" she says. \"People will only cycle if they can get all the way to where they want to go safely.\" Kelderby is now planning new lanes to two nearby villages."]
 ],
 groups:[
 {qtype:"Matching Headings", instr:"The passage has seven paragraphs, A-G. Choose the correct heading for paragraphs B-G from the list of headings below. There are more headings than paragraphs.", optKey:"roman",
  options:["i  Building the network step by step","ii  Advice for other places","iii  A plan for separated cycle routes","iv  The high cost of painted lanes","v  Early objections from businesses and drivers","vi  An unexpected benefit for traders","vii  Why cyclists prefer the countryside","viii  Clear improvements in safety and travel habits","ix  A town where few people cycled"], items:[
  {q:"Paragraph B", a:"iii", ev:"protected lanes are separated from traffic by a physical barrier", ex:"Paragraph B describes Varga's proposal for lanes separated from traffic. 'Painted lanes' are mentioned only to explain the difference, so heading iv is a trap."},
  {q:"Paragraph C", a:"v", ev:"Shop owners on the main street, Bridge Road, were worried", ex:"The paragraph is about shop owners' and drivers' worries before the lanes were built."},
  {q:"Paragraph D", a:"i", ev:"The first stage, 6 kilometres long, opened in 2018", ex:"The paragraph lists the three stages of construction in order, which matches 'step by step'."},
  {q:"Paragraph E", a:"viii", ev:"Road injuries to cyclists fell by around a third", ex:"Paragraph E gives results: more cycling (travel habits) and fewer injuries (safety)."},
  {q:"Paragraph F", a:"vi", ev:"sales on Bridge Road rose by 9 per cent", ex:"Shop owners expected to lose customers, so higher sales are an unexpected benefit for traders."},
  {q:"Paragraph G", a:"ii", ev:"Varga believes the most important lesson is to build lanes that connect to each other", ex:"The paragraph gives a lesson for other towns that are studying Kelderby. 'Nearby villages' does not mean cyclists prefer the countryside (vii)."}
 ]},
 {qtype:"Table Completion", instr:"Complete the table below. Write ONE WORD AND/OR A NUMBER from the passage for each answer.", limit:1,
  table:{head:["Topic","Details"], rows:[["Main worry of shop owners","loss of [1] spaces"],["Public meeting in 2017","attended by more than [2] people"],["Main source of money","a national government [3]"],["Share of journeys by bike in 2023","[4] per cent"]]}, items:[
  {q:"Shop owners' worry: loss of ___ spaces", a:["parking"], ev:"removing parking spaces would mean fewer customers", ex:"'Removing' parking spaces = 'loss of' parking spaces (paragraph C)."},
  {q:"Number at the meeting: more than ___", a:["400"], ev:"more than 400 people came to express their views", ex:"The number appears in paragraph C. Do not confuse it with 48,000, the town's population."},
  {q:"Source of money: a national government ___", a:["fund"], ev:"most of which came from a national government fund for sustainable transport", ex:"Most of the money came from a government fund; the council paid only about a fifth."},
  {q:"Share of journeys by bike in 2023: ___ per cent", a:["14"], ev:"cycling made up 14 per cent of all journeys in the town", ex:"14 per cent is the 2023 figure. 'Under three per cent' was the figure before the lanes, so it is a distractor."}
 ]},
 {qtype:"Short Answer", instr:"Answer the questions below. Write NO MORE THAN THREE WORDS from the passage for each answer.", limit:3, items:[
  {q:"What is used to mark a painted lane?", a:["a white line","white line"], ev:"which are only marked by a white line", ex:"Paragraph B explains that painted lanes are only marked by a white line, unlike protected lanes."},
  {q:"By how much did the number of children cycling to school increase?", a:["fourfold"], ev:"The number of children cycling to school rose fourfold", ex:"'Increase' paraphrases 'rose'. Fourfold means four times as many."},
  {q:"What kind of business does Sandra Oyelaran run?", a:["a bakery","bakery"], ev:"who runs a bakery on the street", ex:"Paragraph F says she runs a bakery on Bridge Road."}
 ]}
 ]
},
{
 id:"R55-03", title:"The Language of Honeybees", category:"Biology", band:5.5, mock:null, mins:15,
 paras:[
 ["A","A honeybee colony can contain up to 50,000 bees, and its survival depends on finding enough food. Worker bees fly out from the hive to collect nectar and pollen from flowers, sometimes travelling several kilometres. But a single bee cannot carry much, so when she finds a good source of food, she needs to tell her sisters where it is. Bees do this mainly through a remarkable form of communication: dancing."],
 ["B","Scientists first described the bee dance in detail in the early twentieth century, and since then it has been studied in many countries. There are two main types. The round dance is used when food is close to the hive, usually less than about 50 metres away. The returning bee runs in small circles on the honeycomb, first in one direction and then the other. This tells the other bees that food is nearby, but it does not show the exact direction."],
 ["C","For food that is further away, bees perform the waggle dance. The bee runs forward in a straight line while shaking her body from side to side, then circles back and repeats the movement. The angle of the straight run shows the direction of the food in relation to the sun. If the bee runs straight up the honeycomb, the food is in the same direction as the sun. The length of the waggle run shows distance: the longer the bee waggles, the further away the food is."],
 ["D","Dance is not the only signal. Dr Petra Lindqvist of the Northfield Bee Research Centre has shown that the scent of flowers carried on a dancer's body helps other bees to recognise the right flowers when they arrive. \"The dance gives the address, and the smell tells them what the house looks like,\" she says. Bees that follow the dance also taste small samples of nectar offered by the dancer."],
 ["E","Bees can also send warnings. Professor Daniel Osei found that when bees are attacked at a food source, they return and give other bees a short \"stop signal\" by pressing their head against the dancer and making a buzzing sound. Dancers that receive many stop signals soon end their dance, so fewer bees fly to the dangerous site."],
 ["F","Some researchers have tried to talk to bees directly. Dr Hana Kovac and her team built a small robot bee that could perform the waggle dance on a honeycomb. Real bees followed the robot's instructions and flew towards the place it described, although less reliably than when they followed a real bee. Kovac believes that smell and vibration, which the robot could not fully copy, are an important part of the message."],
 ["G","Understanding how bees communicate is not only interesting; it may also be useful. Bees pollinate many of the crops that people eat, and their numbers have fallen in many regions. By reading the dances in a hive, beekeepers and farmers can learn where bees are finding food and which areas lack flowers. This information could help them to plant new flowers in the right places."]
 ],
 groups:[
 {qtype:"Matching Features", instr:"Look at the following findings and the list of researchers below. Match each finding with the correct researcher, A, B or C. You may use any letter more than once.", optKey:"letter",
  options:["A  Dr Petra Lindqvist","B  Professor Daniel Osei","C  Dr Hana Kovac"], items:[
  {q:"Bees can be guided by a machine.", a:"C", ev:"Real bees followed the robot's instructions and flew towards the place it described", ex:"Kovac's robot bee is the 'machine'. Real bees flew where it told them to go."},
  {q:"Bees use a signal to stop others from visiting a dangerous place.", a:"B", ev:"give other bees a short \"stop signal\"", ex:"Osei found the stop signal, which means fewer bees fly to the dangerous site."},
  {q:"The smell of flowers helps bees to identify the correct food source.", a:"A", ev:"the scent of flowers carried on a dancer's body helps other bees to recognise the right flowers", ex:"'Scent' = 'smell' and 'recognise the right flowers' = 'identify the correct food source'."},
  {q:"Some parts of a bee's message are hard to reproduce.", a:"C", ev:"which the robot could not fully copy", ex:"Kovac says smell and vibration could not be fully copied by the robot. 'Reproduce' = 'copy'. Lindqvist talks about smell too, but not about copying it."}
 ]},
 {qtype:"Flow-chart Completion", instr:"Complete the flow-chart below. Write NO MORE THAN TWO WORDS from the passage for each answer.", limit:2, flow:true, items:[
  {q:"A worker bee collects nectar and ___ from flowers.", a:["pollen"], ev:"collect nectar and pollen from flowers", ex:"Paragraph A says workers collect nectar and pollen."},
  {q:"If the food is near the hive, she performs the ___.", a:["round dance"], ev:"The round dance is used when food is close to the hive", ex:"'Near' = 'close to'. The round dance is for food less than about 50 metres away."},
  {q:"If the food is far away, the angle of the waggle run shows its direction in relation to the ___.", a:["sun"], ev:"shows the direction of the food in relation to the sun", ex:"The direction of the straight run is measured against the position of the sun."},
  {q:"The length of the waggle run shows the ___.", a:["distance"], ev:"The length of the waggle run shows distance", ex:"The longer the waggle, the further away the food is."},
  {q:"Following bees taste samples of ___ given by the dancer.", a:["nectar"], ev:"taste small samples of nectar offered by the dancer", ex:"'Given' paraphrases 'offered'. The answer is in paragraph D."}
 ]},
 {qtype:"True/False/Not Given", instr:"Do the following statements agree with the information in the passage? Choose TRUE, FALSE or NOT GIVEN.", options:["TRUE","FALSE","NOT GIVEN"], items:[
  {q:"A honeybee colony may include as many as 50,000 bees.", a:"TRUE", ev:"A honeybee colony can contain up to 50,000 bees", ex:"'As many as' = 'up to'. The statement matches the passage."},
  {q:"The round dance shows other bees the exact direction of the food.", a:"FALSE", ev:"it does not show the exact direction", ex:"The passage clearly says the round dance does NOT show the exact direction."},
  {q:"Bees perform the waggle dance more often in summer than in spring.", a:"NOT GIVEN", ev:"For food that is further away, bees perform the waggle dance", ex:"The passage explains when bees use the waggle dance (for distant food) but says nothing about seasons."},
  {q:"Real bees followed the robot as reliably as they followed other bees.", a:"FALSE", ev:"although less reliably than when they followed a real bee", ex:"'Less reliably' contradicts 'as reliably as'."}
 ]}
 ]
},
{
 id:"R55-04", title:"Markets After Dark", category:"Culture", band:5.5, mock:null, mins:15,
 paras:[
 ["A","As the sun goes down in many cities around the world, car parks, empty streets and old railway yards are filling with food stalls, coloured lights and crowds of people. Night food markets, where dozens of small sellers cook and sell food in the open air after dark, have become one of the fastest-growing forms of urban entertainment. In some cities, a popular market can attract more than 10,000 visitors on a single Saturday night."],
 ["B","Night markets are not new. In parts of East and South-East Asia, they have existed for centuries, often growing up around ports and temples where traders gathered after the heat of the day had passed. In hot climates, the evening was simply the most comfortable time to shop and eat. For many families, a visit to the night market was, and still is, a regular part of the week rather than a special event."],
 ["C","In the last twenty years, however, the idea has spread to cities in Europe, North America and Australia, where the climate is often cooler. Dr Lucy Fenwick, a cultural geographer at the University of Ashcombe, has studied 35 new night markets in these regions. She found that most of them were started by small groups of food sellers or local councils, not by large companies. \"They often began as an experiment to bring life to a quiet area of the city after the shops closed,\" she says."],
 ["D","One reason for their popularity is cost. Opening a restaurant requires a large amount of money for rent, equipment and staff. A market stall, by contrast, can be rented for a single night for a small fee. This allows people with little money to test a business idea before taking a bigger risk. Fenwick's research shows that around one in five sellers she interviewed later opened a permanent restaurant or café."],
 ["E","Night markets also offer something that is hard to find elsewhere: variety. In one evening, visitors can try dishes from a dozen different countries, often cooked by people from those countries. Many young people say they prefer the relaxed atmosphere to formal restaurants, and they enjoy sharing photos of unusual dishes on social media. Live music and craft stalls add to the sense of occasion, and many markets now include areas where children can play while their parents eat."],
 ["F","Not everyone is happy, though. People living near some markets have complained about noise, litter and traffic late at night. In the city of Port Hallam, the council limited its market to two nights a week after residents collected more than 2,000 signatures on a petition. Organisers now hire cleaning teams and close the music at ten o'clock. Most experts agree that night markets succeed best when they work closely with the local community."]
 ],
 groups:[
 {qtype:"Matching Information", instr:"The passage has six paragraphs, A-F. Which paragraph contains the following information? You may use any letter more than once.", options:["A","B","C","D","E","F"], items:[
  {q:"an example of a market that had to reduce the number of days it opened", a:"F", ev:"the council limited its market to two nights a week", ex:"Port Hallam's market was limited to two nights a week after a petition."},
  {q:"a reason why evening shopping developed in warm places", a:"B", ev:"In hot climates, the evening was simply the most comfortable time to shop and eat", ex:"'Warm places' = 'hot climates'. The reason is comfort after the heat of the day."},
  {q:"the number of people who may visit one market in an evening", a:"A", ev:"a popular market can attract more than 10,000 visitors on a single Saturday night", ex:"Paragraph A gives the visitor figure. The 2,000 in paragraph F is the number of signatures, not visitors."},
  {q:"information about who usually started the new markets", a:"C", ev:"most of them were started by small groups of food sellers or local councils", ex:"Fenwick found that small groups of sellers or councils, not large companies, started most markets."}
 ]},
 {qtype:"Summary Completion", instr:"Complete the summary below. Write ONE WORD ONLY from the passage for each answer.", limit:1, items:[
  {q:"Opening a restaurant is expensive because of rent, equipment and ___.", a:["staff"], ev:"requires a large amount of money for rent, equipment and staff", ex:"The three costs are listed in paragraph D."},
  {q:"In contrast, a stall can be rented for one night for a small ___.", a:["fee"], ev:"can be rented for a single night for a small fee", ex:"'One night' = 'a single night'. The word after 'small' is 'fee'."},
  {q:"This lets people with little money test a business ___.", a:["idea"], ev:"to test a business idea", ex:"The stall is a cheap way to try out an idea before taking a bigger risk."},
  {q:"About one in five sellers in Fenwick's study later opened a permanent restaurant or ___.", a:["café","cafe"], ev:"later opened a permanent restaurant or café", ex:"Paragraph D: around one in five sellers opened a permanent restaurant or café."},
  {q:"Young visitors like the relaxed ___ more than formal restaurants.", a:["atmosphere"], ev:"they prefer the relaxed atmosphere to formal restaurants", ex:"'Like ... more than' paraphrases 'prefer ... to'."}
 ]},
 {qtype:"Multiple Choice", instr:"Choose the correct letter, A, B, C or D.", items:[
  {q:"For many families in Asia, a visit to the night market is", opts:["a special celebration.","a normal weekly activity.","mainly for tourists.","a religious event."], a:"B", ev:"a regular part of the week rather than a special event", ex:"'Regular part of the week' = 'normal weekly activity'. Temples are mentioned as places where markets grew, so D is a trap."},
  {q:"According to Dr Fenwick, many new night markets began as a way to", opts:["earn money for large companies.","bring activity to quiet parts of the city at night.","replace expensive restaurants.","attract visitors from Asia."], a:"B", ev:"bring life to a quiet area of the city after the shops closed", ex:"'Bring life to a quiet area' = 'bring activity to quiet parts'. She says large companies did NOT start most markets (A)."},
  {q:"What do the organisers in Port Hallam do now?", opts:["They have moved the market to a new place.","They have stopped all live music.","They pay for cleaning and stop the music at ten.","They open the market every night."], a:"C", ev:"Organisers now hire cleaning teams and close the music at ten o'clock", ex:"They hire cleaning teams and close the music at ten. The music stops at a fixed time; it has not been stopped completely (B)."}
 ]}
 ]
},
{
 id:"R55-05", title:"Lessons in the Vegetable Patch", category:"Education", band:5.5, mock:null, mins:15,
 paras:[
 ["A","In a growing number of schools, the playground is not just a place for games. Corners of land that were once covered in grass or concrete are being turned into vegetable gardens, where pupils plant, water and harvest their own food. Supporters say these gardens teach children far more than how to grow carrots."],
 ["B","The idea is not new. In the early twentieth century, many schools kept gardens, and during times of food shortage pupils helped to grow vegetables for their communities. Interest fell in the second half of the century, as schools concentrated on classroom subjects and land was sold for buildings. Over the past fifteen years, however, school gardens have become popular again."],
 ["C","One of the best-known programmes is Grow to Learn, which was started in 2012 by a former primary teacher, Maria Castellano. It now supports more than 600 schools. Each school receives seeds, basic tools and a guidebook, and teachers can attend a two-day training course. Castellano says the most common problem is not a lack of land but a lack of time. \"Teachers are busy, so we design activities that fit into normal lessons,\" she explains."],
 ["D","Gardens can be used to teach many subjects. In maths lessons, pupils measure the growth of plants and calculate the area of a vegetable bed. In science, they learn about soil, insects and the life cycle of plants. Some schools even use the garden for writing lessons, asking pupils to keep a diary of the changes they observe each week."],
 ["E","Researchers have also looked at the effect on children's eating habits. A study by the Brantley Centre for Nutrition followed 1,200 pupils at 24 primary schools for two years. Half of the schools had gardens and half did not. At the end of the study, children at the garden schools ate on average one more portion of vegetables a day than the others. They were also more willing to taste vegetables they had never tried before. The researchers believe that children are more interested in food that they have grown themselves."],
 ["F","Not all projects succeed, though. The biggest difficulty is the summer holiday, which often comes just when many vegetables are ready to pick. Without anyone to water them, plants can die in a few weeks. Some schools solve this by asking families to take turns looking after the garden, while others choose crops such as potatoes and pumpkins that can be harvested in autumn."],
 ["G","Gardens may also help pupils who find classroom learning difficult. Teachers report that some children who are quiet indoors become confident and active outside. As one head teacher put it, \"In the garden, there is no wrong answer. Either the plant grows or it doesn't, and either way you learn something.\""]
 ],
 groups:[
 {qtype:"Note Completion", instr:"Complete the notes below. Write ONE WORD AND/OR A NUMBER from the passage for each answer.", limit:1, items:[
  {q:"Grow to Learn: started in 2012 by a former ___ teacher", a:["primary"], ev:"started in 2012 by a former primary teacher, Maria Castellano", ex:"Paragraph C says Castellano was a former primary teacher."},
  {q:"Grow to Learn: each school is given seeds, tools and a ___", a:["guidebook"], ev:"Each school receives seeds, basic tools and a guidebook", ex:"'Is given' paraphrases 'receives'."},
  {q:"Grow to Learn: main problem for teachers is a lack of ___", a:["time"], ev:"not a lack of land but a lack of time", ex:"Land is the distractor: Castellano says the problem is NOT land but time."},
  {q:"Brantley study: pupils at ___ primary schools", a:["24"], ev:"followed 1,200 pupils at 24 primary schools for two years", ex:"The question asks for schools, not pupils, so 24 is correct and 1,200 is wrong."},
  {q:"Brantley study: garden-school children ate one extra ___ of vegetables a day", a:["portion"], ev:"ate on average one more portion of vegetables a day", ex:"'One extra' = 'one more'. The noun is 'portion'."}
 ]},
 {qtype:"True/False/Not Given", instr:"Do the following statements agree with the information in the passage? Choose TRUE, FALSE or NOT GIVEN.", options:["TRUE","FALSE","NOT GIVEN"], items:[
  {q:"Many schools had gardens in the early 1900s.", a:"TRUE", ev:"In the early twentieth century, many schools kept gardens", ex:"'The early 1900s' means the same as 'the early twentieth century'."},
  {q:"Schools must pay a fee to join Grow to Learn.", a:"NOT GIVEN", ev:"Each school receives seeds, basic tools and a guidebook", ex:"The passage says what schools receive, but never mentions whether they pay anything."},
  {q:"Children at garden schools were less willing to try new vegetables.", a:"FALSE", ev:"They were also more willing to taste vegetables they had never tried before", ex:"The passage says 'more willing', the opposite of 'less willing'."},
  {q:"Some schools ask families to care for the garden during the summer holiday.", a:"TRUE", ev:"asking families to take turns looking after the garden", ex:"'Care for' = 'look after'. This is one solution to the summer holiday problem."}
 ]},
 {qtype:"Short Answer", instr:"Answer the questions below. Write NO MORE THAN TWO WORDS from the passage for each answer.", limit:2, items:[
  {q:"What do some pupils keep to record weekly changes in the garden?", a:["diary","a diary"], ev:"asking pupils to keep a diary of the changes they observe each week", ex:"Paragraph D: in writing lessons pupils keep a diary of the changes they see."},
  {q:"What is the biggest difficulty for school garden projects?", a:["summer holiday","the summer holiday"], ev:"The biggest difficulty is the summer holiday", ex:"Vegetables are often ready to pick during the summer holiday, when nobody is there to water them."},
  {q:"Name ONE crop that schools choose because it can be harvested in autumn.", a:["potatoes","pumpkins"], ev:"choose crops such as potatoes and pumpkins that can be harvested in autumn", ex:"Either potatoes or pumpkins is correct, as both are named in paragraph F."}
 ]}
 ]
},
{
 id:"R55-06", title:"The Last Lighthouse Keepers", category:"Heritage", band:5.5, mock:null, mins:15,
 paras:[
 ["A","For hundreds of years, lighthouses have warned ships of dangerous rocks and coastlines. Today most of them work automatically, but for a long time each light depended on people who lived beside it day and night. These lighthouse keepers formed a small but important profession, and their story says a great deal about how life at sea and on the coast has changed."],
 ["B","The keeper's main job was to make sure the light never went out. Before electricity, lamps burned oil, and the wick had to be trimmed regularly so that the flame stayed bright and did not produce smoke. The large glass lenses had to be cleaned every morning, because even a thin layer of salt or soot could make the light much weaker. Keepers also wound the clockwork machinery that turned the light, sometimes every two hours through the night, and recorded the weather in a logbook."],
 ["C","Life could be very lonely, especially on lighthouses built on rocks far out at sea. On these rock stations, there was no room for families, so keepers usually worked in teams of three and spent several weeks at a time away from home. Supplies arrived by boat, but in bad weather the boat could not land, and keepers sometimes waited for weeks longer than planned. Many passed the time by reading, painting or making models, and some kept small gardens in boxes of soil brought from the land."],
 ["D","On lighthouses on the mainland, conditions were easier. Keepers often lived with their families in cottages next to the tower, and their children went to local schools. Wives frequently helped with the work, and in some cases took over as keeper after their husband's death. Records from the Carrow Point lighthouse show that one woman, Ellen Marsh, kept its light for 31 years in the nineteenth century."],
 ["E","The decline of the profession began in the twentieth century. Electric lamps were more reliable than oil, and new equipment could switch the light on at dusk and off at dawn without human help. From the 1960s onwards, many countries began to automate their lighthouses, and the number of keepers fell quickly. Automation saved money, because a single team of engineers could look after many lights. In many places the last keepers left in the 1980s and 1990s."],
 ["F","Today, satellite navigation means that ships rely much less on lighthouses than they once did, although the lights are still kept as a backup in case electronic systems fail. Many old keepers' cottages have been turned into museums or holiday homes, and some towers are open to visitors. Former keeper Arthur Pennick, who spent 22 years on rock stations, now gives tours. \"People ask if I miss it,\" he says. \"I miss the quiet, but not the storms.\""]
 ],
 groups:[
 {qtype:"Matching Headings", instr:"The passage has six paragraphs, A-F. Choose the correct heading for paragraphs B-F from the list of headings below. There are more headings than paragraphs.", optKey:"roman",
  options:["i  Machines replace people","ii  How lighthouses were built","iii  Keeping the light burning","iv  Family life at coastal stations","v  Training for new keepers","vi  New uses for old lighthouses","vii  Living far from other people","viii  The dangers of sailing at night"], items:[
  {q:"Paragraph B", a:"iii", ev:"The keeper's main job was to make sure the light never went out", ex:"Paragraph B lists the daily tasks needed to keep the light working: trimming the wick, cleaning lenses, winding the machinery."},
  {q:"Paragraph C", a:"vii", ev:"Life could be very lonely, especially on lighthouses built on rocks far out at sea", ex:"'Lonely' and 'far out at sea' match 'living far from other people'."},
  {q:"Paragraph D", a:"iv", ev:"Keepers often lived with their families in cottages next to the tower", ex:"The paragraph is about families on the mainland: children at school and wives helping with the work."},
  {q:"Paragraph E", a:"i", ev:"many countries began to automate their lighthouses, and the number of keepers fell quickly", ex:"Automatic equipment took over the keepers' work, so 'machines replace people' fits."},
  {q:"Paragraph F", a:"vi", ev:"Many old keepers' cottages have been turned into museums or holiday homes", ex:"Paragraph F describes how cottages and towers are used today: museums, holiday homes and tours."}
 ]},
 {qtype:"Sentence Completion", instr:"Complete the sentences below. Write ONE WORD ONLY from the passage for each answer.", limit:1, items:[
  {q:"Before electricity, lighthouse lamps used ___ as fuel.", a:["oil"], ev:"Before electricity, lamps burned oil", ex:"'Used ... as fuel' paraphrases 'burned'."},
  {q:"A thin layer of salt or ___ on the lenses could make the light weaker.", a:["soot"], ev:"even a thin layer of salt or soot could make the light much weaker", ex:"Paragraph B names salt and soot. Smoke is mentioned earlier, but it is not the word in this phrase."},
  {q:"Keepers wrote down information about the weather in a ___.", a:["logbook"], ev:"recorded the weather in a logbook", ex:"'Wrote down' = 'recorded'."},
  {q:"On rock stations, keepers usually worked in teams of ___.", a:["three"], ev:"keepers usually worked in teams of three", ex:"Paragraph C says teams of three. Do not confuse this with 'every two hours' in paragraph B."}
 ]},
 {qtype:"Multiple Choice", instr:"Choose the correct letter, A, B, C or D.", items:[
  {q:"Why did keepers on rock stations sometimes stay longer than planned?", opts:["They wanted to finish their hobbies.","The supply boat could not land in bad weather.","Their families came to visit them.","The clockwork machinery broke down."], a:"B", ev:"in bad weather the boat could not land", ex:"The boat could not land in bad weather, so keepers waited for weeks longer. Hobbies (A) are how they passed the time, not the reason they stayed."},
  {q:"What does the passage say about Ellen Marsh?", opts:["She was the first woman to become a keeper.","She kept the Carrow Point light for more than thirty years.","She taught at a local school.","She worked on a rock station."], a:"B", ev:"kept its light for 31 years in the nineteenth century", ex:"31 years is 'more than thirty years'. The passage never says she was the first woman (A)."},
  {q:"According to paragraph F, lighthouse lights today are", opts:["no longer switched on.","used only as museums.","kept in case electronic systems stop working.","more important than satellite navigation."], a:"C", ev:"the lights are still kept as a backup in case electronic systems fail", ex:"'In case electronic systems fail' = 'in case electronic systems stop working'. Ships rely LESS on lighthouses than before, so D is wrong."}
 ]}
 ]
}
];
