/* ===== READING BANK — band 6.5 (original practice material, written for this app) ===== */
export const SETS = [
{
 id:"R65-01", title:"The Long Road of Paper", category:"History", band:6.5, mock:null, mins:20,
 paras:[
 ["A","Few objects are as ordinary today as a sheet of paper, yet the material took more than a thousand years to travel from its birthplace in China to the workshops of Western Europe. Its journey was not a simple handover from one civilisation to the next. At almost every stage, the people who adopted paper changed the raw materials, the tools and the purposes for which it was used, so that the paper which eventually reached Europe was in many respects a different product from the one first made in East Asia."],
 ["B","Chinese tradition credits a court official named Cai Lun with presenting a method of paper-making to the emperor in the year 105 CE. However, archaeologists have recovered fragments of paper from tombs and watchtowers that appear to be considerably older, suggesting that he improved an existing process rather than inventing it. Early Chinese paper was made from the inner bark of the mulberry tree, from hemp and even from worn-out fishing nets, which were beaten into a pulp, mixed with water and lifted out on a fine screen to dry. At first the material was used mainly for wrapping goods and padding fragile objects. Only gradually did it replace strips of bamboo and expensive silk as the preferred surface for writing."],
 ["C","By the early seventh century, the technique had reached Korea and Japan. Buddhist monks played an important part in this movement, since their monasteries required large numbers of copies of sacred texts. Japanese craftsmen, unable to obtain exactly the same plants as their Chinese teachers, experimented with the fibres of local shrubs and developed sheets that were remarkably thin yet strong. Paper of this kind is still valued by conservators, who use it to repair damaged books and prints all over the world."],
 ["D","The westward spread of paper is often linked to a single dramatic event. According to a popular story, Chinese soldiers captured after a battle near the Talas River in 751 taught the craft to their captors in the city of Samarkand. Many historians now treat this account with caution, regarding it as a convenient legend that simplifies a slower process; paper had probably been carried along the trade routes of Central Asia for some time before the battle. Whatever the precise route, Samarkand soon became famous for the quality of its paper."],
 ["E","From Central Asia the craft moved into the heart of the Islamic world, and a paper mill was operating in Baghdad by the end of the eighth century. Government administrators were among its most enthusiastic supporters. Parchment, made from animal skin, could be scraped clean and rewritten, whereas ink soaked into paper, so any attempt to alter a document left visible damage. Paper was also far cheaper to produce. Because mulberry trees were scarce, papermakers in the region turned instead to linen rags and hemp. Within two centuries, mills had appeared in Damascus, Cairo and across North Africa, and a lively trade in books developed in many cities."],
 ["F","Paper entered Europe through Muslim Spain, and one of the earliest European mills on record was working in the town of Xàtiva in the twelfth century. Christian Europe did not welcome the new material with open arms. Some authorities considered it too fragile for documents that needed to last, and at least one ruler forbade its use for official records, insisting that parchment remain the standard. Such restrictions slowed the adoption of paper but did not stop it."],
 ["G","The decisive changes took place in Italy, particularly in the town of Fabriano during the thirteenth century. There, rags were first left to soak and ferment before being pounded by water-powered hammers, which produced pulp far more quickly than human labour. The pulp was then lifted out on a wire screen, and the sheets were dipped in animal gelatine rather than coated with starch, so that ink did not spread and the paper resisted decay. Papermakers also twisted wire into simple designs on the screen, leaving a faint watermark that identified each mill. When the printing press appeared in the middle of the fifteenth century, Europe therefore already possessed a reliable supply of affordable paper. Without it, printing could hardly have flourished, since a single large book on parchment might require the skins of hundreds of animals."]
 ],
 groups:[
 {qtype:"Matching Headings", instr:"The passage has seven paragraphs, A-G. Choose the correct heading for paragraphs B, C, D, E and G from the list of headings below.", optKey:"roman",
  options:["i  A disputed account of how the craft travelled west","ii  Religious demand and local materials in neighbouring countries","iii  The first use of paper for printing books","iv  A famous inventor reconsidered and some modest early uses","v  Practical and official reasons for welcoming a new material","vi  Technical advances that prepared Europe for a major change","vii  Why European rulers rejected paper for good","viii  The decline of parchment in Central Asia"],
  items:[
  {q:"Paragraph B", a:"iv", ev:"suggesting that he improved an existing process rather than inventing it", ex:"Paragraph B questions whether Cai Lun really invented paper (an inventor reconsidered) and describes its first uses for wrapping and padding (modest early uses)."},
  {q:"Paragraph C", a:"ii", ev:"their monasteries required large numbers of copies of sacred texts", ex:"The monks' need for sacred texts is the religious demand, and the Japanese use of 'local shrubs' is the local materials. Heading viii is wrong: Central Asia is not discussed here."},
  {q:"Paragraph D", a:"i", ev:"regarding it as a convenient legend that simplifies a slower process", ex:"The paragraph presents the Talas story and then explains that historians doubt it, so the account is 'disputed'."},
  {q:"Paragraph E", a:"v", ev:"Government administrators were among its most enthusiastic supporters", ex:"Paper was welcomed because documents could not be altered secretly (an official reason) and because it was cheaper (a practical reason)."},
  {q:"Paragraph G", a:"vi", ev:"Europe therefore already possessed a reliable supply of affordable paper", ex:"The Fabriano improvements meant that paper was ready when printing arrived. Heading iii is a near miss: printing is mentioned, but the paragraph is about the paper-making advances that came before it."}
 ]},
 {qtype:"True/False/Not Given", instr:"Do the following statements agree with the information in the passage? Choose TRUE, FALSE or NOT GIVEN.", options:["TRUE","FALSE","NOT GIVEN"], items:[
  {q:"There is physical evidence that paper was being made in China before the time of Cai Lun.", a:"TRUE", ev:"archaeologists have recovered fragments of paper from tombs and watchtowers that appear to be considerably older", ex:"Fragments that are 'considerably older' than 105 CE are physical evidence of earlier paper-making."},
  {q:"As soon as paper was available in China, it became the usual material for writing.", a:"FALSE", ev:"Only gradually did it replace strips of bamboo and expensive silk as the preferred surface for writing", ex:"'Only gradually' contradicts 'as soon as'. At first paper was mainly used for wrapping and padding."},
  {q:"Japanese paper was exported to China in large quantities.", a:"NOT GIVEN", ev:"developed sheets that were remarkably thin yet strong", ex:"The passage praises Japanese paper and mentions its modern use by conservators, but says nothing about exports to China. It sounds plausible, which is why it is a trap."},
  {q:"Officials in the Islamic world preferred paper partly because changes to a document were easier to detect.", a:"TRUE", ev:"any attempt to alter a document left visible damage", ex:"If any alteration leaves 'visible damage', changes are easier to detect, which is why administrators supported paper."}
 ]},
 {qtype:"Flow-chart Completion", instr:"Complete the flow-chart showing how paper was made in thirteenth-century Fabriano. Write ONE WORD ONLY from the passage for each answer.", limit:1, flow:true, items:[
  {q:"Rags are left to soak and ___", a:["ferment"], ev:"rags were first left to soak and ferment", ex:"Paragraph G gives two actions before pounding: soaking and fermenting."},
  {q:"Rags are pounded into pulp by water-powered ___", a:["hammers"], ev:"pounded by water-powered hammers", ex:"The hammers replaced human labour and made pulp much faster."},
  {q:"Pulp is lifted out on a ___ that may carry a wire design.", a:["screen"], ev:"The pulp was then lifted out on a wire screen", ex:"The screen is where the wire designs were placed to make watermarks."},
  {q:"Sheets are dipped in animal ___ so that ink does not spread.", a:["gelatine"], ev:"the sheets were dipped in animal gelatine rather than coated with starch", ex:"Gelatine replaced starch. 'Starch' is the distractor: it is the older method the Italians abandoned."}
 ]}
 ]
},
{
 id:"R65-02", title:"When the Ice Runs Out", category:"Climate", band:6.5, mock:null, mins:20,
 paras:[
 ["A","Mountain glaciers are often described as the water towers of the world. Throughout the winter they store snowfall in the form of ice, and during the warm, dry months they release it gradually as meltwater, precisely when rivers fed by rain alone would be at their lowest. Hundreds of millions of people in Asia, South America and Europe rely to some degree on this seasonal release for drinking water, for irrigating their crops and for generating hydroelectric power."],
 ["B","Almost every mountain glacier that scientists monitor has been losing mass over recent decades. Higher temperatures lengthen the season during which ice melts, and a growing proportion of precipitation now falls as rain rather than snow, so less new ice forms each winter to replace what is lost. In many ranges, the problem is made worse by dust and soot carried from distant deserts, cities and fires. These particles settle on the ice and darken it, causing the surface to absorb more sunlight and melt faster still."],
 ["C","One of the less intuitive consequences of glacial retreat is that, in its early stages, rivers actually carry more water, not less. As a glacier shrinks rapidly, the additional meltwater swells summer flows, sometimes for several decades. Hydrologists use the term peak water for the moment at which this flow reaches its maximum and begins to fall away as the remaining ice becomes too small to sustain it. The danger is that communities may interpret the temporary abundance as a sign that their water supply is secure, and plan new farms, towns or industries accordingly."],
 ["D","The timing of peak water varies enormously from one place to another. A modelling study led by the hydrologist Imke Halvorsen examined forty-eight river basins and found that many fed by small, low-lying glaciers had already passed their peak, while basins supplied by large glaciers at high altitude might not reach it until the second half of the century. In her words, a single regional average hides very different local stories, and water planners who rely on such averages risk being caught unprepared. Her team also stressed that the models carry considerable uncertainty, because measurements of ice thickness are scarce in many remote ranges, and that estimates are likely to be revised as better observations become available."],
 ["E","Once peak water has passed, the effects downstream are felt most sharply in late summer, the period when glaciers traditionally contributed the largest share of river flow. Farmers who need to water their crops at the end of the growing season are particularly exposed. Operators of hydroelectric plants face a supply that is less predictable from year to year, which complicates the management of national electricity grids. Ecosystems are affected as well: cold meltwater keeps mountain streams cool, and as its contribution declines, stream temperatures rise, threatening certain fish and insects that cannot survive in warmer water."],
 ["F","Retreating ice also creates hazards unrelated to scarcity. As glaciers melt back, water often collects in lakes held in place by loose ridges of rock and earth left behind by the ice. If such a ridge gives way, perhaps after a landslide or an earthquake, the lake can empty within hours, sending a destructive flood into the valleys below. Several governments now use satellite images to watch the growth of these lakes and have installed warning systems in villages downstream."],
 ["G","Communities are responding in various ways. Some authorities are building new reservoirs to replace the storage that glaciers once provided, although such projects are costly and frequently controversial, since they flood land and disrupt rivers. In certain high, dry valleys, villagers channel winter stream water into shaded places where it freezes into large mounds of ice that melt slowly in spring, a simple way of storing water until it is needed. Others are investing in more efficient irrigation. Yet engineers caution that no technical measure can fully replace the storage capacity of a large glacier, and Halvorsen argues that planning must begin well before peak water has passed, not after."]
 ],
 groups:[
 {qtype:"Matching Information", instr:"The passage has seven paragraphs, A-G. Which paragraph contains the following information? Write the correct letter, A-G.", options:["A","B","C","D","E","F","G"], items:[
  {q:"a warning that a short-term increase in supply could lead to poor decisions", a:"C", ev:"communities may interpret the temporary abundance as a sign that their water supply is secure", ex:"Paragraph C explains that higher flows before peak water may persuade people to plan new farms or towns. 'Poor decisions' paraphrases this misreading."},
  {q:"an example of a low-technology method of saving water for later use", a:"G", ev:"a simple way of storing water until it is needed", ex:"Freezing stream water into mounds of ice is the low-technology method. Reservoirs (also in G) are large engineering projects, but the answer is still G."},
  {q:"a risk created by melting ice that has nothing to do with water shortages", a:"F", ev:"Retreating ice also creates hazards unrelated to scarcity", ex:"Floods from bursting glacial lakes are a danger unrelated to scarcity, which is the paraphrase of 'water shortages'."},
  {q:"an explanation of why some glaciers absorb more heat from the sun", a:"B", ev:"causing the surface to absorb more sunlight and melt faster still", ex:"Dust and soot darken the ice so it absorbs more sunlight. The question uses 'heat from the sun' to paraphrase 'sunlight'."}
 ]},
 {qtype:"Multiple Choice", instr:"Choose the correct letter, A, B, C or D.", items:[
  {q:"According to paragraph A, why are glaciers so valuable to people living downstream?", opts:["They prevent rivers from flooding during wet seasons.","They provide water at the time of year when other sources are lowest.","They supply most of the world's drinking water.","They store rainwater for use in winter."], a:"B", ev:"precisely when rivers fed by rain alone would be at their lowest", ex:"Glaciers release water in warm, dry months when rain-fed rivers are low. C exaggerates ('most of the world's'); D reverses the seasons."},
  {q:"What did Halvorsen's study show?", opts:["Most river basins have already passed peak water.","Peak water will occur at the same time across a whole region.","Basins fed by large, high glaciers will reach peak water later.","Regional averages are the most reliable basis for planning."], a:"C", ev:"basins supplied by large glaciers at high altitude might not reach it until the second half of the century", ex:"Large, high glaciers peak later than small, low ones. Option D is the opposite of her view that averages hide local differences; A is not stated ('many', not 'most')."},
  {q:"Which group does the writer identify as especially vulnerable after peak water?", opts:["farmers who irrigate late in the growing season","engineers who design national electricity grids","villagers living beside glacial lakes","fishermen working on large lowland rivers"], a:"A", ev:"Farmers who need to water their crops at the end of the growing season are particularly exposed", ex:"'Particularly exposed' = 'especially vulnerable'. Villagers near lakes (C) face a flood risk, but this is in paragraph F and is not linked to peak water."},
  {q:"What does the writer say about building new reservoirs?", opts:["It is the most effective way to replace glacier storage.","It is expensive and often meets opposition.","It has been abandoned by most authorities.","It is cheaper than improving irrigation."], a:"B", ev:"such projects are costly and frequently controversial", ex:"'Costly' = expensive; 'frequently controversial' = often meets opposition. A is contradicted by the engineers' warning that nothing fully replaces a glacier."}
 ]},
 {qtype:"Summary Completion", instr:"Complete the summary below. Write NO MORE THAN TWO WORDS from the passage for each answer.", limit:2, items:[
  {q:"Glaciers are shrinking partly because more precipitation now arrives as ___ instead of snow.", a:["rain"], ev:"a growing proportion of precipitation now falls as rain rather than snow", ex:"'Instead of snow' paraphrases 'rather than snow'; the missing word is rain."},
  {q:"At first, retreat increases river flow, until a point known as ___ is reached.", a:["peak water"], ev:"Hydrologists use the term peak water for the moment at which this flow reaches its maximum", ex:"Peak water is the technical term for the maximum flow before decline."},
  {q:"Afterwards, power companies must deal with a supply that is less ___ .", a:["predictable"], ev:"a supply that is less predictable from year to year", ex:"Hydroelectric operators face a less predictable supply."},
  {q:"As streams lose cold meltwater, rising temperatures endanger some fish and ___ .", a:["insects"], ev:"threatening certain fish and insects that cannot survive in warmer water", ex:"Paragraph E names fish and insects as the threatened animals."},
  {q:"Several governments monitor dangerous glacial lakes using ___ .", a:["satellite images","satellite"], ev:"use satellite images to watch the growth of these lakes", ex:"Satellite images are used to watch the lakes grow; warning systems are a separate measure installed in villages."}
 ]}
 ]
},
{
 id:"R65-03", title:"Minds in Eight Arms", category:"Biology", band:6.5, mock:null, mins:20,
 paras:[
 ["A","Stories of octopuses escaping from aquarium tanks, raiding neighbouring enclosures at night and returning before morning have circulated for decades. Until fairly recently, most scientists treated such tales as entertaining anecdotes rather than serious evidence. Over the past thirty years, however, a growing body of research has led many biologists to accept that octopuses possess a form of intelligence that rivals that of some birds and mammals, even if there is still considerable disagreement about what that intelligence consists of."],
 ["B","Octopuses belong to a group of molluscs known as cephalopods, which also includes squid and cuttlefish. Their closest relatives are snails and clams, animals not generally associated with complex behaviour. Many researchers believe that the key to the octopus's mental abilities lies in its evolutionary history. Its distant ancestors lost the protective shell that most molluscs still carry, leaving them soft-bodied and vulnerable. To survive, they had to become skilled at hunting, hiding and escaping, and these demands may have favoured larger and more flexible nervous systems."],
 ["C","Laboratory experiments have provided much of the evidence. In a series of trials at the Marlow Bay Marine Station, the comparative psychologist Tomas Rehnberg presented common octopuses with crabs sealed inside glass jars. Within a few sessions most animals had learned to unscrew the lids, and several became noticeably faster with practice. Rehnberg was particularly struck by one individual which, after failing to open a jar by pulling at it, paused and then began twisting instead. He also recorded octopuses repeatedly pushing a floating bottle into the current of the water inlet and catching it as it returned, behaviour which he describes as a form of play because it brought the animal no food or other obvious reward."],
 ["D","The structure of the octopus nervous system is unusual. An octopus has roughly five hundred million neurons, a number comparable to that of a dog, but about two-thirds of them are located not in its brain but in its arms. According to the neurobiologist Adaeze Okonkwo, this arrangement means that each arm enjoys a surprising degree of independence. In her experiments, arms that had been separated from the central brain continued to reach towards food and grasp it. She suggests that the brain sets general goals while the arms work out many of the details themselves, a division of labour that has no close equivalent in vertebrates."],
 ["E","Not everyone is convinced that such findings demonstrate intelligence in any meaningful sense. The behavioural ecologist Marguerite Calloway argues that much of what is reported could result from trial and error combined with natural curiosity, rather than from planning or understanding. She also warns that laboratory tests are often designed around human ideas of cleverness, such as solving puzzles with tools, and may therefore reward animals whose abilities happen to resemble our own while overlooking others. In her view, researchers should study how octopuses behave in the wild before drawing conclusions from life in a tank."],
 ["F","Perhaps the greatest puzzle is why such abilities evolved at all. Most animals regarded as intelligent, such as apes, dolphins and crows, live for many years in social groups and learn a great deal from others. Octopuses, by contrast, are largely solitary, and many species live for only one or two years. The young usually never meet their parents, so each generation must discover the world for itself. The evolutionary biologist Sofia Lindqvist believes this shows that intelligence arose in octopuses entirely separately from its development in vertebrates, driven by the demands of hunting and avoiding predators rather than by social life."],
 ["G","For the time being, the octopus remains something of a scientific mystery. What seems increasingly clear is that intelligence need not take a single form, and that a creature whose last common ancestor with humans lived more than half a billion years ago can arrive at some strikingly similar solutions by a very different route. Studying it may therefore help scientists understand not only octopuses but also the range of ways in which minds can be built."]
 ],
 groups:[
 {qtype:"Matching Features", instr:"Look at the following statements and the list of researchers below. Match each statement with the correct researcher, A-D. You may use any letter more than once.", optKey:"letter",
  options:["A  Tomas Rehnberg","B  Adaeze Okonkwo","C  Marguerite Calloway","D  Sofia Lindqvist"],
  items:[
  {q:"An octopus changed its strategy after an unsuccessful attempt.", a:"A", ev:"after failing to open a jar by pulling at it, paused and then began twisting instead", ex:"Rehnberg observed the octopus switch from pulling to twisting. 'Unsuccessful attempt' paraphrases 'after failing'."},
  {q:"Parts of the body can perform tasks without direction from the brain.", a:"B", ev:"arms that had been separated from the central brain continued to reach towards food and grasp it", ex:"Okonkwo's separated arms still reached for food, showing they act without the brain's direction."},
  {q:"Experiments may be biased towards abilities similar to those of humans.", a:"C", ev:"may therefore reward animals whose abilities happen to resemble our own", ex:"Calloway warns that tests are built around human ideas of cleverness, which is a form of bias."},
  {q:"Octopus intelligence developed independently of intelligence in animals with backbones.", a:"D", ev:"intelligence arose in octopuses entirely separately from its development in vertebrates", ex:"'Animals with backbones' = vertebrates; 'independently' = 'entirely separately'."},
  {q:"Octopuses sometimes carry out activities that bring them no practical benefit.", a:"A", ev:"it brought the animal no food or other obvious reward", ex:"Rehnberg describes the bottle game as play because it gave no food or reward. Calloway mentions curiosity, but she does not describe this behaviour."}
 ]},
 {qtype:"Multiple Choice", instr:"Choose the correct letter, A, B, C or D.", items:[
  {q:"What does the writer say about stories of octopuses escaping from tanks?", opts:["They have been shown to be untrue.","They were once not taken seriously by scientists.","They first appeared about thirty years ago.","They are the main evidence for octopus intelligence."], a:"B", ev:"most scientists treated such tales as entertaining anecdotes rather than serious evidence", ex:"Treating the stories as 'anecdotes rather than serious evidence' means scientists did not take them seriously. The thirty years (C) refers to the research, not the stories."},
  {q:"Why does the writer find the evolution of octopus intelligence puzzling?", opts:["Octopuses are closely related to intelligent mammals.","Octopuses have fewer neurons than other clever animals.","Octopuses lack the long lives and social learning seen in other intelligent species.","Octopuses are rarely forced to hunt or avoid predators."], a:"C", ev:"Octopuses, by contrast, are largely solitary, and many species live for only one or two years", ex:"Other intelligent animals live long and learn socially; octopuses do neither, which makes their intelligence surprising. B is wrong: their neuron count is comparable to a dog's."},
  {q:"What is the main point of the final paragraph?", opts:["Octopuses are more intelligent than humans in some respects.","Research on octopuses should be reduced until more is known.","Octopuses show that intelligence can evolve in more than one way.","Humans and octopuses share a recent common ancestor."], a:"C", ev:"intelligence need not take a single form", ex:"The writer concludes that minds can be built in different ways. D contradicts the passage: the common ancestor lived over half a billion years ago."}
 ]},
 {qtype:"Sentence Completion", instr:"Complete the sentences below. Write NO MORE THAN THREE WORDS from the passage for each answer.", limit:3, items:[
  {q:"Squid, cuttlefish and octopuses are all members of a group called ___ .", a:["cephalopods"], ev:"a group of molluscs known as cephalopods, which also includes squid and cuttlefish", ex:"The group name is given directly; note that 'molluscs' is the wider category and would not fit the sentence."},
  {q:"Early octopus ancestors became vulnerable after they no longer had a ___ .", a:["protective shell","shell"], ev:"Its distant ancestors lost the protective shell that most molluscs still carry", ex:"'No longer had' paraphrases 'lost'."},
  {q:"In Rehnberg's experiments, octopuses learned to remove the ___ in order to reach crabs.", a:["lids"], ev:"most animals had learned to unscrew the lids", ex:"The crabs were inside glass jars, and the octopuses learned to unscrew the lids."},
  {q:"Most of an octopus's neurons are found in its ___ rather than in its brain.", a:["arms"], ev:"about two-thirds of them are located not in its brain but in its arms", ex:"Two-thirds is 'most'. The sentence paraphrases 'not in its brain but in its arms'."},
  {q:"Calloway believes that much octopus behaviour may be explained by ___ together with curiosity.", a:["trial and error"], ev:"could result from trial and error combined with natural curiosity", ex:"'Together with' paraphrases 'combined with'. 'Planning' is the distractor: Calloway says behaviour may NOT come from planning."}
 ]}
 ]
},
{
 id:"R65-04", title:"Working Longer, Working Differently", category:"Society", band:6.5, mock:null, mins:20,
 paras:[
 ["A","Across much of the developed world, two trends are reshaping the labour market at the same time: people are living longer, and fewer children are being born. As a result, the proportion of the population over sixty-five is rising steadily while the number of people of working age is beginning to shrink. Employers who, a generation ago, encouraged staff to retire early in order to make room for younger recruits now find themselves struggling to fill vacancies. Some commentators describe this situation as a looming catastrophe. I would argue that it is better understood as a challenge that requires us to rethink how work is organised."],
 ["B","A common objection to employing older people is that their productivity declines with age. It is true that certain abilities, such as processing speed, tend to fall modestly from middle age onwards. Yet other qualities, including judgement, vocabulary and the ability to handle difficult customers, often continue to improve well into a person's sixties. Studies of teams that combine younger and older members frequently find that they perform better than teams drawn from a single age group. In my view, the belief that older employees are simply less effective is largely unfounded, and it survives mainly because of stereotypes rather than evidence."],
 ["C","Where jobs are physically demanding, relatively small changes can make a considerable difference. When Brenner Logistics, a medium-sized distribution company, examined why experienced warehouse staff were leaving, it found that many were suffering from back and joint pain. The firm installed adjustable tables, provided mechanical lifting aids and laid special flooring designed to reduce strain on the legs. The total cost was modest, yet within two years productivity had risen by 7 per cent and the number of days lost to sickness had fallen sharply. Significantly, the gains were recorded among workers of every age, not only the oldest. This suggests that adjustments made with older staff in mind frequently benefit everyone."],
 ["D","Flexibility is another area in which many organisations lag behind. A survey of four thousand employers carried out by the Halden Institute for Work and Ageing found that only 28 per cent offered any form of phased retirement, in which employees gradually reduce their hours over several years. In contrast, 61 per cent of workers over fifty-five told researchers that they would remain in employment longer if they were allowed to work part-time. Employers who refuse such requests are, I believe, wasting a valuable opportunity to retain skilled people."],
 ["E","Training presents a similar picture. Older employees are offered fewer opportunities to learn new skills than their younger colleagues, often because managers assume that the investment will not pay off before the person retires. This reasoning ignores the fact that older workers change jobs less frequently, so the skills they acquire are more likely to remain within the organisation. Some companies have introduced schemes known as reverse mentoring, in which younger staff help older colleagues develop digital skills, while the older employees in turn share their knowledge of customers and of how the business really works."],
 ["F","That knowledge is easily lost. When experienced employees retire abruptly, they take with them a great deal of tacit knowledge: an understanding of procedures, relationships and past mistakes that has never been written down. To reduce this risk, a number of firms now arrange handover periods in which a retiring employee works alongside his or her successor for six months. Such arrangements are inexpensive compared with the cost of repeating errors that a departing colleague could easily have prevented."],
 ["G","Many governments have responded to population ageing by raising the age at which people can claim a state pension. This is probably necessary, but it is far from sufficient. Unless workplaces change, higher pension ages may simply force people to remain in jobs they are no longer able to do well, or leave them unemployed and without an income. The greatest obstacle, in my opinion, is not the ability of older workers but the attitudes of those who employ them. Nor should the issue be presented as a contest between young and old: workplaces that make room for every generation are likely to be better places for all of them."]
 ],
 groups:[
 {qtype:"Yes/No/Not Given", instr:"Do the following statements agree with the views of the writer? Choose YES if the statement agrees with the views of the writer, NO if the statement contradicts the views of the writer, NOT GIVEN if it is impossible to say what the writer thinks about this.", options:["YES","NO","NOT GIVEN"], items:[
  {q:"The ageing of the population should be seen as an economic disaster.", a:"NO", ev:"I would argue that it is better understood as a challenge", ex:"The writer reports that some commentators call it a catastrophe, but argues instead that it is a challenge. That contradicts the statement."},
  {q:"The idea that older employees work less effectively has little basis in fact.", a:"YES", ev:"the belief that older employees are simply less effective is largely unfounded", ex:"'Has little basis in fact' paraphrases 'largely unfounded', and the writer adds that it survives because of stereotypes rather than evidence."},
  {q:"Older workers adapt to new technology more quickly than most people expect.", a:"NOT GIVEN", ev:"younger staff help older colleagues develop digital skills", ex:"Digital skills are mentioned only in the context of reverse mentoring. The writer gives no view on how quickly older workers adapt to technology."},
  {q:"Raising the state pension age will be enough to deal with population ageing.", a:"NO", ev:"This is probably necessary, but it is far from sufficient", ex:"'Far from sufficient' directly contradicts 'enough'. Note that the writer does accept it is probably necessary."},
  {q:"Companies that employ many older workers will eventually earn higher profits than their competitors.", a:"NOT GIVEN", ev:"Employers who refuse such requests are, I believe, wasting a valuable opportunity to retain skilled people", ex:"The writer believes employers lose skilled staff, but never compares the profits of different companies. This plausible conclusion goes beyond the text."}
 ]},
 {qtype:"Note Completion", instr:"Complete the notes below. Write NO MORE THAN TWO WORDS AND/OR A NUMBER from the passage for each answer.", limit:2, items:[
  {q:"Brenner Logistics: staff were leaving because of back and ___", a:["joint pain"], ev:"many were suffering from back and joint pain", ex:"The notes complete the phrase 'back and joint pain'."},
  {q:"Changes: adjustable tables, mechanical lifting aids and special ___", a:["flooring"], ev:"laid special flooring designed to reduce strain on the legs", ex:"The third change was flooring designed to reduce strain."},
  {q:"Result after two years: productivity up by ___ per cent", a:["7"], ev:"productivity had risen by 7 per cent", ex:"The figure is 7. Do not confuse it with the survey percentages in paragraph D (28 and 61)."},
  {q:"Halden Institute survey: phased retirement offered by ___ per cent of employers", a:["28"], ev:"only 28 per cent offered any form of phased retirement", ex:"28 per cent of employers offered phased retirement; 61 per cent is the proportion of older workers who wanted part-time work."}
 ]},
 {qtype:"Short Answer", instr:"Answer the questions below. Write NO MORE THAN THREE WORDS AND/OR A NUMBER from the passage for each answer.", limit:3, items:[
  {q:"Which mental ability does the writer say tends to decline slightly from middle age?", a:["processing speed"], ev:"such as processing speed, tend to fall modestly from middle age onwards", ex:"'Decline slightly' paraphrases 'fall modestly'. Judgement and vocabulary are qualities that improve, so they are distractors."},
  {q:"What do younger employees help older colleagues to develop in reverse mentoring schemes?", a:["digital skills"], ev:"younger staff help older colleagues develop digital skills", ex:"In reverse mentoring the usual direction is reversed: the young teach digital skills."},
  {q:"What type of knowledge is lost when experienced staff leave suddenly?", a:["tacit knowledge","tacit"], ev:"they take with them a great deal of tacit knowledge", ex:"'Leave suddenly' paraphrases 'retire abruptly'. The passage defines tacit knowledge as understanding that has never been written down."},
  {q:"For how long do some retiring employees work with the person replacing them?", a:["six months","6 months"], ev:"works alongside his or her successor for six months", ex:"'The person replacing them' paraphrases 'successor'; the period is six months."}
 ]}
 ]
},
{
 id:"R65-05", title:"Testing the Four-Day Week", category:"Business", band:6.5, mock:null, mins:20,
 paras:[
 ["A","Not long ago, the idea that employees might work four days a week without losing any pay was regarded as an eccentric proposal with little chance of being taken seriously. In recent years, however, it has moved steadily into the mainstream, and governments and businesses in several countries have begun to test it in practice. One of the most detailed experiments took place in the region of Northvale, where the Centre for Working Time Research at Ashgrove University coordinated a six-month trial involving sixty-one organisations and around 2,900 employees."],
 ["B","The trial was based on a simple bargain. Staff continued to receive their full salary while working roughly 80 per cent of their previous hours, and in return they committed themselves to maintaining the same level of output. Every organisation joined voluntarily, after responding to a public invitation, and each received two months of preparatory workshops on how to reorganise its work. Companies were free to design their own schedules; contrary to popular assumption, not all of them simply gave everyone Friday off."],
 ["C","The headline results attracted considerable attention. Four organisations withdrew before the six months were over, but of the fifty-seven that completed the trial, fifty-one decided to keep the shorter week afterwards. Average revenue rose slightly, by 1.4 per cent compared with the same period in the previous year, suggesting that output had not suffered. Sickness absence fell by around a third and fewer employees resigned. In questionnaires, a large majority of staff reported lower levels of stress and said that they slept better."],
 ["D","Behind these averages, however, lay considerable variation between sectors. Software and marketing firms found the transition comparatively easy: most achieved their savings by holding fewer and shorter meetings, and their staff reported markedly less exhaustion. Manufacturers could not simply switch off their machines for an extra day, so several introduced overlapping shifts that kept production lines running; output was maintained, although planning the rotas proved complicated. Care homes faced the greatest difficulty, because residents need attention around the clock. They were obliged to recruit additional staff, and their costs rose by 9 per cent, although this was partly offset by lower spending on temporary agency workers. Shops, meanwhile, relied on staggered days off arranged by each team, so that stores could remain open six days a week."],
 ["E","Professor Helena Marsh, who led the research team, believes that the findings are strong enough to justify introducing the four-day week much more widely. In her view, the trial showed that a substantial part of the traditional working week is lost to unnecessary meetings, interruptions and poorly organised tasks. Removing this waste, she argues, allows employees to achieve as much in four days as they previously did in five, while returning to work refreshed after a longer weekend."],
 ["F","Other experts are more cautious. The labour economist Rafael Ostrowski points out that the organisations which volunteered were probably those most confident that the scheme would succeed, and therefore cannot be considered typical of businesses as a whole. He adds that six months may be too short to rule out a novelty effect, in which enthusiasm for a new arrangement temporarily raises performance. Nadia Farouk, a researcher for a federation of trade unions, supports shorter working hours in principle but notes that some participants described squeezing an unchanged workload into fewer days, skipping breaks and answering emails in the evening. A shorter week, she warns, can easily become a more intense one. Gareth Lowe, who represents an association of small employers, questions whether firms with only a handful of staff could cover the gaps left by an extra day off without hiring people they cannot afford."],
 ["G","The Northvale trial does not settle the debate, but it does change its terms. It suggests that, in the right circumstances, a four-day week can work without harming output, while making clear that those circumstances differ greatly from one sector to another. The most useful question may therefore be not whether the four-day week works, but where, for whom and under what conditions. A second trial, lasting two years and including a larger number of small firms, is already being planned."]
 ],
 groups:[
 {qtype:"True/False/Not Given", instr:"Do the following statements agree with the information in the passage? Choose TRUE, FALSE or NOT GIVEN.", options:["TRUE","FALSE","NOT GIVEN"], items:[
  {q:"No organisation was required to take part in the Northvale trial.", a:"TRUE", ev:"Every organisation joined voluntarily", ex:"Joining 'voluntarily' means that no organisation was required to participate."},
  {q:"Employees in the trial accepted a reduction in their salary.", a:"FALSE", ev:"Staff continued to receive their full salary", ex:"Hours were reduced to about 80 per cent, but pay was not. The figure of 80 per cent is a trap because it refers to hours."},
  {q:"The organisations that left the trial early did so because their revenue had fallen.", a:"NOT GIVEN", ev:"Four organisations withdrew before the six months were over", ex:"The passage states that four organisations withdrew but gives no reason. Falling revenue is a plausible guess, but the text does not support it."},
  {q:"Most of the organisations that finished the trial chose to continue with a four-day week.", a:"TRUE", ev:"of the fifty-seven that completed the trial, fifty-one decided to keep the shorter week afterwards", ex:"Fifty-one out of fifty-seven is a clear majority."}
 ]},
 {qtype:"Table Completion", instr:"Complete the table below. Write NO MORE THAN TWO WORDS AND/OR A NUMBER from the passage for each answer.", limit:2,
  table:{head:["Sector","How the change was managed","Outcome"], rows:[
   ["Software and marketing","fewer and shorter [1]","staff felt much less [2]"],
   ["Manufacturing","[3] shifts","output maintained; rotas hard to plan"],
   ["Care homes","additional staff recruited","costs up by [4] per cent"],
   ["Shops","[5] days off arranged by teams","open six days a week"]]},
  items:[
  {q:"Software and marketing – method: ___", a:["meetings"], ev:"most achieved their savings by holding fewer and shorter meetings", ex:"These firms saved time by cutting the number and length of meetings."},
  {q:"Software and marketing – outcome: less ___", a:["exhaustion"], ev:"their staff reported markedly less exhaustion", ex:"'Felt much less' paraphrases 'reported markedly less'. 'Stress' appears in paragraph C as a general result, but the sector-specific word is exhaustion."},
  {q:"Manufacturing – method: ___ shifts", a:["overlapping"], ev:"several introduced overlapping shifts that kept production lines running", ex:"Overlapping shifts kept machines running even though each worker had an extra day off."},
  {q:"Care homes – cost increase: ___ per cent", a:["9"], ev:"their costs rose by 9 per cent", ex:"Costs rose by 9 per cent. Do not confuse this with the 1.4 per cent rise in average revenue."},
  {q:"Shops – method: ___ days off", a:["staggered"], ev:"Shops, meanwhile, relied on staggered days off arranged by each team", ex:"Staggered days off meant different staff were absent on different days."}
 ]},
 {qtype:"Matching Features", instr:"Look at the following statements and the list of people below. Match each statement with the correct person, A-D.", optKey:"letter",
  options:["A  Helena Marsh","B  Rafael Ostrowski","C  Nadia Farouk","D  Gareth Lowe"],
  items:[
  {q:"The participants in the trial may not be representative of employers in general.", a:"B", ev:"cannot be considered typical of businesses as a whole", ex:"Ostrowski argues that confident volunteers are not typical. 'Representative' paraphrases 'typical'."},
  {q:"Reducing working days could lead to greater pressure on employees.", a:"C", ev:"A shorter week, she warns, can easily become a more intense one", ex:"Farouk warns of work intensification. Although she supports shorter hours in principle, this statement matches her warning."},
  {q:"The evidence supports a far broader adoption of the four-day week.", a:"A", ev:"the findings are strong enough to justify introducing the four-day week much more widely", ex:"Marsh, who led the research, believes the results justify wider introduction."},
  {q:"Very small businesses might struggle with the cost of the arrangement.", a:"D", ev:"without hiring people they cannot afford", ex:"Lowe doubts that firms with a handful of staff can afford to cover the extra day off."}
 ]}
 ]
},
{
 id:"R65-06", title:"Saving the Past in Pixels", category:"Heritage", band:6.5, mock:null, mins:20,
 paras:[
 ["A","Archives contain some of the most fragile objects that any institution is asked to look after. Medieval charters written on parchment can crack if they are handled carelessly; documents written in iron-based ink slowly corrode the paper beneath them; newspapers printed on cheap, acidic paper turn yellow and crumble at the edges; and early sound recordings on magnetic tape lose their signal year by year. Faced with this gradual decay, archives around the world have embarked on ambitious programmes to digitise their collections. I welcome these efforts, but I believe that the enthusiasm surrounding them sometimes obscures real risks."],
 ["B","The benefits are easy to see. When the Kestrel County Record Office placed its nineteenth-century parish registers online, the number of people consulting them rose from a few hundred visitors a year in the reading room to many thousands of users from more than forty countries. Family historians who could never have travelled to the office were suddenly able to trace their ancestors from home. At the same time, because researchers no longer needed to handle the registers themselves, the volumes suffered far less wear, and staff could store them in conditions designed to slow their decline."],
 ["C","Digitisation can also reveal information that the human eye cannot detect. A technique known as multispectral imaging photographs a document under different wavelengths of light, some of them invisible, and can bring faded or deliberately erased writing back into view. Using this method, scholars have recovered older texts from parchment that was scraped clean and reused centuries ago. Meanwhile, software trained to read historical handwriting is beginning to turn millions of scanned pages into searchable text, allowing researchers to find a single name in a collection that would once have taken years to read."],
 ["D","Yet digital copies are far less permanent than many people assume. File formats become obsolete, storage media degrade, and the software needed to open a file may no longer exist a few decades after it was created. To keep their collections readable, archives must regularly migrate data to new formats and systems, a task that demands skilled staff and continuing funding rather than a single grant. There is an uncomfortable irony here: a charter that has survived eight hundred years in a wooden box could outlast its own digital image unless that image is actively maintained. Digital preservation, in other words, is a process rather than an event."],
 ["E","A further difficulty concerns what is chosen for digitisation in the first place. Because scanning is expensive, only a small fraction of most collections can be converted, and institutions understandably begin with the material that is most popular or most likely to attract sponsors. Records of minority communities, documents in less widely spoken languages and collections that have never been properly catalogued are often left until last. I fear that such material may become even less visible than before, since researchers increasingly behave as though anything that cannot be found online does not exist."],
 ["F","Perhaps the most serious danger is the belief that a digital copy can take the place of the original. Some funding bodies have already questioned why they should continue to pay for the conservation of documents that are available on screen, and in the past several libraries disposed of bound newspapers once they had been copied onto film. This, in my view, is a grave mistake. An original document carries evidence that no image can fully capture: the composition of its paper, the structure of its binding, the marks left by previous owners, even traces of the substances it came into contact with."],
 ["G","Digitisation also raises ethical questions. Many archives hold records that contain personal details, such as court proceedings, school reports or the registers of hospitals. Publishing such material online makes it accessible to anyone, anywhere, and effectively permanent, which may cause distress to the people named in them or to their descendants. Archives therefore need clear policies on what can be released and when. None of this means that digitisation should be slowed or abandoned. It means that it should be treated as a complement to the careful preservation of originals, and never as a substitute for it."]
 ],
 groups:[
 {qtype:"Matching Headings", instr:"The passage has seven paragraphs, A-G. Choose the correct heading for paragraphs B-F from the list of headings below.", optKey:"roman",
  options:["i  Making the unseen visible again","ii  Wider access and reduced damage to originals","iii  The ongoing effort needed to keep digital copies usable","iv  How decisions about what to scan can distort the record","v  A mistaken assumption that copies can replace originals","vi  Materials that are especially vulnerable to decay","vii  Why digital files last longer than paper","viii  Protecting the privacy of people named in records"],
  items:[
  {q:"Paragraph B", a:"ii", ev:"the volumes suffered far less wear", ex:"Paragraph B describes two benefits: many more users (wider access) and less handling of the registers (reduced damage)."},
  {q:"Paragraph C", a:"i", ev:"can bring faded or deliberately erased writing back into view", ex:"Multispectral imaging reveals writing that cannot be seen, so the paragraph is about making the unseen visible again."},
  {q:"Paragraph D", a:"iii", ev:"Digital preservation, in other words, is a process rather than an event", ex:"The paragraph stresses that data must be migrated regularly with continuing funding. Heading vii is the near miss: it states the opposite of the paragraph's argument."},
  {q:"Paragraph E", a:"iv", ev:"institutions understandably begin with the material that is most popular or most likely to attract sponsors", ex:"Choosing popular material first leaves other records less visible, which distorts what researchers see of the past."},
  {q:"Paragraph F", a:"v", ev:"the belief that a digital copy can take the place of the original", ex:"The writer calls this belief 'a grave mistake', matching 'a mistaken assumption'."}
 ]},
 {qtype:"Yes/No/Not Given", instr:"Do the following statements agree with the views of the writer? Choose YES if the statement agrees with the views of the writer, NO if the statement contradicts the views of the writer, NOT GIVEN if it is impossible to say what the writer thinks about this.", options:["YES","NO","NOT GIVEN"], items:[
  {q:"Programmes to digitise archives deserve support even though they involve risks.", a:"YES", ev:"I welcome these efforts, but I believe that the enthusiasm surrounding them sometimes obscures real risks", ex:"The writer welcomes digitisation while pointing out risks, and repeats in paragraph G that it should not be slowed or abandoned."},
  {q:"Software that reads historical handwriting is now more accurate than human experts.", a:"NOT GIVEN", ev:"software trained to read historical handwriting is beginning to turn millions of scanned pages into searchable text", ex:"The writer says this software is 'beginning' to make pages searchable but never compares its accuracy with that of human readers."},
  {q:"Once a document has been digitised, there is little reason to keep the original.", a:"NO", ev:"This, in my view, is a grave mistake", ex:"The writer strongly rejects the idea that copies can replace originals, arguing that originals contain evidence images cannot capture."},
  {q:"Records that are not available online are likely to be overlooked by researchers.", a:"YES", ev:"researchers increasingly behave as though anything that cannot be found online does not exist", ex:"The writer fears that material not online becomes 'even less visible', which means it will be overlooked."}
 ]},
 {qtype:"Summary Completion", instr:"Complete the summary below. Write ONE WORD ONLY from the passage for each answer.", limit:1, items:[
  {q:"Multispectral imaging photographs documents using various ___ of light, including some that cannot be seen.", a:["wavelengths"], ev:"photographs a document under different wavelengths of light, some of them invisible", ex:"'Various' paraphrases 'different', and 'cannot be seen' paraphrases 'invisible'."},
  {q:"However, digital files are not permanent: their formats can become ___ over time.", a:["obsolete"], ev:"File formats become obsolete", ex:"Obsolete means no longer in use, which is the first threat listed in paragraph D."},
  {q:"Archives must therefore ___ their data to new systems at regular intervals.", a:["migrate"], ev:"archives must regularly migrate data to new formats and systems", ex:"'At regular intervals' paraphrases 'regularly'; the verb needed is migrate."},
  {q:"This work depends on skilled staff and continuing ___ rather than one-off grants.", a:["funding"], ev:"a task that demands skilled staff and continuing funding rather than a single grant", ex:"'One-off grants' paraphrases 'a single grant'. The word that fits after 'continuing' is funding."}
 ]}
 ]
}
];
