/* ===== READING BANK — band 7.5 practice sets (original material written for this app) ===== */
export const SETS = [
{
 id:"R75-01", title:"Dimming the Sun: the Ethics of Solar Geoengineering", category:"Climate", band:7.5, mock:null, mins:20,
 paras:[
 ["A","In the catalogue of proposals for dealing with a warming planet, few provoke as much unease as the idea of deliberately dimming the sun. Solar geoengineering, in its most widely discussed form, would involve releasing fine reflective particles high in the stratosphere so that a small fraction of incoming sunlight is bounced back into space. The inspiration is volcanic: large eruptions have been followed by measurable, if temporary, periods of global cooling. That nature has already run the experiment, however, tells us rather less than enthusiasts sometimes imply, because a volcano does not have to be maintained for a century. The proposal has moved, within a generation, from the margins of climate science to the agendas of national academies, a migration that says as much about the slow pace of emissions reductions as about any scientific breakthrough."],
 ["B","The case for taking the idea seriously is straightforward, and I do not think it can be lightly dismissed. Even if emissions fell sharply tomorrow, the carbon dioxide already in the atmosphere would continue to warm the planet for decades. Modelling studies suggest that a modest reflective layer could reduce peak temperatures relatively quickly, and at a cost that is trivial compared with the damage it might avert. For low-lying nations facing the gradual loss of their territory, an argument that begins with the principle that humanity should not interfere with the climate may sound like a luxury of the comfortable. Few, after all, would refuse a fire extinguisher on the grounds that it does nothing to address the cause of the fire."],
 ["C","Yet the very cheapness of the technique is part of the difficulty. Most environmental problems are failures of collective action: everyone benefits from a stable climate, but no single country wishes to bear the cost of cutting its emissions. Solar geoengineering inverts this structure. Because it would be affordable for a single mid-sized state, or conceivably a wealthy private consortium, the question is no longer who will pay but who will decide. A country suffering a devastating heatwave might act alone, and its neighbours, whose seasonal rains might be weakened as a side effect, would have little recourse. No existing treaty was designed with such a scenario in mind, and international law offers, at best, a patchwork of principles drafted for quite different purposes. The governance problem is not an obstacle to be cleared once the science is settled; it is, arguably, the central problem."],
 ["D","A second objection concerns what economists call moral hazard. If governments believe that a technological fix is available, the argument runs, they will feel less pressure to undertake the slow and politically painful work of decarbonisation. Some researchers dispute this. A survey conducted by the Halvorsen Institute in Oslo found that informing citizens about geoengineering made a minority of them more, not less, supportive of emissions cuts, apparently because the proposal alarmed them. It would be unwise to build policy on a single survey, but the finding does at least complicate the assumption that awareness inevitably breeds complacency. Nor is the worry unique to this case: similar fears were once voiced about seat belts, which some predicted would simply encourage reckless driving."],
 ["E","Perhaps the most troubling feature is what has been called termination shock. Reflective particles fall out of the stratosphere within a year or two, so the layer would have to be replenished continuously. If injections were halted abruptly, whether through war, economic collapse or a simple change of government, the warming they had been concealing would return within a few years rather than over several decades, leaving ecosystems and societies almost no time to adapt. The faster the change, the less able species are to migrate or farmers to adjust their crops. To begin such a programme would therefore be to make a promise on behalf of generations not yet born, who would inherit an obligation they never chose."],
 ["F","Defenders reply that these risks argue for careful research, not for abandoning the idea altogether. Their position has a certain logic: if a desperate government is likely to attempt geoengineering eventually, it is better that the consequences have been studied openly beforehand. Ignorance, on this view, is not caution but merely a different kind of gamble. Critics counter that research is never entirely neutral, since each experiment builds expertise, institutions and careers with an interest in continuation. The cancellation of a small outdoor trial in a remote northern region, after objections from local communities who had not been consulted, showed that even a modest test can become a symbol of much larger anxieties about who controls the sky."],
 ["G","My own view is that the debate has too often been framed as a choice between virtue and recklessness. Solar geoengineering is not a substitute for cutting emissions, and anyone who presents it as such is selling something. But nor is refusing to think about it a morally clean position, since a world that overshoots its temperature targets may face the choice whether it has prepared or not. To insist on purity in such circumstances is to confuse the comfort of one's own conscience with the welfare of those most exposed to harm. The least bad course is probably to pursue small-scale, transparent research under international oversight, while being candid that we do not yet know how to govern a technology that would, quite literally, place a thermostat in the hands of whoever is willing to use it."]
 ],
 groups:[
 {qtype:"Yes/No/Not Given", instr:"Do the following statements agree with the claims of the writer? Choose YES, NO or NOT GIVEN.", options:["YES","NO","NOT GIVEN"], items:[
  {q:"The cooling that follows volcanic eruptions is strong evidence that solar geoengineering could be sustained safely.", a:"NO", ev:"tells us rather less than enthusiasts sometimes imply, because a volcano does not have to be maintained for a century", ex:"The writer explicitly downplays the volcanic analogy: an eruption is a one-off event, whereas geoengineering would have to be maintained. 'Strong evidence' contradicts 'tells us rather less'.", strat:"Watch for understatement: 'rather less than ... imply' is a polite but clear disagreement."},
  {q:"Objections based on the principle of non-interference may seem less convincing to countries whose land is under threat.", a:"YES", ev:"may sound like a luxury of the comfortable", ex:"The writer suggests that, for low-lying nations, such principled objections look like a luxury that only safe, comfortable people can afford."},
  {q:"Low-lying nations have been the most active supporters of geoengineering research.", a:"NOT GIVEN", ev:"For low-lying nations facing the gradual loss of their territory", ex:"Low-lying nations are mentioned to show why the principled argument may sound hollow to them, but the writer never says whether they actually support or fund research. Do not turn an imagined viewpoint into a reported fact."},
  {q:"The Halvorsen Institute survey is sufficient evidence that public awareness of geoengineering increases support for emissions cuts.", a:"NO", ev:"It would be unwise to build policy on a single survey", ex:"The writer treats the survey cautiously: it only 'complicates' the opposite assumption. Note too that only 'a minority' became more supportive, so 'sufficient evidence' goes much further than the writer does."},
  {q:"People who promote geoengineering as an alternative to reducing emissions are being misleading.", a:"YES", ev:"anyone who presents it as such is selling something", ex:"'Selling something' is an idiom meaning that someone is promoting an idea for their own interest and not telling the whole truth, so it matches 'misleading'."}
 ]},
 {qtype:"Matching Information", instr:"Which paragraph contains the following information? Write the correct letter, A-G.", options:["A","B","C","D","E","F","G"], items:[
  {q:"an explanation of why a programme, once started, would be dangerous to stop", a:"E", ev:"would return within a few years rather than over several decades, leaving ecosystems and societies almost no time to adapt", ex:"Paragraph E describes termination shock: stopping suddenly would release the hidden warming very quickly."},
  {q:"a claim that the low cost of the technique changes the nature of the political problem", a:"C", ev:"the question is no longer who will pay but who will decide", ex:"Paragraph C argues that cheapness turns a problem of paying into a problem of deciding. Paragraph B also mentions cost, but only as a benefit, not as something that changes the politics."},
  {q:"an example of a planned experiment coming to represent broader concerns", a:"F", ev:"even a modest test can become a symbol of much larger anxieties", ex:"The cancelled outdoor trial in paragraph F became 'a symbol' of wider fears about who controls the sky."},
  {q:"a statement that past emissions would keep raising temperatures for many years", a:"B", ev:"the carbon dioxide already in the atmosphere would continue to warm the planet for decades", ex:"'Already in the atmosphere' = past emissions; 'for decades' = for many years."}
 ]},
 {qtype:"Summary Completion", instr:"Complete the summary. Write NO MORE THAN TWO WORDS from the passage for each answer.", limit:2, items:[
  {q:"One objection, known as ___, is that the availability of a technical fix could reduce the pressure on governments to decarbonise.", a:["moral hazard"], ev:"A second objection concerns what economists call moral hazard.", ex:"The term is introduced in paragraph D and then defined: less pressure to do the 'politically painful work of decarbonisation'."},
  {q:"Since the particles leave the stratosphere within a year or two, the reflective layer would need to be ___ without interruption.", a:["replenished"], ev:"the layer would have to be replenished continuously", ex:"'Without interruption' paraphrases 'continuously'; the missing verb is 'replenished'."},
  {q:"A sudden end to the injections could cause a rapid return of warming, a risk described as ___.", a:["termination shock"], ev:"what has been called termination shock", ex:"Paragraph E names this risk. Two words, both from the passage."},
  {q:"Beginning such a scheme would therefore impose an ___ on future generations who had no say in it.", a:["obligation"], ev:"who would inherit an obligation they never chose", ex:"'Had no say in it' paraphrases 'never chose'; the noun is 'obligation'."}
 ]}
 ]
},
{
 id:"R75-02", title:"The Inner Ecosystem: What We Still Do Not Know about the Gut Microbiome", category:"Biology", band:7.5, mock:null, mins:20,
 paras:[
 ["A","Few areas of biology have travelled so quickly from obscurity to celebrity as the study of the gut microbiome, the trillions of bacteria, fungi, viruses and other microorganisms that inhabit the human digestive tract. Two decades ago it was a specialist concern of microbiologists; today it features on supermarket yoghurt labels and in the titles of bestselling self-help books. The rise has been driven partly by genuine discoveries and partly by technology: the falling cost of genetic sequencing allowed researchers to identify microbes that had never been grown in a laboratory, revealing a community far more diverse than earlier culture-based methods had suggested. What the excitement tends to obscure, however, is how much remains unknown, and how many of the field's most confident pronouncements rest on surprisingly slender foundations."],
 ["B","Consider the frequently repeated claim that bacterial cells outnumber human cells in the body by ten to one. The figure appears to have originated as a rough calculation in the 1970s and was then repeated for decades, in textbooks and lectures alike, without serious scrutiny. More recent estimates, based on better measurements of the volume of the colon and the density of bacteria within it, place the ratio much closer to one to one. The revision does not diminish the importance of the microbiome, but it is a salutary reminder of how readily a striking number can harden into accepted fact. If so basic a quantity could go unchallenged for so long, more subtle claims deserve at least equal caution."],
 ["C","A more fundamental difficulty is that nobody can yet say what a healthy microbiome looks like. The composition of gut communities varies enormously between individuals, and even within one person it can shift considerably with diet, medication, travel or illness. Studies comparing populations have found that people in industrialised cities tend to host fewer kinds of microbes than those living in rural communities with traditional diets, but whether this reduced diversity is harmful, or merely different, is contested. A community that appears impoverished by one measure may perform the same chemical functions as a richer one, because different species can do overlapping jobs, much as a small village may manage with one shopkeeper doing the work of several."],
 ["D","Much of the evidence linking the microbiome to disease is correlational. People with certain conditions, from inflammatory bowel disorders to depression, have been found to carry distinctive microbial profiles. Yet such associations leave the direction of influence unresolved. A disease, or the drugs used to treat it, might alter the microbiome rather than the reverse; alternatively, some third factor such as diet could be shaping both. Experiments in which microbes from human donors are transferred into germ-free mice have provided more persuasive evidence of causation in some cases, but mice differ from humans in their anatomy, diet and immune systems, and results obtained in the animal laboratory have not always survived translation to the clinic. A mouse that becomes anxious after receiving microbes from an anxious donor is an intriguing finding; it is not yet a treatment for human anxiety."],
 ["E","One intervention has, admittedly, proved strikingly effective. Faecal microbiota transplantation, the transfer of processed stool from a healthy donor into a patient's gut, cures most cases of a recurrent and sometimes life-threatening bacterial infection that has failed to respond to antibiotics. Its success is often cited as proof that the microbiome can be deliberately engineered. The irony is that, even here, researchers cannot say with confidence which components of the transplanted material are responsible: bacteria, viruses that infect bacteria, chemical by-products, or some combination of these. The treatment works, in other words, somewhat in the way that many traditional remedies once did, reliably enough to be used and mysteriously enough to be humbling."],
 ["F","Such uncertainty has not deterred commerce. Probiotic supplements, which contain live bacteria said to benefit the host, form a market worth many billions of pounds a year. Clinical trials have shown benefits for a handful of specific conditions, such as certain kinds of diarrhoea associated with antibiotic treatment, but the evidence for the broader claims made on packaging, such as improved mood or stronger immunity, is thin. One complication is that ingested bacteria rarely establish themselves permanently; most appear to pass through the gut within weeks of a person ceasing to take them. A review by researchers at the Brennan Centre for Digestive Health concluded that, for healthy adults, the typical commercial probiotic was unlikely to cause harm and unlikely to do much else. Manufacturers, for their part, point out that the absence of proof is not proof of absence, which is true but hardly a ringing endorsement of their products."],
 ["G","None of this means the field is overrated so much as that it is young. Several research groups are now attempting to move beyond cataloguing which microbes are present towards understanding what they actually do, by measuring the chemicals they produce and tracing how those chemicals interact with human cells. Others are exploring whether the same meal produces different effects in different people depending on their gut communities, a line of inquiry that could eventually lead to dietary advice tailored to individuals rather than to populations. If that promise is fulfilled, it will be because researchers resisted the temptation to announce answers before they had learned to ask the right questions."]
 ],
 groups:[
 {qtype:"Matching Headings", instr:"The passage has seven paragraphs, A-G. Choose the correct heading for paragraphs B-G from the list of headings below.", options:["i  A treatment whose mechanism remains unclear","ii  The problem of identifying a standard","iii  Why sequencing has replaced laboratory culture","iv  A widely quoted figure revised","v  Marketing that outpaces the science","vi  Shifting attention from identity to function","vii  Links whose direction is uncertain","viii  The dangers of antibiotic overuse","ix  How urban diets have changed"], optKey:"roman", items:[
  {q:"Paragraph B", a:"iv", ev:"place the ratio much closer to one to one", ex:"Paragraph B is about the ten-to-one figure and how newer estimates corrected it. 'Widely quoted' = 'frequently repeated'; 'revised' = 'revision'."},
  {q:"Paragraph C", a:"ii", ev:"nobody can yet say what a healthy microbiome looks like", ex:"The main idea is that there is no agreed 'normal' or healthy microbiome. Heading ix is a trap: urban populations are mentioned, but the paragraph says nothing about how their diets have changed."},
  {q:"Paragraph D", a:"vii", ev:"such associations leave the direction of influence unresolved", ex:"The paragraph explains that correlations do not show whether disease changes the microbiome or the reverse. 'Direction ... uncertain' = 'direction of influence unresolved'."},
  {q:"Paragraph E", a:"i", ev:"researchers cannot say with confidence which components of the transplanted material are responsible", ex:"The transplant works, but nobody knows exactly why. Heading viii is a distractor: antibiotics are mentioned only because the infection resists them."},
  {q:"Paragraph F", a:"v", ev:"the evidence for the broader claims made on packaging, such as improved mood or stronger immunity, is thin", ex:"Paragraph F contrasts a large commercial market with weak evidence for most claims: the marketing has run ahead of the science."},
  {q:"Paragraph G", a:"vi", ev:"move beyond cataloguing which microbes are present towards understanding what they actually do", ex:"Identity = which microbes are present; function = what they actually do. Heading iii is tempting because of the word 'sequencing', but that topic belongs to paragraph A."}
 ]},
 {qtype:"True/False/Not Given", instr:"Do the following statements agree with the information given in the passage? Choose TRUE, FALSE or NOT GIVEN.", options:["TRUE","FALSE","NOT GIVEN"], items:[
  {q:"Methods that depended on growing microbes in the laboratory gave too narrow a picture of gut communities.", a:"TRUE", ev:"revealing a community far more diverse than earlier culture-based methods had suggested", ex:"If sequencing revealed far more diversity than culture-based methods suggested, those methods underestimated the variety, i.e. gave too narrow a picture."},
  {q:"The ten-to-one ratio was originally derived from detailed measurements of the colon.", a:"FALSE", ev:"originated as a rough calculation in the 1970s", ex:"The original figure was a 'rough calculation'. Detailed measurements of the colon are what produced the newer, corrected estimate, so the statement reverses the facts.", strat:"Check WHICH estimate a detail belongs to; IELTS often swaps the old and new versions."},
  {q:"Rural populations in the studies suffer less from digestive diseases than city dwellers.", a:"NOT GIVEN", ev:"people in industrialised cities tend to host fewer kinds of microbes than those living in rural communities with traditional diets", ex:"The passage compares microbial diversity, not rates of disease. In fact it says it is contested whether lower diversity is harmful at all. No information about disease rates is given."},
  {q:"Most bacteria taken in probiotic supplements remain in the gut long after a person stops taking them.", a:"FALSE", ev:"ingested bacteria rarely establish themselves permanently", ex:"Most pass through 'within weeks' of stopping, which contradicts 'remain ... long after'."}
 ]},
 {qtype:"Sentence Completion", instr:"Complete the sentences below. Write NO MORE THAN TWO WORDS from the passage for each answer.", limit:2, items:[
  {q:"Stronger evidence that microbes can cause illness has come from transferring human microbes into ___.", a:["germ-free mice"], ev:"transferred into germ-free mice have provided more persuasive evidence of causation", ex:"'Stronger evidence' paraphrases 'more persuasive evidence'. The hyphenated 'germ-free' counts as one word."},
  {q:"Faecal transplants can cure a recurring infection that has not been cured by ___.", a:["antibiotics"], ev:"failed to respond to antibiotics", ex:"'Has not been cured by' paraphrases 'failed to respond to'."},
  {q:"Trials suggest probiotics can help with some types of ___ linked to antibiotic treatment.", a:["diarrhoea"], ev:"certain kinds of diarrhoea associated with antibiotic treatment", ex:"'Some types of' = 'certain kinds of'; 'linked to' = 'associated with'. Mood and immunity are the claims with thin evidence."},
  {q:"Research into how individuals respond to the same meal might one day make personalised ___ possible.", a:["dietary advice"], ev:"could eventually lead to dietary advice tailored to individuals", ex:"'Personalised' paraphrases 'tailored to individuals'; the gap needs the noun phrase 'dietary advice'."}
 ]}
 ]
},
{
 id:"R75-03", title:"A Matter of Time: the Search for Longitude at Sea", category:"History", band:7.5, mock:null, mins:20,
 paras:[
 ["A","For most of the history of ocean travel, a ship's navigator could answer only half of the question 'Where are we?' with any confidence. Latitude, the distance north or south of the equator, could be found by measuring the height of the sun at noon or of the Pole Star at night, a technique familiar to sailors for centuries. Longitude, the position east or west, was another matter entirely. Its determination depended not on the sky alone but on time, and keeping accurate time on a pitching, rolling, damp wooden ship was beyond the technology of the age. The consequences were measured in lost cargoes, lost ships and lost lives."],
 ["B","The principle was understood long before it could be applied. Because the Earth turns through 360 degrees in twenty-four hours, every hour of difference between local time and the time at some reference point corresponds to fifteen degrees of longitude. Local time could be established from the sun; the difficulty lay in knowing, at the same moment, what time it was at the home port. A clock set before departure would serve, provided it kept time to within a few seconds a day for months on end. The pendulum clocks of the seventeenth century, admirable on land, were hopeless at sea, where the motion of the vessel disturbed the pendulum and changes in temperature caused their metal parts to expand and contract."],
 ["C","In the absence of a solution, sailors relied on dead reckoning: estimating position from the ship's speed, its compass heading and the time elapsed since the last known point. Speed was measured by throwing overboard a piece of wood attached to a knotted line and counting the knots that ran out in a given interval, a practice that bequeathed the word 'knot' to the language of navigation. Experienced navigators could achieve respectable results over short distances, but small errors in each estimate compounded one another, so that after weeks at sea a ship's believed position might differ from its true position by many miles. Currents and leeway, the sideways drift caused by wind, added further uncertainty."],
 ["D","The costs of this uncertainty became politically impossible to ignore in the early eighteenth century, after a naval disaster off the south-west coast of England in which several warships were wrecked and well over a thousand sailors drowned, partly because of errors in navigation. In 1714 the British Parliament offered a prize of up to twenty thousand pounds, an enormous sum at the time, for a method that could find longitude at sea to within half a degree. Other maritime powers had offered similar rewards in earlier decades, without result. That governments were prepared to pay such sums says a good deal about how central sea power had become to national wealth."],
 ["E","Astronomers were confident that the answer lay in the heavens. Galileo had proposed using the predictable eclipses of Jupiter's moons as a kind of celestial clock visible from anywhere on Earth, and the method was indeed used to improve maps on land. At sea, however, holding a telescope steady enough to observe tiny moons from a moving deck proved all but impossible. The more promising astronomical approach was the lunar distance method, which relied on the fact that the moon moves against the background of fixed stars at a known rate. By measuring the angle between the moon and a particular star and consulting tables prepared in advance, a navigator could work out the time at the reference point. The method was sound in principle, but the tables required years of observation to compile, and the calculations at sea could occupy a skilled navigator for several hours."],
 ["F","The rival approach was mechanical. John Harrison, a carpenter and largely self-taught clockmaker from the north of England, devoted several decades to building timekeepers that could withstand the conditions of a voyage. His designs incorporated ingenious devices to compensate for changes in temperature and to reduce friction, and his fourth instrument, a large watch rather than a clock, performed remarkably well in sea trials. Popular histories have tended to present his story as a romance of the lone craftsman triumphing over a hostile scientific establishment. The reality was untidier. The board responsible for the prize was certainly cautious, and Harrison's rewards arrived slowly and in instalments, but its insistence on repeated tests, and on proof that the watch could be copied by other makers, was not unreasonable for a body charged with spending public money. A single extraordinary instrument was not yet a navigational system."],
 ["G","Nor did the clockmaker's achievement end the matter as neatly as the legend suggests. Early marine timekeepers were extremely expensive, and for decades many ships could not afford one. The lunar method, simplified by the publication of annual almanacs containing pre-calculated tables, remained in widespread use well into the nineteenth century, often as a check on the chronometer. The two approaches, so often cast as rivals, in practice became partners. Only as manufacturing improved and prices fell did the marine chronometer become standard equipment, and by then the question that had consumed a century had quietly been settled by economics rather than by genius alone."]
 ],
 groups:[
 {qtype:"Matching Features", instr:"Match each statement with the correct method, A, B, C or D. You may use any letter more than once.", options:["A  dead reckoning","B  observing Jupiter's moons","C  the lunar distance method","D  the marine timekeeper"], optKey:"letter", items:[
  {q:"It proved useful on land but could not be applied reliably on a moving ship.", a:"B", ev:"the method was indeed used to improve maps on land", ex:"Jupiter's moons helped map-making on land, but observing them from 'a moving deck proved all but impossible'."},
  {q:"Its inaccuracy increased the longer a voyage continued.", a:"A", ev:"small errors in each estimate compounded one another, so that after weeks at sea", ex:"With dead reckoning, errors 'compounded', so the position became less reliable with time at sea."},
  {q:"Using it at sea could take an expert a long time.", a:"C", ev:"the calculations at sea could occupy a skilled navigator for several hours", ex:"'An expert' = 'a skilled navigator'; 'a long time' = 'several hours'."},
  {q:"At first, its cost put it beyond the reach of many vessels.", a:"D", ev:"Early marine timekeepers were extremely expensive, and for decades many ships could not afford one", ex:"Paragraph G states that early timekeepers were too expensive for many ships."},
  {q:"It was made easier by reference works issued every year.", a:"C", ev:"simplified by the publication of annual almanacs containing pre-calculated tables", ex:"'Reference works issued every year' paraphrases 'annual almanacs'. These simplified the lunar method, not the timekeeper."}
 ]},
 {qtype:"Multiple Choice", instr:"Choose the correct letter, A, B, C or D.", items:[
  {q:"According to the first two paragraphs, longitude was harder to find than latitude because", opts:["the necessary stars were visible only at night.","it required knowing the time at a distant place.","the principle behind it had not yet been discovered.","sailors distrusted mathematical techniques."], a:"B", ev:"the difficulty lay in knowing, at the same moment, what time it was at the home port", ex:"Longitude depends on comparing local time with the time at the home port. Option C is wrong: 'The principle was understood long before it could be applied.'"},
  {q:"Why does the writer refer to the size of the 1714 prize?", opts:["to suggest that Parliament wasted public money","to show how important naval power was to a country's prosperity","to explain why foreign inventors entered the competition","to contrast British generosity with that of other nations"], a:"B", ev:"says a good deal about how central sea power had become to national wealth", ex:"The writer draws a conclusion from the size of the prize: sea power was central to national wealth. Other nations' rewards are mentioned but not compared in generosity."},
  {q:"What is the writer's view of the board that managed the prize?", opts:["It was deliberately unfair to a craftsman without formal training.","It was cautious, but its demands were largely justified.","It rewarded Harrison more quickly than he deserved.","It favoured astronomers over clockmakers."], a:"B", ev:"was not unreasonable for a body charged with spending public money", ex:"The writer concedes that the board was 'certainly cautious' but defends its demands. Option A reflects the 'popular histories' that the writer calls a romance, not the writer's own opinion.", strat:"Separate what 'popular histories' say from what the writer believes."},
  {q:"What point does the writer make in the final paragraph?", opts:["The chronometer immediately made the lunar method obsolete.","The lunar method was ultimately more accurate than the chronometer.","Falling costs, not ingenuity alone, decided when chronometers became normal.","Harrison's design could never be successfully reproduced."], a:"C", ev:"settled by economics rather than by genius alone", ex:"The chronometer became standard 'only as manufacturing improved and prices fell'. Option A is contradicted: the lunar method stayed in use 'well into the nineteenth century'."}
 ]},
 {qtype:"Note Completion", instr:"Complete the notes. Write NO MORE THAN TWO WORDS from the passage for each answer.", limit:2, items:[
  {q:"Principle: each hour of time difference = ___ of longitude", a:["fifteen degrees","15 degrees"], ev:"corresponds to fifteen degrees of longitude", ex:"360 degrees in 24 hours gives 15 degrees per hour; the passage writes the number in words."},
  {q:"Problem with pendulum clocks: ship's motion and changes in ___", a:["temperature"], ev:"changes in temperature caused their metal parts to expand and contract", ex:"Two causes are given: the motion of the vessel and temperature changes that made metal expand and contract."},
  {q:"Dead reckoning: speed measured with wood tied to a ___", a:["knotted line"], ev:"a piece of wood attached to a knotted line", ex:"'Tied to' paraphrases 'attached to'. The knots gave the speed unit its name."},
  {q:"Extra uncertainty from currents and ___ (sideways drift caused by wind)", a:["leeway"], ev:"Currents and leeway, the sideways drift caused by wind", ex:"The passage defines leeway immediately after naming it."}
 ]}
 ]
},
{
 id:"R75-04", title:"The Laboratory and the Connoisseur: Science against Forgery", category:"Art", band:7.5, mock:null, mins:20,
 paras:[
 ["A","The art market has a peculiar relationship with doubt. A painting attributed to a celebrated master may be worth a hundred times as much as an almost identical canvas labelled 'follower of' or 'school of', and the difference between those descriptions has traditionally rested on the judgement of a small number of experts. These connoisseurs, trained to recognise an artist's handling of paint and habits of composition, have frequently been right. They have also, on some notable occasions, been spectacularly wrong, and it is partly in response to such embarrassments that museums and auction houses have increasingly turned to the laboratory. The shift has not been universally welcomed. Some connoisseurs regard technical analysis as a blunt instrument wielded by people with no eye for painting, while some scientists dismiss connoisseurship as little more than educated opinion dressed up as knowledge."],
 ["B","The most straightforward scientific test asks whether the materials of a work could have existed when it was supposedly made. Many pigments have well-documented dates of introduction. Titanium white, for instance, became commercially available only in the twentieth century, so its presence in a painting attributed to a seventeenth-century artist is, barring later restoration, decisive. Analysts at the Kessler Institute for Conservation Science reported several years ago that a supposedly Flemish landscape submitted for examination contained precisely this pigment beneath its surface varnish; the attribution was quietly withdrawn within a week. Such anachronisms are the forensic equivalent of a wristwatch in a portrait of a medieval king. Pigment analysis has the additional virtue of requiring only microscopic samples, often taken from the edges of a canvas where the loss will never be noticed."],
 ["C","Paintings on wood offer a further source of evidence. Dendrochronology, the study of annual growth rings, can establish when the tree used for a panel was felled, by matching the pattern of wide and narrow rings against reference sequences built up from securely dated timber. Such sequences now exist for oak from much of northern Europe, although far fewer have been compiled for the softer woods favoured in some regions. The method does not, of course, reveal when the panel was painted: wood was typically seasoned for some years before use, and a determined forger may simply acquire an old panel. What it can provide is an earliest possible date, which is sometimes enough to rule an attribution out but never enough, on its own, to rule one in."],
 ["D","Radiocarbon dating, long associated with archaeology, has found an unexpected application in the detection of modern fakes. Nuclear weapons tests in the 1950s and early 1960s sharply increased the amount of carbon-14 in the atmosphere, and this excess was absorbed by living things, including the plants from which canvas fibres and oil binders are derived. Materials produced after that period therefore carry a distinctive chemical signature. For older works the technique is less useful, since its margins of error can span several decades, but for exposing twentieth-century forgeries passed off as earlier works it can be remarkably effective. A forger who takes care to use old pigments may not think to ask where the oil in which they are bound was produced."],
 ["E","Other methods look beneath the visible surface. X-radiography and infrared imaging can reveal underdrawings and earlier versions of a composition. Original works frequently show the artist changing their mind, adjusting the position of a hand or removing a figure altogether, whereas a copyist working from a finished model has little reason to hesitate. The presence of such alterations is not proof of authenticity, but their complete absence in a work by an artist known to have revised extensively may reasonably raise suspicion. Infrared images can also capture an artist's characteristic manner of sketching, which is often harder to imitate than the finished surface precisely because it was never intended to be seen."],
 ["F","It would be comforting to conclude that science has made forgery obsolete. It has not, and I suspect it never will. Every published technique becomes, in effect, a set of instructions for the next generation of forgers, who now source historical pigments, scrape down genuine old canvases and even simulate the fine network of cracks that develops as paint ages. More fundamentally, the laboratory is far better at demonstrating that a work is not what it claims to be than at proving that it is. A painting made entirely from period-appropriate materials might still be a fake produced with patience and skill; an absence of anachronisms establishes only that the forger, if there was one, made no mistake that has yet been detected."],
 ["G","For this reason, I believe the most productive approach is not to set the scientist against the connoisseur but to treat their methods as complementary. Technical analysis can narrow the field and occasionally deliver a verdict; stylistic judgement, documentary research into a work's ownership history and comparison with securely attributed pieces must do the rest. Dr Ilse Varga, who heads the paintings laboratory at the Kessler Institute, has remarked that her instruments answer only the questions we already know to ask. Laboratories, after all, cannot test for what nobody suspects. The forgers who cause the most trouble are, by definition, those who anticipate those questions, which suggests that humility, rather than any new machine, remains the expert's most valuable tool."]
 ],
 groups:[
 {qtype:"Table Completion", instr:"Complete the table. Write NO MORE THAN TWO WORDS from the passage for each answer.", limit:2, table:{head:["Technique","What it can show","Limitation"],rows:[["Pigment analysis","materials not yet invented, e.g. [1]","later restoration may confuse results"],["Dendrochronology","when the tree was [2]","provides only an [3] date"],["Radiocarbon dating","excess carbon-14 caused by nuclear [4]","wide margins of error for older works"],["X-ray and infrared imaging","[5] and changes of composition","alterations do not prove a work is genuine"]]}, items:[
  {q:"Example of an anachronistic pigment: ___", a:["titanium white"], ev:"Titanium white, for instance, became commercially available only in the twentieth century", ex:"The passage gives titanium white as its example of a pigment that did not exist in the seventeenth century."},
  {q:"Dendrochronology shows when the tree was ___", a:["felled"], ev:"can establish when the tree used for a panel was felled", ex:"Tree rings date the felling of the tree, not the painting itself."},
  {q:"Dendrochronology provides only an ___ date", a:["earliest possible"], ev:"What it can provide is an earliest possible date", ex:"Because wood was seasoned and old panels can be reused, the method only gives the earliest date at which the work could have been painted."},
  {q:"Excess carbon-14 caused by nuclear ___", a:["weapons tests"], ev:"Nuclear weapons tests in the 1950s and early 1960s sharply increased the amount of carbon-14", ex:"The table already supplies 'nuclear', so the gap needs 'weapons tests'."},
  {q:"X-ray and infrared imaging can reveal ___", a:["underdrawings"], ev:"can reveal underdrawings and earlier versions of a composition", ex:"'Changes of composition' in the table paraphrases 'earlier versions of a composition'; the other item revealed is underdrawings."}
 ]},
 {qtype:"Yes/No/Not Given", instr:"Do the following statements agree with the claims of the writer? Choose YES, NO or NOT GIVEN.", options:["YES","NO","NOT GIVEN"], items:[
  {q:"The judgements of connoisseurs have generally proved unreliable.", a:"NO", ev:"have frequently been right", ex:"The writer says connoisseurs have 'frequently been right', though sometimes 'spectacularly wrong'. 'Generally unreliable' overstates the occasional failures.", strat:"Do not let one vivid exception ('spectacularly wrong') override the writer's general claim."},
  {q:"Auction houses have been quicker than museums to adopt scientific testing.", a:"NOT GIVEN", ev:"museums and auction houses have increasingly turned to the laboratory", ex:"Both are mentioned together; the writer makes no comparison of which adopted science first or faster."},
  {q:"Unless a painting has been restored, titanium white in a supposed seventeenth-century work settles the question of its date.", a:"YES", ev:"barring later restoration, decisive", ex:"'Barring later restoration' = 'unless it has been restored'; 'decisive' = 'settles the question'."},
  {q:"Advances in scientific analysis will eventually make forgery impossible.", a:"NO", ev:"It has not, and I suspect it never will.", ex:"The writer explicitly rejects the idea that science will make forgery obsolete, because forgers learn from published techniques."},
  {q:"Scientific and stylistic methods should be regarded as working together rather than in competition.", a:"YES", ev:"not to set the scientist against the connoisseur but to treat their methods as complementary", ex:"'Complementary' means that each supplies what the other lacks, i.e. they work together."}
 ]},
 {qtype:"Short Answer", instr:"Answer the questions below. Write NO MORE THAN THREE WORDS from the passage for each answer.", limit:3, items:[
  {q:"What might a forger obtain in order to defeat dendrochronology?", a:["an old panel","old panel"], ev:"a determined forger may simply acquire an old panel", ex:"An old panel would have tree rings that produce a convincingly early felling date."},
  {q:"What feature of ageing paint do some forgers now imitate?", a:["network of cracks","cracks"], ev:"simulate the fine network of cracks that develops as paint ages", ex:"'Imitate' paraphrases 'simulate'. 'Fine network of cracks' is four words, so 'network of cracks' fits the limit."},
  {q:"Apart from stylistic judgement and comparison with other works, what kind of investigation into ownership history does the writer recommend?", a:["documentary research"], ev:"documentary research into a work's ownership history", ex:"The writer lists three non-laboratory methods; the one concerning ownership history is documentary research."}
 ]}
 ]
},
{
 id:"R75-05", title:"Silent Tongues: the Loss of Linguistic Diversity", category:"Language", band:7.5, mock:null, mins:20,
 paras:[
 ["A","Of the roughly seven thousand languages spoken today, a large proportion are used by very small communities, and frequently cited estimates suggest that as many as half may cease to be spoken by the end of this century. Such figures should be treated with some caution: counting languages is itself a contentious exercise, since the boundary between a language and a dialect is often drawn as much by politics as by linguistics. Yet even allowing for generous margins of error, few specialists doubt that the world is undergoing a contraction of linguistic diversity without precedent in recorded history. Linguists generally classify a language as endangered not when its speakers are few but when children are no longer acquiring it, since a language with a hundred young speakers may be more secure than one with ten thousand elderly ones."],
 ["B","Languages rarely die because their last speakers die. Far more commonly, they are abandoned. The typical pattern, which linguists call language shift, unfolds over three generations. Grandparents speak the community language fluently; their children understand it but reply in the dominant language of the school and the labour market; the grandchildren neither speak nor understand it. Each step is, from the perspective of the individual family, entirely rational. Parents who have experienced discrimination, or who see that economic opportunity lies elsewhere, may conclude that passing on the language would handicap their children. The tragedy, if that is the right word, is that a series of sensible private decisions can produce a collective outcome that many of those involved later regret."],
 ["C","What exactly is lost? The answer most frequently advanced is knowledge. Languages spoken by small communities often encode a detailed understanding of local environments: names for plants with medicinal properties, distinctions between types of snow or sea ice, or terms for ecological relationships that outsiders have not yet documented. When the vocabulary disappears, the argument runs, so does the knowledge. There is truth in this, though it is sometimes overstated; knowledge can in principle be translated and recorded, and much of it is transmitted through practice rather than through words alone. What resists translation is less the individual fact than the web of associations in which it is embedded, and that web is far harder to reconstruct from a dictionary entry."],
 ["D","A subtler argument concerns the science of language itself. Linguists attempting to establish which features all human languages share, and which are merely common, depend on the widest possible sample. Several grammatical structures once assumed to be impossible have been found only in languages spoken by a few thousand people, or fewer. Every language that vanishes undocumented therefore narrows the evidence on which theories of the human mind are built. It is a curious irony that the discipline best equipped to describe these languages is also the one most dependent on their survival. A single undescribed language from a remote highland, for instance, can overturn a long-held assumption about the order in which speakers may arrange subject, verb and object."],
 ["E","For the communities concerned, such academic considerations are often secondary. People who have lost their ancestral language frequently describe the loss in terms of identity and belonging: an inability to understand the songs, prayers or jokes of their grandparents, and a sense of being cut off from their own history. It would be presumptuous for outsiders to dismiss these feelings, but equally presumptuous to assume that every community wishes to reverse the shift. Some speakers regard the dominant language as fully their own and resent the suggestion that they have betrayed a heritage."],
 ["F","Efforts to revitalise endangered languages have met with mixed results. The most successful have generally combined official recognition, use in schools and, crucially, opportunities for children to hear the language at home and in everyday life. In the remote Varne valley, a programme led by the linguist Dr Maren Holt placed young children in so-called language nests, where elderly speakers looked after them entirely in the local tongue. Within fifteen years, the number of fluent speakers under the age of twenty had risen from almost none to several hundred. Holt is careful to stress, however, that the programme succeeded because parents chose to take part, not because it was imposed on them."],
 ["G","Technology is sometimes presented as a remedy. Recording projects, online dictionaries and language-learning applications can preserve and spread a language at minimal cost. I am sceptical that they can do more than slow the decline. A language survives not because it is archived but because people need it: to court, to argue, to bargain, to comfort a child. A meticulously documented language that nobody uses in daily life is a museum piece, valuable certainly, but not alive."],
 ["H","None of this means that the decline is inevitable. It does mean that language policy cannot be separated from economic and social policy. Where speaking a minority language carries a penalty in employment, education or social status, exhortations to preserve it will achieve little. Where bilingualism is rewarded, or at least not punished, communities have shown a remarkable capacity to sustain more than one language across many generations. The question is less whether small languages can survive than whether the societies around them are willing to make room for them. That, ultimately, is a political choice rather than a linguistic one."]
 ],
 groups:[
 {qtype:"Multiple Choice", instr:"Choose the correct letter, A, B, C or D.", items:[
  {q:"What does the writer say about estimates of language loss?", opts:["They are precise enough to guide policy.","They are uncertain, but the overall trend is not seriously disputed.","They have been exaggerated by specialists.","They wrongly include dialects as separate languages."], a:"B", ev:"even allowing for generous margins of error, few specialists doubt", ex:"The writer urges caution about the figures but says few specialists doubt the contraction. Option D is a distractor: the language/dialect problem is mentioned as a reason for caution, not as a proven error."},
  {q:"According to paragraph B, language shift usually happens because", opts:["governments forbid the use of minority languages.","the last fluent speakers of a language die.","reasonable choices by families combine to produce an unwanted result.","children refuse to learn the language of their grandparents."], a:"C", ev:"a series of sensible private decisions can produce a collective outcome that many of those involved later regret", ex:"'Reasonable choices' = 'sensible private decisions'; 'unwanted result' = 'outcome ... later regret'. Option B is explicitly rejected in the first sentence."},
  {q:"What is the writer's attitude to the argument that language loss means loss of knowledge?", opts:["It is entirely convincing.","It has some validity but can be pushed too far.","It is irrelevant to most communities.","It applies only to medical knowledge."], a:"B", ev:"There is truth in this, though it is sometimes overstated", ex:"A typical band-7.5 concession: the writer accepts the argument ('there is truth') but qualifies it ('sometimes overstated')."},
  {q:"What irony does the writer identify in paragraph D?", opts:["Linguists have contributed to the decline of small languages.","The field best able to record small languages also relies most on their continued existence.","The most complex grammars belong to the largest languages.","Theories of the mind are based mainly on dominant languages."], a:"B", ev:"the discipline best equipped to describe these languages is also the one most dependent on their survival", ex:"The irony is that linguistics both describes these languages and depends on them. Nothing suggests linguists cause the decline (A)."}
 ]},
 {qtype:"Yes/No/Not Given", instr:"Do the following statements agree with the claims of the writer? Choose YES, NO or NOT GIVEN.", options:["YES","NO","NOT GIVEN"], items:[
  {q:"Families who stop passing on a minority language are usually acting irrationally.", a:"NO", ev:"Each step is, from the perspective of the individual family, entirely rational.", ex:"The writer stresses that each family's decision is rational; the problem lies in the combined result."},
  {q:"Not all members of communities affected by language shift want it to be reversed.", a:"YES", ev:"equally presumptuous to assume that every community wishes to reverse the shift", ex:"The writer warns against assuming every community wants reversal and notes that some speakers see the dominant language as their own."},
  {q:"The language nest approach used in the Varne valley has since been copied in other regions.", a:"NOT GIVEN", ev:"placed young children in so-called language nests", ex:"The programme and its results are described, but there is no information about whether it has been adopted elsewhere.", strat:"A success story does not imply that others copied it: look for explicit evidence."},
  {q:"Digital resources on their own are unlikely to keep a language in active use.", a:"YES", ev:"I am sceptical that they can do more than slow the decline", ex:"The writer believes technology can at best slow decline, because a language lives only if people need it in daily life."},
  {q:"Minority languages are bound to disappear in modern economies.", a:"NO", ev:"None of this means that the decline is inevitable.", ex:"'Bound to disappear' = 'inevitable', which the writer explicitly denies, pointing to communities that sustain bilingualism."}
 ]},
 {qtype:"Sentence Completion", instr:"Complete the sentences below. Write NO MORE THAN TWO WORDS from the passage for each answer.", limit:2, items:[
  {q:"Whether a variety counts as a language or a dialect is often decided by ___ as well as by linguistic criteria.", a:["politics"], ev:"is often drawn as much by politics as by linguistics", ex:"The boundary is drawn 'as much by politics as by linguistics'."},
  {q:"Much traditional knowledge is passed on through ___ rather than through vocabulary alone.", a:["practice"], ev:"much of it is transmitted through practice rather than through words alone", ex:"'Passed on' paraphrases 'transmitted'; this is why the writer thinks the knowledge argument can be overstated."},
  {q:"In the Varne valley, older speakers cared for small children in what were called ___.", a:["language nests"], ev:"placed young children in so-called language nests", ex:"'What were called' paraphrases 'so-called'."},
  {q:"The writer compares a well-recorded language that is not used every day to a ___.", a:["museum piece"], ev:"A meticulously documented language that nobody uses in daily life is a museum piece", ex:"The metaphor suggests something preserved and valuable but no longer living."}
 ]}
 ]
},
{
 id:"R75-06", title:"Paying with Our Eyes: the Economics of Attention", category:"Economics", band:7.5, mock:null, mins:20,
 paras:[
 ["A","Economists have long defined their discipline as the study of how scarce resources are allocated among competing ends. For most of its history, the resources in question were land, labour and capital. Over the past two decades, however, a growing number of scholars have argued that the scarcest resource in wealthy societies is no longer information, which is now abundant to the point of excess, but the human attention required to process it. The phrase 'attention economy' captures this reversal: when information costs almost nothing to produce and distribute, the binding constraint shifts to the limited hours and mental capacity of the people expected to consume it."],
 ["B","The business model that has grown up around this insight is, on the surface, remarkably generous. Search engines, social networks and video platforms charge their users nothing. Their revenue comes instead from advertisers, who pay for the opportunity to place messages in front of audiences whose interests can be inferred with increasing precision. The user, in the familiar phrase, is not the customer but the product. I find this formulation too glib. Users plainly receive something of value, and many would be unwilling to pay the subscription fees that would be required to replace advertising revenue. The more interesting question is not whether the exchange is fair but whether its terms are visible to those who enter into it."],
 ["C","Here the evidence is less reassuring. A free service has no price that a consumer can compare with alternatives, and the true cost, measured in time and in personal data surrendered, is rarely stated. The behavioural economist Dr Ilse Brandvold has found that participants in her studies underestimated the time they spent on a single entertainment application by roughly forty per cent, and that the size of the error grew with the intensity of use. Since conventional economic reasoning assumes that people know approximately what they are paying, a market in which the price is systematically misperceived cannot be expected to produce efficient outcomes."],
 ["D","Critics go further, arguing that platforms do not merely capture attention but actively engineer its capture. Features such as endlessly scrolling feeds, unpredictable notifications and automatically playing videos are said to exploit well-documented tendencies of human cognition, including our heightened sensitivity to variable rewards. The design researcher Tomasz Wierzbicki, who spent several years building recommendation systems before moving to academia, describes the industry's central metric, time spent on a platform, as 'a measure of success that cannot distinguish between delight and compulsion'. It is a striking observation, though it should be noted that similar charges were once levelled at novels, radio serials and even newspapers, all of which were accused in their day of corrupting the attention of the young."],
 ["E","That historical parallel deserves to be taken seriously, but it can also be pushed too far. What distinguishes the current situation is not the desire to hold an audience, which is as old as storytelling, but the scale and speed of experimentation. A platform with hundreds of millions of users can test thousands of variations of a design simultaneously and adopt whichever version keeps people engaged for a few seconds longer. No newspaper editor ever possessed such a feedback loop. The result is a system that optimises relentlessly for engagement without any individual necessarily intending the consequences. Responsibility, in such a system, is diffused across engineers, managers and algorithms to the point where it becomes genuinely difficult to say who, if anyone, has made a choice that could be held to account."],
 ["F","Defenders of the industry offer several replies. The economist Ruth Okafor-Lind argues that measures of compulsive use are often drawn from small and unrepresentative samples, and that most users report broadly positive experiences when surveyed. She also points out that competition among platforms should, in principle, reward services that respect their users' time, since dissatisfied customers can always leave. Whether they actually do so is disputed: network effects, whereby a service becomes more valuable as more people use it, make it costly for any individual to abandon a platform on which their friends and colleagues remain."],
 ["G","Proposed remedies range from the modest to the radical. Some reformers favour transparency, requiring platforms to show users how much time they have spent and what data have been collected about them. Others advocate design codes that would prohibit particular features for younger users. The most ambitious proposal, associated with the legal scholar Anselm Gruber, would treat attention-capturing design in the same way as other forms of pollution, imposing a levy proportional to the time users spend on a service beyond a certain threshold. Gruber acknowledges that measuring the harm would be difficult, but argues that carbon emissions were once considered equally hard to price. Sceptics reply that a tax calibrated to minutes of use would penalise valuable activities, such as education or keeping in touch with distant relatives, as heavily as idle scrolling."],
 ["H","My own view is that the pollution analogy, though imaginative, misdescribes the problem. Pollution harms third parties who have not consented to it; the costs of excessive screen time fall mainly on the users themselves. The more persuasive case for intervention rests on the informational failure described earlier: markets work poorly when buyers cannot see what they are paying. Making that price visible would not end the competition for our attention, nor should it. It would, however, allow us to decide with open eyes how much of it we are prepared to give away."]
 ],
 groups:[
 {qtype:"Multiple Choice", instr:"Choose the correct letter, A, B, C or D.", items:[
  {q:"According to paragraph A, why do some scholars now regard attention as the scarcest resource?", opts:["Because people have less leisure time than in the past.","Because information has become so plentiful that processing it is the real limit.","Because land, labour and capital are no longer studied by economists.","Because producing information has become increasingly expensive."], a:"B", ev:"which is now abundant to the point of excess", ex:"Information is 'abundant to the point of excess', so the constraint shifts to the attention needed to process it. D reverses the passage: information 'costs almost nothing to produce'. A is never stated: the passage mentions 'limited hours' but does not say leisure has fallen."},
  {q:"What does the writer see as the main reason the market for free online services may be inefficient?", opts:["Advertisers pay too little for the audiences they reach.","Platforms charge users fees that are hidden from them.","Users cannot accurately judge what they are giving up.","Consumers have too many alternatives to compare."], a:"C", ev:"a market in which the price is systematically misperceived cannot be expected to produce efficient outcomes", ex:"The 'price' (time and data) is 'systematically misperceived', i.e. users cannot judge what they give up. B is a trap: the services charge 'nothing', so there are no hidden fees; the hidden cost is time and data."},
  {q:"In paragraph E, what does the writer consider new about today's competition for attention?", opts:["The wish to keep an audience interested.","The deliberate intention of designers to cause harm.","The ability to test and refine designs on an enormous scale very quickly.","The willingness of newspaper editors to adopt digital methods."], a:"C", ev:"the scale and speed of experimentation", ex:"The writer concedes that holding an audience is 'as old as storytelling' (so A is not new) and stresses 'scale and speed of experimentation'. B contradicts the final sentence, which says no individual need intend the consequences."},
  {q:"Why does the writer reject the comparison between attention-capturing design and pollution?", opts:["Because the harm is too difficult to measure.","Because the costs are borne mainly by the people who choose to use the services.","Because carbon emissions are now easy to price.","Because a levy would reduce competition between platforms."], a:"B", ev:"the costs of excessive screen time fall mainly on the users themselves", ex:"Pollution harms non-consenting third parties, whereas here the users bear the costs. A is Gruber's own concession, not the writer's reason for rejecting the analogy."}
 ]},
 {qtype:"Yes/No/Not Given", instr:"Do the following statements agree with the claims of the writer? Choose YES, NO or NOT GIVEN.", options:["YES","NO","NOT GIVEN"], items:[
  {q:"Describing users of free platforms as the product oversimplifies their relationship with those platforms.", a:"YES", ev:"I find this formulation too glib.", ex:"'Glib' means superficial or oversimplified; the writer adds that users 'plainly receive something of value'.", strat:"First-person phrases (I find, my own view) signal the writer's claims."},
  {q:"Most users would be willing to pay a subscription in order to avoid advertising.", a:"NO", ev:"many would be unwilling to pay the subscription fees that would be required to replace advertising revenue", ex:"The writer states the opposite: many would be unwilling to pay. 'Willing' vs 'unwilling' is a direct contradiction, so NO rather than NOT GIVEN."},
  {q:"The harmful effects of engagement-driven design are usually planned by particular employees.", a:"NO", ev:"without any individual necessarily intending the consequences", ex:"The writer argues the system optimises for engagement without anyone necessarily intending the outcome, which contradicts deliberate planning."},
  {q:"Design codes banning certain features for children have already been adopted in several countries.", a:"NOT GIVEN", ev:"Others advocate design codes that would prohibit particular features for younger users.", ex:"Design codes are only described as something reformers 'advocate'; the writer gives no information about whether any country has adopted them.", strat:"'Advocate ... would' describes a proposal, not an existing law."},
  {q:"Regulation should aim to eliminate competition for people's attention altogether.", a:"NO", ev:"Making that price visible would not end the competition for our attention, nor should it.", ex:"'Nor should it' shows the writer does not want competition for attention to end; the aim is transparency."}
 ]},
 {qtype:"Matching Features", instr:"Match each statement with the correct person, A-D. You may use any letter more than once.", options:["A  Ilse Brandvold","B  Tomasz Wierzbicki","C  Ruth Okafor-Lind","D  Anselm Gruber"], optKey:"letter", items:[
  {q:"The more heavily people use an application, the more they misjudge how long they spend on it.", a:"A", ev:"the size of the error grew with the intensity of use", ex:"Brandvold found the underestimate 'grew with the intensity of use'; 'more heavily' paraphrases 'intensity'."},
  {q:"A widely used performance indicator fails to separate enjoyment from dependence.", a:"B", ev:"a measure of success that cannot distinguish between delight and compulsion", ex:"'Performance indicator' = 'metric/measure of success'; 'enjoyment' = 'delight'; 'dependence' = 'compulsion'."},
  {q:"Research suggesting widespread problematic use may rest on weak samples.", a:"C", ev:"measures of compulsive use are often drawn from small and unrepresentative samples", ex:"Okafor-Lind questions the samples used to measure compulsive use. Wierzbicki (B) criticises the industry, not the research."},
  {q:"Rivalry between services ought to benefit those that treat users' time with consideration.", a:"C", ev:"competition among platforms should, in principle, reward services that respect their users' time", ex:"'Rivalry' = 'competition'; 'treat ... with consideration' = 'respect'. The writer then notes network effects may prevent this."},
  {q:"A charge used for one type of environmental damage could be adapted to digital design.", a:"D", ev:"would treat attention-capturing design in the same way as other forms of pollution", ex:"Gruber proposes a levy modelled on pollution charges, comparing it with the pricing of carbon emissions."}
 ]}
 ]
}
];
