/* Lesson 3 of the Grammar Learning Layer prototype. See present-simple-vs-continuous.mjs for conventions. */
const GEN = "education|technology|knowledge|poverty|crime|society|money|information|advice|research|health|pollution";
export default {
  id: "articles", title: "Articles: a / an / the / zero article", cat: "gr.articles", minutes: 40, level: "B1 → C1",
  objective: "By the end of this lesson you will be able to decide between a / an, the and NO article by asking three questions about the noun (countable? known to both of us? general or specific?), and to avoid the article errors that Portuguese speakers make most often in IELTS Writing.",
  why: [
    { k: "Everyday English", t: "Articles carry meaning: “I need **a** pen” (any pen) vs “I need **the** pen” (the one we both know). Native speakers hear a missing or wrong article as a small but constant mistake." },
    { k: "Academic English", t: "Academic writing is full of general statements (“Education reduces poverty”) and specific ones (“**The** education system in Brazil needs reform”). The article is what tells the reader which one you mean." },
    { k: "IELTS Writing", t: "Article errors are among the most frequent errors in Portuguese speakers' essays, and they appear in almost every sentence. Reducing them improves Grammatical Range and Accuracy at once." },
    { k: "IELTS Speaking", t: "Fluency can hide them, but a wrong article in the first sentence of your answer (“I am doctor”) is noticed immediately." },
  ],
  concept: {
    intro: "An article answers ONE question for your reader: **do you know exactly which one I mean?** If I say “**a** dog” I introduce one dog among many. If I say “**the** dog” we both know which dog. If I talk about dogs in general, I use **no article**. Three questions solve almost every case.",
    points: [
      "**Question 1: is the noun SINGULAR and COUNTABLE (a car, a problem, a student)?** If yes, it can never stand alone: it needs a / an / the / my / this. (“She is doctor” and “I bought car” are impossible.)",
      "**Question 2: do the reader and I both know exactly which one?** If yes, use **the**: it was mentioned before (“I saw a man. **The** man was running”), it is unique (the sun, the government, the internet), or the sentence tells you which one (“**the** capital of France”, “**the** number of students”).",
      "**Question 3: am I talking about the idea in general (plural or uncountable)?** Then use **no article**: “Education is important.” “Children need love.” “Technology changes society.” This is the biggest difference from Portuguese.",
      "**a or an depends on the SOUND, not the letter:** an hour (silent h), an umbrella; but a university (/j/ sound), a European country, a one-way street.",
    ],
  },
  formation: [
    { title: "Which article for which noun?", rows: [
      ["Singular countable — new / any", "**a / an**: I saw **a** film. She is **an** engineer."],
      ["Singular countable — known / specific", "**the**: **the** film we saw last night."],
      ["Plural countable — general", "**no article**: Films can change opinions."],
      ["Plural countable — specific", "**the**: **the** films of the 1990s."],
      ["Uncountable — general", "**no article**: **Information** is power. **Water** is essential."],
      ["Uncountable — specific", "**the**: **the** information in this report."],
    ]},
    { title: "a or an?", rows: [
      ["Consonant SOUND", "**a** car · **a** university (/j/) · **a** European · **a** one-day course."],
      ["Vowel SOUND", "**an** apple · **an** hour (silent h) · **an** honest man · **an** MBA (/em/)."],
      ["The", "Pronounced /ðə/ before a consonant sound and /ði/ before a vowel sound. The spelling never changes."],
    ]},
  ],
  whenUse: [
    { rule: "a / an: first mention, or one of many (new information).", ex: "I have **a** meeting at three." },
    { rule: "a / an: a person's job or role.", ex: "My father is **a** pilot." },
    { rule: "a / an: ‘per’ (price, frequency).", ex: "I study English three times **a** week." },
    { rule: "the: the second mention.", ex: "We bought a house. **The** house has a small garden." },
    { rule: "the: unique or shared by everyone.", ex: "Pollution is damaging **the** environment. **The** government should act." },
    { rule: "the: a phrase or clause tells us which one; superlatives and ordinals.", ex: "**The** number of cars is rising. It is **the** most serious problem. **The** first step is education." },
    { rule: "no article: general plural and uncountable ideas.", ex: "**Teachers** need support. **Technology** has changed communication." },
    { rule: "no article: most countries and cities, languages, meals, sports, most subjects.", ex: "I study **English** in **Brazil**. We have **lunch** at one." },
  ],
  whenNot: [
    { rule: "Do NOT use ‘the’ with a general idea (uncountable or plural).", ex: "✗ The education is important. → ✓ **Education** is important." },
    { rule: "Do NOT use a / an with uncountable nouns or plurals (information, advice, knowledge, equipment, furniture, research).", ex: "✗ I need an advice. → ✓ I need **some advice** / **a piece of advice**." },
    { rule: "Do NOT leave out the article before a singular countable noun.", ex: "✗ She is engineer. → ✓ She is **an** engineer." },
    { rule: "Do NOT use ‘the’ before most country names (but yes with the UK, the USA, the Netherlands, the Philippines).", ex: "✗ He lives in the Brazil. → ✓ He lives in **Brazil**." },
    { rule: "Do NOT use an article before a possessive (my, your, his, her, their, our).", ex: "✗ The my friend → ✓ **My** friend." },
    { rule: "Do NOT choose a / an by the letter: check the sound.", ex: "✗ an university, a hour → ✓ **a** university, **an** hour." },
  ],
  contrast: {
    a: "General (no article)", b: "Specific (the)",
    rows: [
      { ctx: "Life", a: "**Life** is difficult.", b: "**The** life of a student is difficult.", diff: "No article = life in general. The + of-phrase = a particular kind of life." },
      { ctx: "Children", a: "**Children** learn quickly.", b: "**The** children in my class learn quickly.", diff: "General group vs the specific children we are talking about." },
      { ctx: "Music", a: "I love **music**.", b: "**The** music at the party was too loud.", diff: "Music as a general idea vs the particular music at one event." },
      { ctx: "A / the", a: "I need **a** pen.", b: "I need **the** pen on your desk.", diff: "Any pen vs one that both of us can identify." },
      { ctx: "University", a: "She went to **university** (as a student).", b: "She went to **the** university (the building, for example to meet someone).", diff: "Institution in its normal purpose (no article) vs a particular place." },
      { ctx: "Technology", a: "**Technology** has changed society.", b: "**The** technology we use today is very advanced.", diff: "The idea in general vs the particular technology that is defined by ‘we use today’." },
    ],
  },
  examples: {
    a1: ["I have **a** dog. **The** dog is brown.", "She is **an** engineer.", "I like **music**.", "We had dinner in **a** restaurant."],
    b1: ["I bought **a** laptop last week, but **the** screen is already broken.", "**Water** is essential for life, but **the** water in this area is not safe to drink.", "He wants to be **a** doctor and work in **a** hospital."],
    natural: ["I'm looking for **a** flat near **the** city centre, ideally with **a** balcony.", "**People** often forget that **the** hardest part of learning English is **practice**, not grammar.", "She's **the** kind of person who always sees **the** best in **people**."],
    ielts: ["The graph shows **the** percentage of households with **internet** access, and **the** number of users rose steadily.", "**Education** plays a vital role in reducing **poverty**, but **the** government must invest in **the** quality of teaching.", "**A** number of experts believe that **the** internet has made **it** easier to find **information**."],
  },
  pitfalls: [
    { say: "A educação é importante / A vida é difícil / Os brasileiros gostam de futebol", wrong: "The education is important. · The life is difficult. · The Brazilians love football.", right: "**Education** is important. · **Life** is difficult. · **Brazilians** love football.", pt: "Em português usamos o artigo definido com ideias gerais (a educação, a vida, os brasileiros). Em inglês, ideias gerais NÃO levam artigo. Este é o erro mais frequente: traduzir ‘a/o/as/os’ por ‘the’. Pergunte-se: estou falando de algo específico ou da ideia em geral?" },
    { say: "Ela é médica / Eu tenho carro", wrong: "She is doctor. · I have car.", right: "She is **a** doctor. · I have **a** car.", pt: "Em português dizemos ‘ela é médica’ sem artigo. Em inglês, substantivo contável singular precisa de a / an (ou the, my…). Profissões sempre levam a / an." },
    { say: "Preciso de um conselho / informações", wrong: "I need an advice. · I need some informations.", right: "I need **some advice** / **a piece of advice**. · I need **some information**.", pt: "Informação, conselho, conhecimento e equipamento são incontáveis em inglês. Não têm plural (informations ✗) e não aceitam a / an (an advice ✗). Use some, a piece of, a bit of." },
    { say: "O Brasil / A França / Os Estados Unidos", wrong: "I live in the Brazil. · He went to the France.", right: "I live in **Brazil**. · He went to **France**. · the **United States**, the **UK**.", pt: "Em português quase todo país leva artigo (o Brasil, a França). Em inglês, a maioria dos países NÃO leva the. Exceções: nomes plurais ou com ‘Republic/Kingdom/States’: the USA, the UK, the Netherlands, the Philippines." },
    { say: "O meu amigo / A minha casa", wrong: "The my friend is nice. · I love the my house.", right: "**My** friend is nice. · I love **my** house.", pt: "Em português ‘o meu amigo’ é normal. Em inglês não se usa artigo com possessivo: my friend, not the my friend." },
    { say: "Uma universidade / uma hora", wrong: "an university · a hour", right: "**a** university · **an** hour", pt: "Em inglês, a / an depende do SOM inicial, não da letra. University começa com som /j/ (consoante) → a. Hour tem h mudo → an." },
  ],
  errors: [
    { wrong: "The education is the key to success.", right: "**Education** is the key to success.", why: "‘Education’ is a general idea (uncountable), so no article. ‘The key to success’ keeps ‘the’ because ‘to success’ tells us which key." },
    { wrong: "She is engineer.", right: "She is **an** engineer.", why: "‘Engineer’ is a singular countable noun and cannot stand alone. Jobs take a / an; ‘an’ because ‘engineer’ starts with a vowel sound." },
    { wrong: "I need an advice.", right: "I need **some advice**.", why: "‘Advice’ is uncountable: no a / an and no plural. Use some or a piece of." },
    { wrong: "Many people believe that the technology makes life easier.", right: "Many people believe that **technology** makes life easier.", why: "Technology in general = no article." },
    { wrong: "He bought an university degree.", right: "He earned **a** university degree.", why: "University starts with a /j/ sound (a consonant sound), so a." },
    { wrong: "She lives in the Brazil.", right: "She lives in **Brazil**.", why: "Most countries take no article (exceptions: the UK, the USA, the Netherlands…)." },
    { wrong: "Pollution is damaging environment.", right: "Pollution is damaging **the** environment.", why: "‘The environment’ is unique and shared by everyone, so it takes the. ‘Pollution’ in general takes none." },
    { wrong: "I like the my new job.", right: "I like **my** new job.", why: "A possessive replaces the article. Never use both." },
  ],
  ielts: {
    t1: ["‘The’ is common because the chart is specific: “**The** chart shows **the** percentage of…”, “**The** highest figure was…”, “**The** number of cars…”.", "Years and periods: “in **the** 1990s”, “over **the** period”. Years alone take no article: “in 2005”.", "A number of / The number of: “**A** number of countries (several) **have**…” vs “**The** number of countries **has**…” (the total)."],
    t2: ["General opinions use no article: “**Governments** should invest in **education**.” Do not add ‘the’ to every noun.", "Specific references use ‘the’: “**The** government of Brazil”, “**the** problem of unemployment”, “**the** elderly”.", "A good habit: for every singular countable noun in your essay, check that it has a / an / the / my / this."],
    speaking: ["Jobs: “I'm **a** nurse.” “I work for **a** small company.”", "Hobbies and sports take no article: “I play **football**.” “I love **music**.”", "A wrong article rarely stops understanding, but accurate articles in the first sentence create a strong impression."],
    tip: "When unsure, run the three questions: (1) singular countable → needs something; (2) both of us know exactly which → the; (3) general plural or uncountable → no article. Do not add 'the' just to sound formal.",
  },
  understand: [
    { id: "u1", q: "Why do we say “Education is important” but “The education system in Brazil needs reform”?", opts: ["The first is a general idea (no article); the second is specific because ‘system in Brazil’ tells us which one.", "Because ‘system’ is countable.", "There is no difference."], a: 0, why: "General idea = zero article. A phrase that defines it (system in Brazil) makes it specific, so ‘the’." },
    { id: "u2", q: "Why: “I saw a man. The man was running.”", opts: ["First mention = a (new information); second mention = the (now known).", "Both articles are interchangeable.", "‘Man’ always takes ‘a’."], a: 0, why: "A introduces; the refers back to what both speakers now know." },
    { id: "u3", q: "Why is “She is doctor” wrong?", opts: ["A singular countable noun cannot stand alone; jobs need a / an.", "‘Doctor’ is uncountable.", "Because ‘she’ requires ‘the’."], a: 0, why: "Singular countable nouns need a determiner. Portuguese ‘Ela é médica’ is fine because Portuguese works differently." },
    { id: "u4", q: "Why do we say ‘an hour’ but ‘a university’?", opts: ["The choice depends on the sound: hour starts with a vowel sound, university with a /j/ consonant sound.", "It is just an exception to memorise.", "‘An’ is used with long words."], a: 0, why: "A/an follows the first SOUND, not the first letter." },
    { id: "u5", q: "What is the difference between “The number of students is rising” and “A number of students are rising hands”? (focus on the first words)", opts: ["‘The number of’ refers to the total figure (singular verb); ‘a number of’ means ‘several’ (plural verb).", "No difference.", "‘A number of’ is only used in speaking."], a: 0, why: "The = a defined quantity. A number of = several. This also changes the verb." },
    { id: "u6", q: "‘The environment’ and ‘the internet’ are general, yet they take ‘the’. Why?", opts: ["They are unique things that everybody shares, so the reader knows exactly which one.", "They are plural.", "It is a mistake that is accepted."], a: 0, why: "Unique/shared things are ‘known’ by definition, so the." },
  ],
  practice: [
    { id: "p1", stage: "recognise", q: "Which sentence is correct?", opts: ["She is a engineer.", "She is an engineer.", "She is engineer."], a: 1, why: "Job = a / an; ‘engineer’ starts with a vowel sound = an.", natural: "She is an engineer." },
    { id: "p2", stage: "recognise", q: "Which sentence is correct?", opts: ["The information is power.", "An information is power.", "Information is power."], a: 2, why: "General idea + uncountable = no article.", natural: "Information is power." },
    { id: "p3", stage: "recognise", q: "She has ___ university degree.", opts: ["an", "a", "the"], a: 1, why: "University begins with a /j/ sound (consonant), so a.", natural: "She has a university degree." },
    { id: "p4", stage: "recognise", q: "Which sentence is correct?", opts: ["Pollution harms environment.", "The pollution harms the environment.", "Pollution harms the environment."], a: 2, why: "General pollution = no article; the environment is unique = the.", natural: "Pollution harms the environment." },
    { id: "p5", stage: "choice", q: "I need ___ advice about my essay.", opts: ["an", "some", "a"], a: 1, why: "Advice is uncountable: some / a piece of.", natural: "I need some advice about my essay." },
    { id: "p6", stage: "choice", q: "___ number of cars on the road has increased.", opts: ["A", "The", "(no article)"], a: 1, why: "‘The number of’ = the total figure. The singular verb (has) confirms it.", natural: "The number of cars on the road has increased." },
    { id: "p7", stage: "choice", q: "___ children need love and attention.", opts: ["The", "(no article)", "A"], a: 1, why: "Children in general: plural, general idea = no article.", natural: "Children need love and attention." },
    { id: "p8", stage: "choice", q: "I saw ___ accident yesterday. ___ accident was serious.", opts: ["an / The", "the / An", "an / An"], a: 0, why: "First mention an (vowel sound); second mention the.", natural: "I saw an accident yesterday. The accident was serious." },
    { id: "p9", stage: "choice", q: "He lives in ___ United States, but his sister lives in ___ Spain.", opts: ["the / (no article)", "(no article) / the", "the / the"], a: 0, why: "The United States takes the; most countries (Spain) do not.", natural: "He lives in the United States, but his sister lives in Spain." },
    { id: "p10", stage: "choice", q: "___ elderly need more support from society.", opts: ["The", "(no article)", "An"], a: 0, why: "The + adjective refers to a whole group of people (the elderly, the poor, the young).", natural: "The elderly need more support from society." },
  ],
  transform: [
    { id: "r1", stage: "transform", q: "Correct the sentence: “She is engineer.”", spec: { must: ["\\bshe is an engineer\\b"] }, model: "She is an engineer.", why: "Singular countable noun + vowel sound = an." },
    { id: "r2", stage: "transform", q: "Correct the sentence: “I need an advice.”", spec: { must: ["\\b(some|a piece of|a bit of|more|good|any|your|his|her) advice\\b"], mustNot: [{ re: "\\ban advice\\b", why: "Advice is uncountable: no ‘an’." }] }, model: "I need some advice.", why: "Uncountable: some / a piece of." },
    { id: "r3", stage: "transform", q: "Correct the sentence: “The education is important for the society.”", spec: { must: ["\\beducation is important for society\\b"], mustNot: [{ re: "\\bthe (education|society)\\b", why: "General ideas take no article." }] }, model: "Education is important for society.", why: "General ideas: no article." },
    { id: "r4", stage: "transform", q: "Add the missing article: “Pollution is damaging environment.”", spec: { must: ["\\bthe environment\\b"] }, model: "Pollution is damaging the environment.", why: "The environment is unique and shared: the." },
  ],
  produce: [
    { id: "s1", stage: "guided", q: "Write ONE sentence about your job or what you study, using a or an.", spec: { must: ["\\b(a|an) [a-z]+"], mustNot: [{ re: "\\ban (university|european|useful|unit|unique|uniform|user)\\b", why: "/j/ sound = a, not an." }, { re: "\\ba (hour|honest|honour|employee|engineer|architect|accountant|assistant|artist|english|administrator|electrician|economist|officer)\\b", why: "Vowel sound = an." }, { re: "\\b(I am|I'm|I work as) (nurse|teacher|engineer|doctor|student|manager|lawyer|designer|developer|accountant)\\b", why: "Jobs need a / an." }] }, model: "I am a nurse and I work in a public hospital.", hint: "I am a / an + job", why: "Jobs take a / an." },
    { id: "s2", stage: "guided", q: "Write TWO sentences: introduce something with a / an, then refer to it again with the.", spec: { must: ["\\b(a|an) [a-z]+", "\\bthe [a-z]+"], mustNot: [] }, model: "I bought a bike last month. The bike is very light.", hint: "first mention → a/an; second mention → the", why: "New information = a/an. Known = the." },
    { id: "s3", stage: "produce", q: "Write ONE general sentence about children, students, teachers or parents. (General plural: decide the article yourself.)", spec: { must: ["\\b(children|students|teachers|parents|doctors)\\b"], mustNot: [{ re: "\\b(the|a|an) (children|students|teachers|parents|doctors)\\b(?! (in|of|at|who|that|from))", why: "A general plural takes no article." }] }, model: "Children learn languages more easily than adults.", why: "General plural = no article." },
    { id: "s4", stage: "produce", q: "(No hints.) Write ONE general sentence about education, technology, health or money.", spec: { must: ["\\b(education|technology|health|money)\\b"], mustNot: [{ re: "\\b(the|a|an) (education|technology|health|money)\\b(?! (system|sector|we|that|of|in|industry))", why: "A general uncountable idea takes no article." }] }, model: "Technology has made communication much easier.", why: "General uncountable idea = no article." },
  ],
  apply: {
    prompt: "Write 80–120 words about the role of education in society. Use at least two general ideas with NO article (for example: Education…, Children…), at least two uses of ‘the’ for specific things (for example: the government, the education system, the number of…), and at least one a / an.",
    min: 80, max: 120,
    mustUse: [
      { label: "No article with a general idea (Education…, Children…, Technology…)", re: "(?<!\\bthe )(?<!\\ba )(?<!\\ban )\\b(" + GEN + "|children|students|teachers|young people|people|parents)\\b", min: 2 },
      { label: "‘the’ for something specific or unique (the government, the number of, the education system…)", re: "\\bthe (?!the\\b)[a-z]+", min: 2 },
      { label: "a / an with a singular noun", re: "\\b(a|an) (?!lot\\b|few\\b|number\\b)[a-z]+", min: 1 },
    ],
    mustNot: [
      { re: "\\bthe (" + GEN + ")\\b(?! (system|sector|industry|of|in|that|which|we|people|level|available|provided|quality|budget))", why: "A general idea takes no article (check: is it specific?)." },
      { re: "\\ban? (information|advice|knowledge|research|homework|equipment|furniture|education|technology)\\b", why: "Uncountable noun with a / an." },
      { re: "\\b(is|am|are|was|were) (doctor|teacher|engineer|student|nurse|lawyer|manager)\\b", why: "A job (singular countable) needs a / an." },
      { re: "\\ban (university|european|useful|unit)\\b|\\ba (hour|honest)\\b", why: "a / an follows the SOUND." },
      { re: "\\bthe (my|your|his|her|their|our)\\b", why: "Do not use the with a possessive." },
    ],
  },
  transfer: [
    { id: "t1", q: "Speaking Part 1. Examiner: “What do you do?” You: “I'm ___ nurse. I work in ___ hospital in Recife.”", opts: ["a / a", "a / the", "(no article) / a"], a: 0, why: "A job takes a; the hospital is new information for the examiner, so a." },
    { id: "t2", q: "From an essay: “Many experts argue that ___ pollution is the main threat to ___ environment.”", opts: ["(no article) / the", "the / the", "the / an"], a: 0, why: "Pollution in general = no article; the environment is unique = the." },
    { id: "t3", q: "IELTS Task 1: “___ percentage of households with internet access rose, and ___ highest figure was recorded in 2018.”", opts: ["The / the", "A / a", "The / a"], a: 0, why: "Both refer to a specific percentage on the chart; superlative = the." },
    { id: "t4", q: "A news report: “___ scientists have discovered ___ new species of frog in the Amazon.”", opts: ["(no article) / a", "The / a", "(no article) / the"], a: 0, why: "Scientists in general (plural) = no article. A new species = new information = a." },
    { id: "t5", q: "A friend asks what you do and where you work. Answer in TWO short sentences. (Choose articles yourself.)", spec: { must: ["\\b(a|an) [a-z]+"], mustNot: [{ re: "\\b(I am|I'm|I work as) (nurse|teacher|engineer|doctor|student|manager|lawyer|designer|developer|accountant)\\b", why: "Jobs need a / an." }] }, model: "I'm a teacher. I work at a school near the city centre.", why: "Jobs and new places take a / an." },
    { id: "t6", q: "Write ONE sentence for an essay saying that governments should spend more on education. (Think about the articles!)", spec: { must: ["\\bgovernments?\\b", "\\beducation\\b"], mustNot: [{ re: "\\bthe education\\b(?! (system|sector|budget))", why: "General idea: no article." }, { re: "\\bthe governments\\b", why: "General plural: no article." }] }, model: "Governments should spend more money on education.", why: "General plural and general uncountable idea: no article." },
  ],
};
